# Inspect Final Project Tables From `BOW` Downward

This notebook documents each unique UVA Box table referenced in `FinalProject.ipynb` from the `BOW` section downward. Each table gets its own pair of cells:

- a short markdown description of the table being inspected
- a code cell that loads the table and reports its shape, number of observations, column names, and `head(10)`

The loader tries the UVA Box link first and falls back to the matching local project file when needed.

In [1]:
from io import BytesIO
from pathlib import Path
from textwrap import fill
from urllib.parse import parse_qsl, urlencode, urlparse, urlunparse

import pandas as pd
import requests
from IPython.display import Markdown, display

pd.set_option('display.max_columns', 100)
pd.set_option('display.max_colwidth', 120)

PROJECT_ROOT = Path.cwd()

def add_download_flag(url: str) -> str:
    parsed = urlparse(url)
    query = dict(parse_qsl(parsed.query, keep_blank_values=True))
    query['download'] = '1'
    return urlunparse(parsed._replace(query=urlencode(query)))


def load_table(box_url: str, local_path: str, file_format: str) -> tuple[pd.DataFrame, str]:
    local_file = PROJECT_ROOT / local_path
    try:
        response = requests.get(add_download_flag(box_url), timeout=90)
        response.raise_for_status()
        if file_format == 'parquet':
            df = pd.read_parquet(BytesIO(response.content))
        elif file_format == 'csv':
            df = pd.read_csv(BytesIO(response.content))
        else:
            raise ValueError(f'Unsupported format: {file_format}')
        return df, 'Box download'
    except Exception:
        if not local_file.exists():
            raise FileNotFoundError(f'Could not load {local_path} from Box or local workspace.')
        if file_format == 'parquet':
            df = pd.read_parquet(local_file)
        elif file_format == 'csv':
            df = pd.read_csv(local_file)
        else:
            raise ValueError(f'Unsupported format: {file_format}')
        return df, 'Local fallback'


def inspect_table(section: str, box_url: str, local_path: str, file_format: str, preview_rows: int = 10) -> pd.DataFrame:
    df, load_source = load_table(box_url, local_path, file_format)
    print(f'Section: {section}')
    print(f'Box URL: {box_url}')
    print(f'Local file: {local_path}')
    print(f'Loaded from: {load_source}')
    print(f'Format: {file_format}')
    print(f'Shape: {df.shape[0]:,} rows x {df.shape[1]:,} columns')
    print(f'Number of observations: {df.shape[0]:,}')
    print('Column names:')
    print(fill(', '.join(str(col) for col in df.columns), width=100))
    display(df.head(preview_rows))
    return df

## BOW

This section inspects the project `BOW` table, the long bag-of-words table used as the starting point for several downstream models.

The saved `bow.parquet` now includes both the raw term count column `n` and a row-level `tfidf` value for each observed term occurrence in each bag.

In [2]:
BOW = inspect_table(
    section='BOW',
    box_url='https://virginia.box.com/shared/static/hyvirbfhuo5vcjegyjhsrn2ea1d6ikhq.parquet',
    local_path='bow.parquet',
    file_format='parquet'
)

Section: BOW
Box URL: https://virginia.box.com/shared/static/hyvirbfhuo5vcjegyjhsrn2ea1d6ikhq.parquet
Local file: bow.parquet
Loaded from: Box download
Format: parquet
Shape: 1,775,569 rows x 5 columns
Number of observations: 1,775,569
Column names:
country_id, article_n, term_str, n, tfidf

    country_id  article_n      term_str   n      tfidf
0  Afghanistan          1    accordance   1   2.950516
1  Afghanistan          1      adhering   1   9.123469
2  Afghanistan          1      admiring   1  10.732907
3  Afghanistan          1   afghanistan   3  22.602701
4  Afghanistan          1           all   3   8.100179
5  Afghanistan          1         allah   2  15.283729
6  Afghanistan          1      almighty   1   6.597740
7  Afghanistan          1            an   1   2.501132
8  Afghanistan          1           and  18  21.972341
9  Afghanistan          1  appreciating   1   9.816616

## DTM

This section inspects the document-term matrix derived from the project `BOW` table.

In [3]:
DTM = inspect_table(
    section='DTM',
    box_url='https://virginia.box.com/shared/static/tipo8kaykn4xapb85etbvtiq8b5w07ut',
    local_path='dtm.parquet',
    file_format='parquet'
)

Section: DTM
Box URL: https://virginia.box.com/shared/static/tipo8kaykn4xapb85etbvtiq8b5w07ut
Local file: dtm.parquet
Loaded from: Box download
Format: parquet
Shape: 33,726 rows x 24,735 columns
Number of observations: 33,726
Column names:
aa, aalim, aargau, ab, aba, ababa, abadam, abaiang, abaji, abak, abakaliki, abandon, abandoned,
abandoning, abandonment, abandons, abariringa, abases, abasi, abasto, abate, abatement, abatements,
abattoir, abattoirs, abbot, abbottabad, abbreviated, abbreviations, abd-allah, abdallah, abdel,
abdicate, abdicated, abdicates, abdication, abdications, abduct, abduction, abdul, abdulai,
abdulaziz, abdullah, abemama, abeokuta, abetment, abets, abetting, abeyance, abi, abia, abide,
abided, abides, abiding, abilities, ability, abim, abinger, abish, abjure, abkhazia, abkhazian,
able, able-bodied, abler, ablution, ably, abnegation, abnormal, abnormalities, abnormality,
abnormally, aboard, abode, aboh-mbaise, abolish, abolished, abolishes, abolishing, abolishment,
abolition, abonar, aboriginal, aborigine, aborigines, abortion, about, above, above-cited, above-
mentioned, above-referenced, above-specified, aboveground, abovementioned, abr, abreast, abridge,
abridged, abridgement, abridgements, abridges, abridging, abroad, abrogate, abrogated, abrogates,
abrogating, abrogation, abrogatory, abruzzi, abs, abscissa, absconding, absence, absences, absent,
absent-ones, absented, absentee, absentees, absentia, absenting, absents, absoluta, absolute,
absolutely, absolutory, absolve, absolved, absolving, absorb, absorbed, absorption, abstain,
abstained, abstaining, abstains, abstention, abstentions, abstract, abstraction, abu, abuja,
abundance, abundant, abuse, abuse-of-rights, abused, abuses, abusing, abusive, abyei, ac, academia,
academic, academical, academically, academicians, academics, academies, academy, accede, acceded,
accedes, acceding, accelerate, accelerated, accelerates, accelerating, accept, acceptable,
acceptance, accepted, accepting, accepts, accesiones, access, accessed, accessibility, accessible,
accessing, accession, accessories, accessory, accident, accidents, accion, acclaiming, acclamation,
acclamations, accommodate, accommodates, accommodating, accommodation, accommodations, accompanied,
accompany, accompanying, accomplice, accomplices, accomplish, accomplished, accomplishes,
accomplishing, accomplishment, accomplishments, accord, accordance, accorded, accorder, according,
accordingly, accords, accosted, account, accountability, accountable, accountably, accountancy,
accountant, accountant-general, accountants, accounted, accounting, accounts, accredit,
accreditation, accredited, accrediting, accredits, accreditted, accrete, accretion, accretions,
accrual, accruals, accrue, accrued, accrues, accruing, accumulate, accumulated, accumulation,
accuracy, accurate, accurately, accursed, accusation, accusations, accusatorial, accusatory, accuse,
accused, accuser, accusers, accusing, acervo, ach, achieve, achieved, achievement, achievements,
achieves, achieving, achodo, acholi, achwa, acids, acing, acknowledge, acknowledged,
acknowledgement, acknowledgements, acknowledges, acknowledging, acknowledgment, aconsejables,
aconseje, acoustical, acquaculture, acquaint, acquaintance, acquainted, acquainting, acquaints,
acquiesce, acquiescence, acquirable, acquire, acquired, acquirement, acquires, acquiring, acquis,
acquisition, acquisitions, acquisitive, acquit, acquittal, acquitted, acquitting, acre, acreages,
acronyms, across, act, act-the, act-to, acted, actifs, acting, actio, action, actionable, actions,
actions-incitement, activate, activated, activating, activation, active, actively, actives,
activism, activists, activite, activities, activity, acto, acton, actor, actors, acts, actuaciones,
actuado, actual, actualite, actualization, actually, actuarial, actuary, acu, acuerden, acute, ad,
ad-hoc, adam, adamaoua, adamawa, adami, adapt, adaptability, adaptation, adaptations, adapted,
adapting, adaptions, adapts, adat, adavi, add, added, addenda, addendum, addict, addicted,
addiction, addictions, addicts, adding, addington, addis, addition, additional, additionally,
additions, address, address-on, addressed, addressee, addresses, addressing, adds, addu, adduce,
adduced, adelaide, aden, adequacy, adequate, adequately, adh, adhere, adhered, adherence,
adherences, adherents, adherer, adheres, adhering, adhesion, adhi, adhiniyam, adi, adibasi, adige,
adil, adilnya, adjacent, adjala, adjika, adjoining, adjourn, adjourned, adjourning, adjournment,
adjournments, adjourns, adjucators, adjudge, adjudged, adjudicate, adjudicated, adjudicates,
adjudicating, adjudication, adjudications, adjudicative, adjudicator, adjudicators, adjudicatory,
adjumani, adjunct, adjunction, adjuncts, adjust, adjustable, adjusted, adjusting, adjustment,
adjustments, adjusts, admaston, administer, administered, administering, administers,
administradores, administrate, administrated, administrates, administrating, administration,
administrations, administrative, administrative-economic, administrative-procedural, administrative-
territorial, administratively, administratively-territorial, administrator, administrator-general,
administrators, administrators-general, admiral, admirals, admiralty, admiration, admiring,
admissibility, admissible, admission, admissions, admit, admits, admittance, admitted, admitting,
admonish, admonishing, admonition, ado, adolescence, adolescent, adolescents, adolphustown, adopt,
adopted, adoptee, adopter, adopting, adoption, adoptions, adoptive, adopts, adorned, adriatic, ads,
adult, adulterate, adulteration, adulthood, adults, advance, advanced, advancement, advancements,
advances, advancing, advantage, advantaged, advantageous, advantages, advent, adventure,
adventurers, adversarial, adversaries, adversary, adverse, adversely, adversity, advertised,
advertisement, advertisements, advertisers, advertising, advice, advices, advisability, advisable,
advise, advised, adviser, advisers, advises, advising, advisor, advisors, advisory, advocacy,
advocacy-general, advocacy-generals, advocate, advocate-general, advocated, advocates, advocating,
adygeya, aegis, aerated, aerial, aerodrome, aerodromes, aeronautic, aeronautical, aeronautics,
aerospace, aesthetic, af, afar, afectar, affair, affaire, affaires, affairs, affect, affected,
affectees, affecting, affection, affective, affects, afferents, affidavit, affidavits, affiliate,
affiliated, affiliates, affiliating, affiliation, affiliations, affinities, affinity, affirm,
affirmation, affirmations, affirmative, affirmed, affirming, affirms, affix, affixed, afflicted,
afflictive, affluent, affluents, afford, affordable, afforded, affording, affords, afforestation,
affronts, afghan, afghanistan, afijio, afikpo, afore-mentioned, aforementioned, aforesaid,
aforetime, afresh, africa, africains, african, africans, afrika, afrikaans, afro-arab, afro-
bolivian, afro-brazilian, afro-ecuadorian, afro-ecuadorians, after, aftermath, afterward,
afterwards, afurika, ag, agaie, again, against, agalega, agama, agatu, agave, age, age-limit, age-
old, aged, agege, agencies, agency, agenda, agendas, agent, agentes, agents, ages, agglomeration,
agglomerations, aggravate, aggravating, aggravation, aggregate, aggregated, aggregates, aggregating,
aggregation, aggression, aggressions, aggressive, aggressors, aggrieved, aghia, aghion, aginsk,
agitate, agitation, ago, agong, agonising, agoyan, agraria, agrarian, agree, agreed, agreeing,
agreement, agreements, agrees, agregado, agri-food, agricultura, agricultural, agricultural-
livestock, agriculture, agro-allied, agro-environmental, agro-industrial, agro-industry, agro-
linked, agroambiental, agrochemical, agrochemicals, agroindustrial, agrological, agropecuaria,
agrupaciones, agruparse, agu, aguascalientes, aguata, aguinaldo, agwara, ah, ahead, ahiazu-mbaise,
ahinza, ahkam, ahmadis, ahmed, aho, ahoada, ahy, ai-maghrib, aid, aide, aide-de-camp, aided, aides,
aiding, aids, aigrettes, ail, ailinginae, ailinglaplap, ailments, ailuk, aim, aimed, aimeliik,
aiming, aims, ain, aina, aioda, air, air-force, airai, aircraft, aircrafts, aires, airfields,
airforce, airok, airport, airports, airships, airspace, airstrips, airtime, airwaves, airways,
aishwarya, aisladamente, aiyedade, aiyedire, aiyekire, aja-raja, ajaokuta, ajara, ajc, ajeromi-
ifelodun, ajigu, ajingi, ajm-bill, ajm-constitution, ajm-corrupt, ajm-criminal, ajm-debt, ajm-
disciplinary, ajm-disciplined, ajm-electoral, ajm-eligible, ajm-forced, ajm-hate, ajm-human, ajm-
includes, ajm-judicial, ajm-land, ajm-oath, ajm-pension, ajm-political, ajm-public, ajm-republic,
ajm-sentence, ajm-state, ajm-subordinate, ajm-this, ajm-written, ajman, ajq, ajustarse, ajuste,
ajyalg, akamkpa, akan, akar, akara, akasiru, akbar, akim, akims, akin, akinyele, akiykatchy, akko,
akoko, akoko-edo, akpabuyo, akrishik, aksakal, aksakaly, akuku, akure, akwa, akwanga, al, al-ad-ha,
al-amr, al-anfal, al-assi, al-awwal, al-azhar, al-bikaa, al-douha, al-dujail, al-faqih, al-fitr, al-
fuqaha, al-hima, al-hudud, al-hussein, al-imran, al-kabir, al-kamar, al-majlis, al-munkar, al-nahr,
al-nahy, al-nuwwab, al-saud, al-shoura, al-shura, al-taqlid, al-watani, alala, alam, alania, alap,
alarm, alava, albania, albanian, albanians, albasu, albeit, albermarle, albert, alberta, albion,
albums, alcalde, alcaldes, alcances, alcanzan, alcanzaren, alcock, alcohol, alcoholic, alcoholics,
alcoholism, aldabra, alderman, aldermen, alegre, aleiro, alert, alerte, alexander, alexandria,
alexandrine, alfaro, alfaro-peace, alfonso, algemene, algeria, algerian, algerians, algiers, algoma,
algona, ali, alia, aliba, alice, alien, alienable, alienate, alienated, alienation, alienations,
aliens, aligarh, alight, align, aligned, aligning, alignment, alike, alimentaria, alimenticias,
alimenticios, alimony, alimosho, aliquot, alive, alkaleri, alkalo, all, all-around, all-india, all-
nation, all-pakistan, all-people, all-powerful, all-round, all-ukrainian, allah, allahu, allanados,
allanando, allanar, allegados, allegation, allegations, allege, alleged, allegedly, alleger,
alleges, allegiance, allegience, alleging, aller, alleviate, alleviated, alleviating, alleviation,
alliance, alliances, allied, allies, allocate, allocated, allocates, allocating, allocation,
allocations, allodial, allot, allotment, allotments, allotted, allottees, allow, allowance,
allowances, allowed, allowing, allows, alloys, alluded, allusion, almarhum, almighty, almost, aloft,
alone, along, alongside, aloud, alphabet, alphabetical, alphonse, alpine, already, als, also, also-
in, alta, altai, altaqlid, alter, alteration, alterations, altered, altering, alternabilidad,
alternate, alternated, alternately, alternates, alternating, alternation, alternations, alternative,
alternatively, alternatives, alters, althingi, although, alto, altogether, aludidos, alumni, alupe,
alur, always, alzado, am, ama, amable, amacuro, amalgamated, amalgamation, aman, amani, amap, amar,
amaranth, amass, amateur, amazigh, amazighe, amazighit, amazing, amazon, amazonas, amazonia,
amazonian, amb, ambassador, ambassadorial, ambassadors, ambeno, ambergris, ambiguities, ambiguity,
ambiguous, ambit, ambition, ambitions, ambito, ambits, ambulance, ambushes, amdendment, amdt, ameen,
ameliorate, amelioration, amenable, amenagement, amend, amendable, amendatory, amended, amending,
amendment, amendments, amends, amenities, america, american, americans, amerindian, amerindians,
amhara, amharic, amherst, amicable, amicably, amidst, amilcar, amim, aminzi, amir, amirantes,
amirate, amiri, amity, amkeni, amman, ammodar, ammunition, ammunitions, amnesties, amnesty, amoda,
amolatar, among, amongst, amortisation, amortization, amortizations, amount, amounted, amounting,
amounts, ampara, amparado, amparar, amparo, ample, ampliado, ampliar, amplification, amplified,
amplio, amply, amsterdam, amur, amuria, amuru, amusement, amusements, amuwo-odofin, amyotha, an, an-
organizations, anakandriamaso, analagous, analfabetismo, analogies, analogous, analogously, analogy,
analphabetism, analyse, analysed, analyses, analysing, analysis, analytic, analytical, analyze,
analyzed, anam, anambra, anaocha, anastasia, anatocism, anc, ancap, ancash, ancestor, ancestors,
ancestral, ancestrally, ancestry, anchor, anchored, ancient, ancillary, and, andalusian, andaman,
andean, andereko, andhra, andloyalty, andolan, andoni, andorra, andorran, andorrans, andraikitra,
andres, andreserve, andriamanitra, andriananahary, ands, andto, anew, anfal, ang, angaur, anger,
angket, angkor, angle, angled, angles, anglesea, anglo-french, anglo-indian, anglo-liberian,
anglong, angola, angolan, angolans, anguilla, anibare, animal, animals, animated, animates,
animating, animation, animism, animosity, aninri, aniocha, anjouan, anka, ankanavaka, ankara,
ankole, ankpa, annals, anne, annex, annexed, annexes, annexing, annexure, anniversaries,
anniversary, anno, annotate, annotation, announce, announced, announcement, announcements,
announces, announcing, annual, annually, annuities, annuity, annul, annulled, annulling, annulment,
annuls, annum, anointed, anomaly, anonyme, anonymity, another, anson, answer, answerability,
answerable, answered, answering, answers, ant, antananarivo, antarctic, antecedent, antecedentes,
antecedents, antecendentes, antedated, antejuicio, antejuicios, anterior, anthem, anthem-sanctioned,
anthropological, anti, anti-colonial, anti-colonialist, anti-competitive, anti-constitutional, anti-
corruption, anti-despotic, anti-discrimination, anti-fascist, anti-graft, anti-imperialist, anti-
interventionist, anti-islamic, anti-japanese, anti-juridical, anti-national, anti-piracy, anti-
smuggling, anti-terrorism, anti-trust, anticipate, anticipated, anticipating, anticipation,
anticipatory, anticolonialist, anticorruption, antidemocratic, antifascist, antigua, antilles,
antimonopoly, antiocheia, antiques, antiquities, antisocial, antonio, antwerp, anuradhapura,
anxiety, anxious, any, anybody, anyone, anyplace, anything, anytime, anywhere, anzoategui, ao,
aoruma, apa, apac, apapa, aparceros, apart, apartheid, apartment, apartments, apatrids, apex,
apexes, apolima, apolitical, apology, aportantes, apostle, apostles, apostolic, appanage, apparatus,
apparent, apparently, appartenance, appeal, appealable, appealed, appealing, appeals, appear,
appearance, appearances, appeared, appearing, appears, appellant, appellants, appellate,
appellation, appellations, append, appended, appendices, appending, appendix, appends, appenzell,
appertain, appertaining, appertains, applause, apples, appliances, applicability, applicable,
applicant, applicants, application, applications, applied, applies, appliquer, apply, applying,
appoint, appoint-appointed, appointed, appointee, appointees, appointer, appointers, appointing,
appointive, appointment, appointments, appoints, apport, apporte, apporter, apportion, apportioned,
apportioning, apportionment, apportions, appraisal, appraisals, appraise, appraised, appraises,
appraising, appreciated, appreciating, appreciation, apprecie, apprehend, apprehended, apprehending,
apprehension, apprentice, apprenticeship, apprised, apprized, approach, approached, approaches,
approaching, approbation, approbations, approbatory, appropriate, appropriated, appropriately,
appropriateness, appropriates, appropriating, appropriation, appropriations, approval, approvals,
approve, approved, approves, approving, approvisionment, approximate, approximately, approximation,
appurtenances, appurtenant, april, aprovechamiento, apt, aptitude, aptitudes, apulia, apure,
aquaculture, aquatic, aquiculture, arab, arab-islamist, arab-muslim, arab-ness, arabia, arabian,
arabic, arabism, arable, arabs, araguaia, aranuka, araona, ararat, arauca, arbiter, arbiters,
arbitraje, arbitral, arbitrament, arbitrarily, arbitrariness, arbitrary, arbitrate, arbitrated,
arbitrates, arbitration, arbitration-procedural, arbitrations, arbitrator, arbitrators, arbitrios,
arboreum, arc, archaeological, archduke, archeological, archipelagic, archipelago, archipelagos,
architectural, architecture, archival, archivar, archive, archived, archives, archyn, arcs, ardent,
ardo-kola, arduous, arduousness, are, area, area-based, areas, arena, arenas, arequipa, arewa-dandi,
argent, argenteuil, argentine, argentines, arguable, argue, argued, argument, arguments, argungu,
ari, arid, aride, aright, aringa, arise, arisen, arises, arises-or, arising, arithmetical, ark,
arkhangelsk, arm, armadas, armament, armaments, armas, armed, armenia, armenian, armenians, armies,
arming, armistice, armorial, armouries, armoury, arms, army, arno, arnprior, arochukwu, arorae,
arose, around, arouse, aroused, arouses, arrack, arraign, arraigned, arraigning, arraignment,
arraignments, arraigo, arran, arrange, arranged, arrangement, arrangements, arranges, arranging,
arrears, arrendamiento, arrest, arrested, arresting, arrests, arrete, arretes, arrival, arrive,
arrived, arrivee, arriving, arrogance, arrogate, arrondissement, arrondissements, arrow, arrt,
arrte, arsenals, art, artefacts, artemesia, arthur, article, articled, articles, articulate,
articulated, articulates, articulating, articulation, artifacts, artificial, artillery,
artillerymen, artisan, artisanal, artisans, artisanship, artist, artistic, artistic-cultural,
artists, arts, arua, arunachal, arusha, ary, as, asa, asaba, asad, asamblea, asari-toru, ascend,
ascendants, ascending, ascension, ascensos, ascent, ascertain, ascertainable, ascertained,
ascertaining, ascertainment, ascertains, ascribed, ascription, asentado, asesora, ashburnham,
ashdown, ashfield, ashgabat, ashkali, asia, asian, aside, asignaciones, asiliado, asilo, asimismo,
asina, asistencia, ask, asked, asking, asks, aspect, aspects, asphodel, aspirant, aspirants,
aspiration, aspirations, aspire, aspires, aspiring, aspp, assail, assailed, assam, assamese,
assassination, assault, assaulted, assed, assembiy, assemble, assemblea, assembled, assembles,
assemblies, assembling, assembly, assembly-or, assembly-parliament, assemnbly, assent, assented,
assenting, assents, assert, asserted, asserting, assertion, asserts, asservissement, assess,
assessed, assesses, assessing, assessment, assessments, assessor, assessors, asset, assets,
asseveration, assiduously, assiette, assign, assignation, assigned, assignee, assignees, assigning,
assignment, assignments, assigns, assimilate, assimilated, assimilating, assimilation, assimiles,
assist, assistance, assistance-related, assistances, assistant, assistants, assisted, assisting,
assists, associate, associated, associates, associating, association, associational, associations,
associative, assomption, assuagements, assume, assumed, assumes, assuming, assumption, assumptions,
assurance, assurances, assure, assured, assures, assuring, assyrian, assyrians, astove, astrakhan,
astrid, asturias, astutely, asueto, asuntos, asutan, asylee, asylum, asylum-seeker, asylums,
asymmetrical, asymmetries, asymmetry, at, at-home, at-law, at-will, atai, atakumosa, atas,
atendiendo, atheistic, athens, athletes, athletic, athletics, atholhu, athos, atiba, atigbo,
atlantic, atmosphere, atmospheric, atoli, atoll, atolls, atomic, atop, atractivo, atribuciones,
atribuicoes, atrocity, attach, attachable, attached, attaches, attaching, attachment, attachments,
attack, attacked, attacking, attacks, attain, attainable, attainder, attained, attaining,
attainment, attainments, attains, attainted, atteinte, attempt, attempted, attempting, attempts,
attend, attendance, attendant, attendants, attended, attendees, attending, attends, attentatoires,
attention, attentions, attentive, attentively, attenuate, attest, attestation, attestations,
attested, attests, attire, attired, attirer, attitude, attitudes, attorney, attorney-at-law,
attorney-general, attorneys, attorneys-at-law, attorneys-general, attorneyship, attract, attracting,

term_str               aa  aalim  aargau  ab  aba  ababa  abadam  abaiang  \
country_id  article_n
Afghanistan 1           0      0       0   0    0      0       0        0
            2           0      0       0   0    0      0       0        0
            3           0      0       0   0    0      0       0        0
            4           0      0       0   0    0      0       0        0
            5           0      0       0   0    0      0       0        0
            6           0      0       0   0    0      0       0        0
            7           0      0       0   0    0      0       0        0
            8           0      0       0   0    0      0       0        0
            9           0      0       0   0    0      0       0        0
            10          0      0       0   0    0      0       0        0

term_str               abaji  abak  abakaliki  abandon  abandoned  abandoning  \
country_id  article_n
Afghanistan 1              0     0          0        0          0           0
            2              0     0          0        0          0           0
            3              0     0          0        0          0           0
            4              0     0          0        0          0           0
            5              0     0          0        0          0           0
            6              0     0          0        0          0           0
            7              0     0          0        0          0           0
            8              0     0          0        0          0           0
            9              0     0          0        0          0           0
            10             0     0          0        0          0           0

term_str               abandonment  abandons  abariringa  abases  abasi  \
country_id  article_n
Afghanistan 1                    0         0           0       0      0
            2                    0         0           0       0      0
            3                    0         0           0       0      0
            4                    0         0           0       0      0
            5                    0         0           0       0      0
            6                    0         0           0       0      0
            7                    0         0           0       0      0
            8                    0         0           0       0      0
            9                    0         0           0       0      0
            10                   0         0           0       0      0

term_str               abasto  abate  abatement  abatements  abattoir  \
country_id  article_n
Afghanistan 1               0      0          0           0         0
            2               0      0          0           0         0
            3               0      0          0           0         0
            4               0      0          0           0         0
            5               0      0          0           0         0
            6               0      0          0           0         0
            7               0      0          0           0         0
            8               0      0          0           0         0
            9               0      0          0           0         0
            10              0      0          0           0         0

term_str               abattoirs  abbot  abbottabad  abbreviated  \
country_id  article_n
Afghanistan 1                  0      0           0            0
            2                  0      0           0            0
            3                  0      0           0            0
            4                  0      0           0            0
            5                  0      0           0            0
            6                  0      0           0            0
            7                  0      0           0            0
            8                  0      0           0            0
            9                  0      0           0            0
            10                 0      0           0            0

term_str               abbreviations  abd-allah  abdallah  abdel  abdicate  \
country_id  article_n
Afghanistan 1                      0          0         0      0         0
            2                      0          0         0      0         0
            3                      0          0         0      0         0
            4                      0          0         0      0         0
            5                      0          0         0      0         0
            6                      0          0         0      0         0
            7                      0          0         0      0         0
            8                      0          0         0      0         0
            9                      0          0         0      0         0
            10                     0          0         0      0         0

term_str               abdicated  abdicates  abdication  abdications  abduct  \
country_id  article_n
Afghanistan 1                  0          0           0            0       0
            2                  0          0           0            0       0
            3                  0          0           0            0       0
            4                  0          0           0            0       0
            5                  0          0           0            0       0
            6                  0          0           0            0       0
            7                  0          0           0            0       0
            8                  0          0           0            0       0
            9                  0          0           0            0       0
            10                 0          0           0            0       0

term_str               abduction  abdul  abdulai  abdulaziz  abdullah  \
country_id  article_n
Afghanistan 1                  0      0        0          0         0
            2                  0      0        0          0         0
            3                  0      0        0          0         0
            4                  0      0        0          0         0
            5                  0      0        0          0         0
            6                  0      0        0          0         0
            7                  0      0        0          0         0
            8                  0      0        0          0         0
            9                  0      0        0          0         0
            10                 0      0        0          0         0

term_str               abemama  abeokuta  abetment  abets  abetting  abeyance  \
country_id  article_n
Afghanistan 1                0         0         0      0         0         0
            2                0         0         0      0         0         0
            3                0         0         0      0         0         0
            4                0         0         0      0         0         0
            5                0         0         0      0         0         0
            6                0         0         0      0         0         0
            7                0         0         0      0         0         0
            8                0         0         0      0         0         0
            9                0         0         0      0         0         0
            10               0         0         0      0         0         0

term_str               abi  ...  zango-kataf  zanzibar  zaporizhia  \
country_id  article_n       ...
Afghanistan 1            0  ...            0         0           0
            2            0  ...            0         0           0
            3            0  ...            0         0           0
            4            0  ...            0         0           0
            5            0  ...            0         0           0
            6            0  ...            0         0           0
            7            0  ...            0         0           0
            8            0  ...            0         0           0
            9            0  ...            0         0           0
            10           0  ...            0         0           0

term_str               zaporozhian  zapotillos  zaria  zave  zayd  zb  \
country_id  article_n
Afghanistan 1                    0           0      0     0     0   0
            2                    0           0      0     0     0   0
            3                    0           0      0     0     0   0
            4                    0           0      0     0     0   0
            5                    0           0      0     0     0   0
            6                    0           0      0     0     0   0
            7                    0           0      0     0     0   0
            8                    0           0      0     0     0   0
            9                    0           0      0     0     0   0
            10                   0           0      0     0     0   0

term_str               zdravljica  zeal  zealand  zealously  zebu  zedong  \
country_id  article_n
Afghanistan 1                   0     0        0          0     0       0
            2                   0     0        0          0     0       0
            3                   0     0        0          0     0       0
            4                   0     0        0          0     0       0
            5                   0     0        0          0     0       0
            6                   0     0        0          0     0       0
            7                   0     0        0          0     0       0
            8                   0     0        0          0     0       0
            9                   0     0        0          0     0       0
            10                  0     0        0          0     0       0

term_str               zeledon  zemgale  zero  zetu  zf  zhabdrung  \
country_id  article_n
Afghanistan 1                0        0     0     0   0          0
            2                0        0     0     0   0          0
            3                0        0     0     0   0          0
            4                0        0     0     0   0          0
            5                0        0     0     0   0          0
            6                0        0     0     0   0          0
            7                0        0     0     0   0          0
            8                0        0     0     0   0          0
            9                0        0     0     0   0          0
            10               0        0     0     0   0          0

term_str               zhug-drel-phunsum  zhugdrel  zhung  zhungtshog  \
country_id  article_n
Afghanistan 1                          0         0      0           0
            2                          0         0      0           0
            3                          0         0      0           0
            4                          0         0      0           0
            5                          0         0      0           0
            6                          0         0      0           0
            7                          0         0      0           0
            8                          0         0      0           0
            9                          0         0      0           0
            10                         0         0      0           0

term_str               zhytomyr  zimbabwe  zimbabwean  zimbabweans  zing  \
country_id  article_n
Afghanistan 1                 0         0           0            0     0
            2                 0         0           0            0     0
            3                 0         0           0            0     0
            4                 0         0           0            0     0
            5                 0         0           0            0     0
            6                 0         0           0            0     0
            7                 0         0           0            0     0
            8                 0         0           0            0     0
            9                 0         0           0            0     0
            10                0         0           0            0     0

term_str               zionist  zjednocovan  zk  zo  zone  zoned  zones  \
country_id  article_n
Afghanistan 1                0            0   0   0     0      0      0
            2                0            0   0   0     0      0      0
            3                0            0   0   0     0      0      0
            4                0            0   0   0     0      0      0
            5                0            0   0   0     0      0      0
            6                0            0   0   0     0      0      0
            7                0            0   0   0     0      0      0
            8                0            0   0   0     0      0      0
            9                0            0   0   0     0      0      0
            10               0            0   0   0     0      0      0

term_str               zoning  zoological  zoro  zoroastrian  zoroastrians  \
country_id  article_n
Afghanistan 1               0           0     0            0             0
            2               0           0     0            0             0
            3               0           0     0            0             0
            4               0           0     0            0             0
            5               0           0     0            0             0
            6               0           0     0            0             0
            7               0           0     0            0             0
            8               0           0     0            0             0
            9               0           0     0            0             0
            10              0           0     0            0             0

term_str               zq  zuba  zug  zui  zulia  zurich  zurmi  zuru
country_id  article_n
Afghanistan 1           0     0    0    0      0       0      0     0
            2           0     0    0    0      0       0      0     0
            3           0     0    0    0      0       0      0     0
            4           0     0    0    0      0       0      0     0
            5           0     0    0    0      0       0      0     0
            6           0     0    0    0      0       0      0     0
            7           0     0    0    0      0       0      0     0
            8           0     0    0    0      0       0      0     0
            9           0     0    0    0      0       0      0     0
            10          0     0    0    0      0       0      0     0

[10 rows x 24735 columns]

## TFIDF

This section inspects the TFIDF-weighted document-term matrix built from the project corpus.

In [4]:
TFIDF = inspect_table(
    section='TFIDF',
    box_url='https://virginia.box.com/shared/static/eypbjdf47oiftzj9vdsz7cz5cas2vp81',
    local_path='tfidf.parquet',
    file_format='parquet'
)

Section: TFIDF
Box URL: https://virginia.box.com/shared/static/eypbjdf47oiftzj9vdsz7cz5cas2vp81
Local file: tfidf.parquet
Loaded from: Box download
Format: parquet
Shape: 33,726 rows x 24,735 columns
Number of observations: 33,726
Column names:
aa, aalim, aargau, ab, aba, ababa, abadam, abaiang, abaji, abak, abakaliki, abandon, abandoned,
abandoning, abandonment, abandons, abariringa, abases, abasi, abasto, abate, abatement, abatements,
abattoir, abattoirs, abbot, abbottabad, abbreviated, abbreviations, abd-allah, abdallah, abdel,
abdicate, abdicated, abdicates, abdication, abdications, abduct, abduction, abdul, abdulai,
abdulaziz, abdullah, abemama, abeokuta, abetment, abets, abetting, abeyance, abi, abia, abide,
abided, abides, abiding, abilities, ability, abim, abinger, abish, abjure, abkhazia, abkhazian,
able, able-bodied, abler, ablution, ably, abnegation, abnormal, abnormalities, abnormality,
abnormally, aboard, abode, aboh-mbaise, abolish, abolished, abolishes, abolishing, abolishment,
abolition, abonar, aboriginal, aborigine, aborigines, abortion, about, above, above-cited, above-
mentioned, above-referenced, above-specified, aboveground, abovementioned, abr, abreast, abridge,
abridged, abridgement, abridgements, abridges, abridging, abroad, abrogate, abrogated, abrogates,
abrogating, abrogation, abrogatory, abruzzi, abs, abscissa, absconding, absence, absences, absent,
absent-ones, absented, absentee, absentees, absentia, absenting, absents, absoluta, absolute,
absolutely, absolutory, absolve, absolved, absolving, absorb, absorbed, absorption, abstain,
abstained, abstaining, abstains, abstention, abstentions, abstract, abstraction, abu, abuja,
abundance, abundant, abuse, abuse-of-rights, abused, abuses, abusing, abusive, abyei, ac, academia,
academic, academical, academically, academicians, academics, academies, academy, accede, acceded,
accedes, acceding, accelerate, accelerated, accelerates, accelerating, accept, acceptable,
acceptance, accepted, accepting, accepts, accesiones, access, accessed, accessibility, accessible,
accessing, accession, accessories, accessory, accident, accidents, accion, acclaiming, acclamation,
acclamations, accommodate, accommodates, accommodating, accommodation, accommodations, accompanied,
accompany, accompanying, accomplice, accomplices, accomplish, accomplished, accomplishes,
accomplishing, accomplishment, accomplishments, accord, accordance, accorded, accorder, according,
accordingly, accords, accosted, account, accountability, accountable, accountably, accountancy,
accountant, accountant-general, accountants, accounted, accounting, accounts, accredit,
accreditation, accredited, accrediting, accredits, accreditted, accrete, accretion, accretions,
accrual, accruals, accrue, accrued, accrues, accruing, accumulate, accumulated, accumulation,
accuracy, accurate, accurately, accursed, accusation, accusations, accusatorial, accusatory, accuse,
accused, accuser, accusers, accusing, acervo, ach, achieve, achieved, achievement, achievements,
achieves, achieving, achodo, acholi, achwa, acids, acing, acknowledge, acknowledged,
acknowledgement, acknowledgements, acknowledges, acknowledging, acknowledgment, aconsejables,
aconseje, acoustical, acquaculture, acquaint, acquaintance, acquainted, acquainting, acquaints,
acquiesce, acquiescence, acquirable, acquire, acquired, acquirement, acquires, acquiring, acquis,
acquisition, acquisitions, acquisitive, acquit, acquittal, acquitted, acquitting, acre, acreages,
acronyms, across, act, act-the, act-to, acted, actifs, acting, actio, action, actionable, actions,
actions-incitement, activate, activated, activating, activation, active, actively, actives,
activism, activists, activite, activities, activity, acto, acton, actor, actors, acts, actuaciones,
actuado, actual, actualite, actualization, actually, actuarial, actuary, acu, acuerden, acute, ad,
ad-hoc, adam, adamaoua, adamawa, adami, adapt, adaptability, adaptation, adaptations, adapted,
adapting, adaptions, adapts, adat, adavi, add, added, addenda, addendum, addict, addicted,
addiction, addictions, addicts, adding, addington, addis, addition, additional, additionally,
additions, address, address-on, addressed, addressee, addresses, addressing, adds, addu, adduce,
adduced, adelaide, aden, adequacy, adequate, adequately, adh, adhere, adhered, adherence,
adherences, adherents, adherer, adheres, adhering, adhesion, adhi, adhiniyam, adi, adibasi, adige,
adil, adilnya, adjacent, adjala, adjika, adjoining, adjourn, adjourned, adjourning, adjournment,
adjournments, adjourns, adjucators, adjudge, adjudged, adjudicate, adjudicated, adjudicates,
adjudicating, adjudication, adjudications, adjudicative, adjudicator, adjudicators, adjudicatory,
adjumani, adjunct, adjunction, adjuncts, adjust, adjustable, adjusted, adjusting, adjustment,
adjustments, adjusts, admaston, administer, administered, administering, administers,
administradores, administrate, administrated, administrates, administrating, administration,
administrations, administrative, administrative-economic, administrative-procedural, administrative-
territorial, administratively, administratively-territorial, administrator, administrator-general,
administrators, administrators-general, admiral, admirals, admiralty, admiration, admiring,
admissibility, admissible, admission, admissions, admit, admits, admittance, admitted, admitting,
admonish, admonishing, admonition, ado, adolescence, adolescent, adolescents, adolphustown, adopt,
adopted, adoptee, adopter, adopting, adoption, adoptions, adoptive, adopts, adorned, adriatic, ads,
adult, adulterate, adulteration, adulthood, adults, advance, advanced, advancement, advancements,
advances, advancing, advantage, advantaged, advantageous, advantages, advent, adventure,
adventurers, adversarial, adversaries, adversary, adverse, adversely, adversity, advertised,
advertisement, advertisements, advertisers, advertising, advice, advices, advisability, advisable,
advise, advised, adviser, advisers, advises, advising, advisor, advisors, advisory, advocacy,
advocacy-general, advocacy-generals, advocate, advocate-general, advocated, advocates, advocating,
adygeya, aegis, aerated, aerial, aerodrome, aerodromes, aeronautic, aeronautical, aeronautics,
aerospace, aesthetic, af, afar, afectar, affair, affaire, affaires, affairs, affect, affected,
affectees, affecting, affection, affective, affects, afferents, affidavit, affidavits, affiliate,
affiliated, affiliates, affiliating, affiliation, affiliations, affinities, affinity, affirm,
affirmation, affirmations, affirmative, affirmed, affirming, affirms, affix, affixed, afflicted,
afflictive, affluent, affluents, afford, affordable, afforded, affording, affords, afforestation,
affronts, afghan, afghanistan, afijio, afikpo, afore-mentioned, aforementioned, aforesaid,
aforetime, afresh, africa, africains, african, africans, afrika, afrikaans, afro-arab, afro-
bolivian, afro-brazilian, afro-ecuadorian, afro-ecuadorians, after, aftermath, afterward,
afterwards, afurika, ag, agaie, again, against, agalega, agama, agatu, agave, age, age-limit, age-
old, aged, agege, agencies, agency, agenda, agendas, agent, agentes, agents, ages, agglomeration,
agglomerations, aggravate, aggravating, aggravation, aggregate, aggregated, aggregates, aggregating,
aggregation, aggression, aggressions, aggressive, aggressors, aggrieved, aghia, aghion, aginsk,
agitate, agitation, ago, agong, agonising, agoyan, agraria, agrarian, agree, agreed, agreeing,
agreement, agreements, agrees, agregado, agri-food, agricultura, agricultural, agricultural-
livestock, agriculture, agro-allied, agro-environmental, agro-industrial, agro-industry, agro-
linked, agroambiental, agrochemical, agrochemicals, agroindustrial, agrological, agropecuaria,
agrupaciones, agruparse, agu, aguascalientes, aguata, aguinaldo, agwara, ah, ahead, ahiazu-mbaise,
ahinza, ahkam, ahmadis, ahmed, aho, ahoada, ahy, ai-maghrib, aid, aide, aide-de-camp, aided, aides,
aiding, aids, aigrettes, ail, ailinginae, ailinglaplap, ailments, ailuk, aim, aimed, aimeliik,
aiming, aims, ain, aina, aioda, air, air-force, airai, aircraft, aircrafts, aires, airfields,
airforce, airok, airport, airports, airships, airspace, airstrips, airtime, airwaves, airways,
aishwarya, aisladamente, aiyedade, aiyedire, aiyekire, aja-raja, ajaokuta, ajara, ajc, ajeromi-
ifelodun, ajigu, ajingi, ajm-bill, ajm-constitution, ajm-corrupt, ajm-criminal, ajm-debt, ajm-
disciplinary, ajm-disciplined, ajm-electoral, ajm-eligible, ajm-forced, ajm-hate, ajm-human, ajm-
includes, ajm-judicial, ajm-land, ajm-oath, ajm-pension, ajm-political, ajm-public, ajm-republic,
ajm-sentence, ajm-state, ajm-subordinate, ajm-this, ajm-written, ajman, ajq, ajustarse, ajuste,
ajyalg, akamkpa, akan, akar, akara, akasiru, akbar, akim, akims, akin, akinyele, akiykatchy, akko,
akoko, akoko-edo, akpabuyo, akrishik, aksakal, aksakaly, akuku, akure, akwa, akwanga, al, al-ad-ha,
al-amr, al-anfal, al-assi, al-awwal, al-azhar, al-bikaa, al-douha, al-dujail, al-faqih, al-fitr, al-
fuqaha, al-hima, al-hudud, al-hussein, al-imran, al-kabir, al-kamar, al-majlis, al-munkar, al-nahr,
al-nahy, al-nuwwab, al-saud, al-shoura, al-shura, al-taqlid, al-watani, alala, alam, alania, alap,
alarm, alava, albania, albanian, albanians, albasu, albeit, albermarle, albert, alberta, albion,
albums, alcalde, alcaldes, alcances, alcanzan, alcanzaren, alcock, alcohol, alcoholic, alcoholics,
alcoholism, aldabra, alderman, aldermen, alegre, aleiro, alert, alerte, alexander, alexandria,
alexandrine, alfaro, alfaro-peace, alfonso, algemene, algeria, algerian, algerians, algiers, algoma,
algona, ali, alia, aliba, alice, alien, alienable, alienate, alienated, alienation, alienations,
aliens, aligarh, alight, align, aligned, aligning, alignment, alike, alimentaria, alimenticias,
alimenticios, alimony, alimosho, aliquot, alive, alkaleri, alkalo, all, all-around, all-india, all-
nation, all-pakistan, all-people, all-powerful, all-round, all-ukrainian, allah, allahu, allanados,
allanando, allanar, allegados, allegation, allegations, allege, alleged, allegedly, alleger,
alleges, allegiance, allegience, alleging, aller, alleviate, alleviated, alleviating, alleviation,
alliance, alliances, allied, allies, allocate, allocated, allocates, allocating, allocation,
allocations, allodial, allot, allotment, allotments, allotted, allottees, allow, allowance,
allowances, allowed, allowing, allows, alloys, alluded, allusion, almarhum, almighty, almost, aloft,
alone, along, alongside, aloud, alphabet, alphabetical, alphonse, alpine, already, als, also, also-
in, alta, altai, altaqlid, alter, alteration, alterations, altered, altering, alternabilidad,
alternate, alternated, alternately, alternates, alternating, alternation, alternations, alternative,
alternatively, alternatives, alters, althingi, although, alto, altogether, aludidos, alumni, alupe,
alur, always, alzado, am, ama, amable, amacuro, amalgamated, amalgamation, aman, amani, amap, amar,
amaranth, amass, amateur, amazigh, amazighe, amazighit, amazing, amazon, amazonas, amazonia,
amazonian, amb, ambassador, ambassadorial, ambassadors, ambeno, ambergris, ambiguities, ambiguity,
ambiguous, ambit, ambition, ambitions, ambito, ambits, ambulance, ambushes, amdendment, amdt, ameen,
ameliorate, amelioration, amenable, amenagement, amend, amendable, amendatory, amended, amending,
amendment, amendments, amends, amenities, america, american, americans, amerindian, amerindians,
amhara, amharic, amherst, amicable, amicably, amidst, amilcar, amim, aminzi, amir, amirantes,
amirate, amiri, amity, amkeni, amman, ammodar, ammunition, ammunitions, amnesties, amnesty, amoda,
amolatar, among, amongst, amortisation, amortization, amortizations, amount, amounted, amounting,
amounts, ampara, amparado, amparar, amparo, ample, ampliado, ampliar, amplification, amplified,
amplio, amply, amsterdam, amur, amuria, amuru, amusement, amusements, amuwo-odofin, amyotha, an, an-
organizations, anakandriamaso, analagous, analfabetismo, analogies, analogous, analogously, analogy,
analphabetism, analyse, analysed, analyses, analysing, analysis, analytic, analytical, analyze,
analyzed, anam, anambra, anaocha, anastasia, anatocism, anc, ancap, ancash, ancestor, ancestors,
ancestral, ancestrally, ancestry, anchor, anchored, ancient, ancillary, and, andalusian, andaman,
andean, andereko, andhra, andloyalty, andolan, andoni, andorra, andorran, andorrans, andraikitra,
andres, andreserve, andriamanitra, andriananahary, ands, andto, anew, anfal, ang, angaur, anger,
angket, angkor, angle, angled, angles, anglesea, anglo-french, anglo-indian, anglo-liberian,
anglong, angola, angolan, angolans, anguilla, anibare, animal, animals, animated, animates,
animating, animation, animism, animosity, aninri, aniocha, anjouan, anka, ankanavaka, ankara,
ankole, ankpa, annals, anne, annex, annexed, annexes, annexing, annexure, anniversaries,
anniversary, anno, annotate, annotation, announce, announced, announcement, announcements,
announces, announcing, annual, annually, annuities, annuity, annul, annulled, annulling, annulment,
annuls, annum, anointed, anomaly, anonyme, anonymity, another, anson, answer, answerability,
answerable, answered, answering, answers, ant, antananarivo, antarctic, antecedent, antecedentes,
antecedents, antecendentes, antedated, antejuicio, antejuicios, anterior, anthem, anthem-sanctioned,
anthropological, anti, anti-colonial, anti-colonialist, anti-competitive, anti-constitutional, anti-
corruption, anti-despotic, anti-discrimination, anti-fascist, anti-graft, anti-imperialist, anti-
interventionist, anti-islamic, anti-japanese, anti-juridical, anti-national, anti-piracy, anti-
smuggling, anti-terrorism, anti-trust, anticipate, anticipated, anticipating, anticipation,
anticipatory, anticolonialist, anticorruption, antidemocratic, antifascist, antigua, antilles,
antimonopoly, antiocheia, antiques, antiquities, antisocial, antonio, antwerp, anuradhapura,
anxiety, anxious, any, anybody, anyone, anyplace, anything, anytime, anywhere, anzoategui, ao,
aoruma, apa, apac, apapa, aparceros, apart, apartheid, apartment, apartments, apatrids, apex,
apexes, apolima, apolitical, apology, aportantes, apostle, apostles, apostolic, appanage, apparatus,
apparent, apparently, appartenance, appeal, appealable, appealed, appealing, appeals, appear,
appearance, appearances, appeared, appearing, appears, appellant, appellants, appellate,
appellation, appellations, append, appended, appendices, appending, appendix, appends, appenzell,
appertain, appertaining, appertains, applause, apples, appliances, applicability, applicable,
applicant, applicants, application, applications, applied, applies, appliquer, apply, applying,
appoint, appoint-appointed, appointed, appointee, appointees, appointer, appointers, appointing,
appointive, appointment, appointments, appoints, apport, apporte, apporter, apportion, apportioned,
apportioning, apportionment, apportions, appraisal, appraisals, appraise, appraised, appraises,
appraising, appreciated, appreciating, appreciation, apprecie, apprehend, apprehended, apprehending,
apprehension, apprentice, apprenticeship, apprised, apprized, approach, approached, approaches,
approaching, approbation, approbations, approbatory, appropriate, appropriated, appropriately,
appropriateness, appropriates, appropriating, appropriation, appropriations, approval, approvals,
approve, approved, approves, approving, approvisionment, approximate, approximately, approximation,
appurtenances, appurtenant, april, aprovechamiento, apt, aptitude, aptitudes, apulia, apure,
aquaculture, aquatic, aquiculture, arab, arab-islamist, arab-muslim, arab-ness, arabia, arabian,
arabic, arabism, arable, arabs, araguaia, aranuka, araona, ararat, arauca, arbiter, arbiters,
arbitraje, arbitral, arbitrament, arbitrarily, arbitrariness, arbitrary, arbitrate, arbitrated,
arbitrates, arbitration, arbitration-procedural, arbitrations, arbitrator, arbitrators, arbitrios,
arboreum, arc, archaeological, archduke, archeological, archipelagic, archipelago, archipelagos,
architectural, architecture, archival, archivar, archive, archived, archives, archyn, arcs, ardent,
ardo-kola, arduous, arduousness, are, area, area-based, areas, arena, arenas, arequipa, arewa-dandi,
argent, argenteuil, argentine, argentines, arguable, argue, argued, argument, arguments, argungu,
ari, arid, aride, aright, aringa, arise, arisen, arises, arises-or, arising, arithmetical, ark,
arkhangelsk, arm, armadas, armament, armaments, armas, armed, armenia, armenian, armenians, armies,
arming, armistice, armorial, armouries, armoury, arms, army, arno, arnprior, arochukwu, arorae,
arose, around, arouse, aroused, arouses, arrack, arraign, arraigned, arraigning, arraignment,
arraignments, arraigo, arran, arrange, arranged, arrangement, arrangements, arranges, arranging,
arrears, arrendamiento, arrest, arrested, arresting, arrests, arrete, arretes, arrival, arrive,
arrived, arrivee, arriving, arrogance, arrogate, arrondissement, arrondissements, arrow, arrt,
arrte, arsenals, art, artefacts, artemesia, arthur, article, articled, articles, articulate,
articulated, articulates, articulating, articulation, artifacts, artificial, artillery,
artillerymen, artisan, artisanal, artisans, artisanship, artist, artistic, artistic-cultural,
artists, arts, arua, arunachal, arusha, ary, as, asa, asaba, asad, asamblea, asari-toru, ascend,
ascendants, ascending, ascension, ascensos, ascent, ascertain, ascertainable, ascertained,
ascertaining, ascertainment, ascertains, ascribed, ascription, asentado, asesora, ashburnham,
ashdown, ashfield, ashgabat, ashkali, asia, asian, aside, asignaciones, asiliado, asilo, asimismo,
asina, asistencia, ask, asked, asking, asks, aspect, aspects, asphodel, aspirant, aspirants,
aspiration, aspirations, aspire, aspires, aspiring, aspp, assail, assailed, assam, assamese,
assassination, assault, assaulted, assed, assembiy, assemble, assemblea, assembled, assembles,
assemblies, assembling, assembly, assembly-or, assembly-parliament, assemnbly, assent, assented,
assenting, assents, assert, asserted, asserting, assertion, asserts, asservissement, assess,
assessed, assesses, assessing, assessment, assessments, assessor, assessors, asset, assets,
asseveration, assiduously, assiette, assign, assignation, assigned, assignee, assignees, assigning,
assignment, assignments, assigns, assimilate, assimilated, assimilating, assimilation, assimiles,
assist, assistance, assistance-related, assistances, assistant, assistants, assisted, assisting,
assists, associate, associated, associates, associating, association, associational, associations,
associative, assomption, assuagements, assume, assumed, assumes, assuming, assumption, assumptions,
assurance, assurances, assure, assured, assures, assuring, assyrian, assyrians, astove, astrakhan,
astrid, asturias, astutely, asueto, asuntos, asutan, asylee, asylum, asylum-seeker, asylums,
asymmetrical, asymmetries, asymmetry, at, at-home, at-law, at-will, atai, atakumosa, atas,
atendiendo, atheistic, athens, athletes, athletic, athletics, atholhu, athos, atiba, atigbo,
atlantic, atmosphere, atmospheric, atoli, atoll, atolls, atomic, atop, atractivo, atribuciones,
atribuicoes, atrocity, attach, attachable, attached, attaches, attaching, attachment, attachments,
attack, attacked, attacking, attacks, attain, attainable, attainder, attained, attaining,
attainment, attainments, attains, attainted, atteinte, attempt, attempted, attempting, attempts,
attend, attendance, attendant, attendants, attended, attendees, attending, attends, attentatoires,
attention, attentions, attentive, attentively, attenuate, attest, attestation, attestations,
attested, attests, attire, attired, attirer, attitude, attitudes, attorney, attorney-at-law,
attorney-general, attorneys, attorneys-at-law, attorneys-general, attorneyship, attract, attracting,

term_str                aa  aalim  aargau   ab  aba  ababa  abadam  abaiang  \
country_id  article_n
Afghanistan 1          0.0    0.0     0.0  0.0  0.0    0.0     0.0      0.0
            2          0.0    0.0     0.0  0.0  0.0    0.0     0.0      0.0
            3          0.0    0.0     0.0  0.0  0.0    0.0     0.0      0.0
            4          0.0    0.0     0.0  0.0  0.0    0.0     0.0      0.0
            5          0.0    0.0     0.0  0.0  0.0    0.0     0.0      0.0
            6          0.0    0.0     0.0  0.0  0.0    0.0     0.0      0.0
            7          0.0    0.0     0.0  0.0  0.0    0.0     0.0      0.0
            8          0.0    0.0     0.0  0.0  0.0    0.0     0.0      0.0
            9          0.0    0.0     0.0  0.0  0.0    0.0     0.0      0.0
            10         0.0    0.0     0.0  0.0  0.0    0.0     0.0      0.0

term_str               abaji  abak  abakaliki  abandon  abandoned  abandoning  \
country_id  article_n
Afghanistan 1            0.0   0.0        0.0      0.0        0.0         0.0
            2            0.0   0.0        0.0      0.0        0.0         0.0
            3            0.0   0.0        0.0      0.0        0.0         0.0
            4            0.0   0.0        0.0      0.0        0.0         0.0
            5            0.0   0.0        0.0      0.0        0.0         0.0
            6            0.0   0.0        0.0      0.0        0.0         0.0
            7            0.0   0.0        0.0      0.0        0.0         0.0
            8            0.0   0.0        0.0      0.0        0.0         0.0
            9            0.0   0.0        0.0      0.0        0.0         0.0
            10           0.0   0.0        0.0      0.0        0.0         0.0

term_str               abandonment  abandons  abariringa  abases  abasi  \
country_id  article_n
Afghanistan 1                  0.0       0.0         0.0     0.0    0.0
            2                  0.0       0.0         0.0     0.0    0.0
            3                  0.0       0.0         0.0     0.0    0.0
            4                  0.0       0.0         0.0     0.0    0.0
            5                  0.0       0.0         0.0     0.0    0.0
            6                  0.0       0.0         0.0     0.0    0.0
            7                  0.0       0.0         0.0     0.0    0.0
            8                  0.0       0.0         0.0     0.0    0.0
            9                  0.0       0.0         0.0     0.0    0.0
            10                 0.0       0.0         0.0     0.0    0.0

term_str               abasto  abate  abatement  abatements  abattoir  \
country_id  article_n
Afghanistan 1             0.0    0.0        0.0         0.0       0.0
            2             0.0    0.0        0.0         0.0       0.0
            3             0.0    0.0        0.0         0.0       0.0
            4             0.0    0.0        0.0         0.0       0.0
            5             0.0    0.0        0.0         0.0       0.0
            6             0.0    0.0        0.0         0.0       0.0
            7             0.0    0.0        0.0         0.0       0.0
            8             0.0    0.0        0.0         0.0       0.0
            9             0.0    0.0        0.0         0.0       0.0
            10            0.0    0.0        0.0         0.0       0.0

term_str               abattoirs  abbot  abbottabad  abbreviated  \
country_id  article_n
Afghanistan 1                0.0    0.0         0.0          0.0
            2                0.0    0.0         0.0          0.0
            3                0.0    0.0         0.0          0.0
            4                0.0    0.0         0.0          0.0
            5                0.0    0.0         0.0          0.0
            6                0.0    0.0         0.0          0.0
            7                0.0    0.0         0.0          0.0
            8                0.0    0.0         0.0          0.0
            9                0.0    0.0         0.0          0.0
            10               0.0    0.0         0.0          0.0

term_str               abbreviations  abd-allah  abdallah  abdel  abdicate  \
country_id  article_n
Afghanistan 1                    0.0        0.0       0.0    0.0       0.0
            2                    0.0        0.0       0.0    0.0       0.0
            3                    0.0        0.0       0.0    0.0       0.0
            4                    0.0        0.0       0.0    0.0       0.0
            5                    0.0        0.0       0.0    0.0       0.0
            6                    0.0        0.0       0.0    0.0       0.0
            7                    0.0        0.0       0.0    0.0       0.0
            8                    0.0        0.0       0.0    0.0       0.0
            9                    0.0        0.0       0.0    0.0       0.0
            10                   0.0        0.0       0.0    0.0       0.0

term_str               abdicated  abdicates  abdication  abdications  abduct  \
country_id  article_n
Afghanistan 1                0.0        0.0         0.0          0.0     0.0
            2                0.0        0.0         0.0          0.0     0.0
            3                0.0        0.0         0.0          0.0     0.0
            4                0.0        0.0         0.0          0.0     0.0
            5                0.0        0.0         0.0          0.0     0.0
            6                0.0        0.0         0.0          0.0     0.0
            7                0.0        0.0         0.0          0.0     0.0
            8                0.0        0.0         0.0          0.0     0.0
            9                0.0        0.0         0.0          0.0     0.0
            10               0.0        0.0         0.0          0.0     0.0

term_str               abduction  abdul  abdulai  abdulaziz  abdullah  \
country_id  article_n
Afghanistan 1                0.0    0.0      0.0        0.0       0.0
            2                0.0    0.0      0.0        0.0       0.0
            3                0.0    0.0      0.0        0.0       0.0
            4                0.0    0.0      0.0        0.0       0.0
            5                0.0    0.0      0.0        0.0       0.0
            6                0.0    0.0      0.0        0.0       0.0
            7                0.0    0.0      0.0        0.0       0.0
            8                0.0    0.0      0.0        0.0       0.0
            9                0.0    0.0      0.0        0.0       0.0
            10               0.0    0.0      0.0        0.0       0.0

term_str               abemama  abeokuta  abetment  abets  abetting  abeyance  \
country_id  article_n
Afghanistan 1              0.0       0.0       0.0    0.0       0.0       0.0
            2              0.0       0.0       0.0    0.0       0.0       0.0
            3              0.0       0.0       0.0    0.0       0.0       0.0
            4              0.0       0.0       0.0    0.0       0.0       0.0
            5              0.0       0.0       0.0    0.0       0.0       0.0
            6              0.0       0.0       0.0    0.0       0.0       0.0
            7              0.0       0.0       0.0    0.0       0.0       0.0
            8              0.0       0.0       0.0    0.0       0.0       0.0
            9              0.0       0.0       0.0    0.0       0.0       0.0
            10             0.0       0.0       0.0    0.0       0.0       0.0

term_str               abi  ...  zango-kataf  zanzibar  zaporizhia  \
country_id  article_n       ...
Afghanistan 1          0.0  ...          0.0       0.0         0.0
            2          0.0  ...          0.0       0.0         0.0
            3          0.0  ...          0.0       0.0         0.0
            4          0.0  ...          0.0       0.0         0.0
            5          0.0  ...          0.0       0.0         0.0
            6          0.0  ...          0.0       0.0         0.0
            7          0.0  ...          0.0       0.0         0.0
            8          0.0  ...          0.0       0.0         0.0
            9          0.0  ...          0.0       0.0         0.0
            10         0.0  ...          0.0       0.0         0.0

term_str               zaporozhian  zapotillos  zaria  zave  zayd   zb  \
country_id  article_n
Afghanistan 1                  0.0         0.0    0.0   0.0   0.0  0.0
            2                  0.0         0.0    0.0   0.0   0.0  0.0
            3                  0.0         0.0    0.0   0.0   0.0  0.0
            4                  0.0         0.0    0.0   0.0   0.0  0.0
            5                  0.0         0.0    0.0   0.0   0.0  0.0
            6                  0.0         0.0    0.0   0.0   0.0  0.0
            7                  0.0         0.0    0.0   0.0   0.0  0.0
            8                  0.0         0.0    0.0   0.0   0.0  0.0
            9                  0.0         0.0    0.0   0.0   0.0  0.0
            10                 0.0         0.0    0.0   0.0   0.0  0.0

term_str               zdravljica  zeal  zealand  zealously  zebu  zedong  \
country_id  article_n
Afghanistan 1                 0.0   0.0      0.0        0.0   0.0     0.0
            2                 0.0   0.0      0.0        0.0   0.0     0.0
            3                 0.0   0.0      0.0        0.0   0.0     0.0
            4                 0.0   0.0      0.0        0.0   0.0     0.0
            5                 0.0   0.0      0.0        0.0   0.0     0.0
            6                 0.0   0.0      0.0        0.0   0.0     0.0
            7                 0.0   0.0      0.0        0.0   0.0     0.0
            8                 0.0   0.0      0.0        0.0   0.0     0.0
            9                 0.0   0.0      0.0        0.0   0.0     0.0
            10                0.0   0.0      0.0        0.0   0.0     0.0

term_str               zeledon  zemgale  zero  zetu   zf  zhabdrung  \
country_id  article_n
Afghanistan 1              0.0      0.0   0.0   0.0  0.0        0.0
            2              0.0      0.0   0.0   0.0  0.0        0.0
            3              0.0      0.0   0.0   0.0  0.0        0.0
            4              0.0      0.0   0.0   0.0  0.0        0.0
            5              0.0      0.0   0.0   0.0  0.0        0.0
            6              0.0      0.0   0.0   0.0  0.0        0.0
            7              0.0      0.0   0.0   0.0  0.0        0.0
            8              0.0      0.0   0.0   0.0  0.0        0.0
            9              0.0      0.0   0.0   0.0  0.0        0.0
            10             0.0      0.0   0.0   0.0  0.0        0.0

term_str               zhug-drel-phunsum  zhugdrel  zhung  zhungtshog  \
country_id  article_n
Afghanistan 1                        0.0       0.0    0.0         0.0
            2                        0.0       0.0    0.0         0.0
            3                        0.0       0.0    0.0         0.0
            4                        0.0       0.0    0.0         0.0
            5                        0.0       0.0    0.0         0.0
            6                        0.0       0.0    0.0         0.0
            7                        0.0       0.0    0.0         0.0
            8                        0.0       0.0    0.0         0.0
            9                        0.0       0.0    0.0         0.0
            10                       0.0       0.0    0.0         0.0

term_str               zhytomyr  zimbabwe  zimbabwean  zimbabweans  zing  \
country_id  article_n
Afghanistan 1               0.0       0.0         0.0          0.0   0.0
            2               0.0       0.0         0.0          0.0   0.0
            3               0.0       0.0         0.0          0.0   0.0
            4               0.0       0.0         0.0          0.0   0.0
            5               0.0       0.0         0.0          0.0   0.0
            6               0.0       0.0         0.0          0.0   0.0
            7               0.0       0.0         0.0          0.0   0.0
            8               0.0       0.0         0.0          0.0   0.0
            9               0.0       0.0         0.0          0.0   0.0
            10              0.0       0.0         0.0          0.0   0.0

term_str               zionist  zjednocovan   zk   zo  zone  zoned  zones  \
country_id  article_n
Afghanistan 1              0.0          0.0  0.0  0.0   0.0    0.0    0.0
            2              0.0          0.0  0.0  0.0   0.0    0.0    0.0
            3              0.0          0.0  0.0  0.0   0.0    0.0    0.0
            4              0.0          0.0  0.0  0.0   0.0    0.0    0.0
            5              0.0          0.0  0.0  0.0   0.0    0.0    0.0
            6              0.0          0.0  0.0  0.0   0.0    0.0    0.0
            7              0.0          0.0  0.0  0.0   0.0    0.0    0.0
            8              0.0          0.0  0.0  0.0   0.0    0.0    0.0
            9              0.0          0.0  0.0  0.0   0.0    0.0    0.0
            10             0.0          0.0  0.0  0.0   0.0    0.0    0.0

term_str               zoning  zoological  zoro  zoroastrian  zoroastrians  \
country_id  article_n
Afghanistan 1             0.0         0.0   0.0          0.0           0.0
            2             0.0         0.0   0.0          0.0           0.0
            3             0.0         0.0   0.0          0.0           0.0
            4             0.0         0.0   0.0          0.0           0.0
            5             0.0         0.0   0.0          0.0           0.0
            6             0.0         0.0   0.0          0.0           0.0
            7             0.0         0.0   0.0          0.0           0.0
            8             0.0         0.0   0.0          0.0           0.0
            9             0.0         0.0   0.0          0.0           0.0
            10            0.0         0.0   0.0          0.0           0.0

term_str                zq  zuba  zug  zui  zulia  zurich  zurmi  zuru
country_id  article_n
Afghanistan 1          0.0   0.0  0.0  0.0    0.0     0.0    0.0   0.0
            2          0.0   0.0  0.0  0.0    0.0     0.0    0.0   0.0
            3          0.0   0.0  0.0  0.0    0.0     0.0    0.0   0.0
            4          0.0   0.0  0.0  0.0    0.0     0.0    0.0   0.0
            5          0.0   0.0  0.0  0.0    0.0     0.0    0.0   0.0
            6          0.0   0.0  0.0  0.0    0.0     0.0    0.0   0.0
            7          0.0   0.0  0.0  0.0    0.0     0.0    0.0   0.0
            8          0.0   0.0  0.0  0.0    0.0     0.0    0.0   0.0
            9          0.0   0.0  0.0  0.0    0.0     0.0    0.0   0.0
            10         0.0   0.0  0.0  0.0    0.0     0.0    0.0   0.0

[10 rows x 24735 columns]

## TFIDF_REDUCED_L2

This section inspects the reduced and L2-normalized TFIDF table used for downstream modeling.

In [5]:
TFIDF_REDUCED_L2 = inspect_table(
    section='TFIDF_REDUCED_L2',
    box_url='https://virginia.box.com/shared/static/0c2vu4l7moiq1jjxdcy1v3aeoyiu0uur',
    local_path='tfidf_reduced_l2.parquet',
    file_format='parquet'
)

Section: TFIDF_REDUCED_L2
Box URL: https://virginia.box.com/shared/static/0c2vu4l7moiq1jjxdcy1v3aeoyiu0uur
Local file: tfidf_reduced_l2.parquet
Loaded from: Box download
Format: parquet
Shape: 33,726 rows x 3,006 columns
Number of observations: 33,726
Column names:
abide, ability, able, abolish, abolished, abolition, about, above, abroad, abrogated, absence,
absent, absolute, abuse, academic, accept, acceptance, accepted, accepts, access, accessible,
accompanied, accord, accorded, according, accordingly, account, accountability, accountable,
accounting, accounts, accredited, accusation, accused, achieve, achieving, acquire, acquired,
acquisition, acquitted, acted, acting, action, actions, active, activities, activity, acts, actual,
ad, adaptations, added, addition, additional, address, addressed, adequate, adherence, adjourn,
adjournment, adjudged, adjudicate, administer, administered, administering, administration,
administrations, administrative, administrator, admissible, admission, admitted, adopt, adopted,
adopting, adoption, adopts, adult, advance, advanced, advancement, advice, advise, adviser, advises,
advisory, advocate, affairs, affect, affected, affecting, affection, affects, affiliation, affirm,
affirmation, affirmative, afforded, aforementioned, aforesaid, african, again, against, age,
agencies, agency, agenda, agent, agents, aggregate, aggression, aggrieved, agong, agree, agreed,
agreement, agreements, agricultural, agriculture, aid, aim, aimed, aims, air, aliens, alleged,
allegiance, allocated, allocation, allow, allowance, allowances, allowed, almighty, alone, along,
already, also, alter, alteration, altered, altering, alternate, alternative, always, ambassadors,
amend, amended, amending, amendment, amendments, amnesty, among, amongst, amount, amounts, animals,
announced, announcement, annual, annually, annul, another, answer, answerable, anthem, antigua,
anyone, anything, apart, appeal, appealed, appeals, appear, appears, appellate, applicable,
application, applications, applied, applies, apply, applying, appoint, appointing, appointment,
appointments, appoints, appropriate, appropriated, appropriation, appropriations, approval, approve,
approved, approves, approving, april, arab, arbitration, area, areas, arise, arisen, arises,
arising, armed, arms, army, arrangements, arrest, arrested, art, artistic, arts, aside, ask,
aspects, aspirations, assemble, assemblies, assent, assented, assessment, assets, assign, assigned,
assignment, assist, assistance, assistant, assisted, associate, associated, association,
associations, assume, assumed, assumes, assuming, assumption, assure, assured, assures, assuring,
asylum, attached, attained, attaining, attains, attend, attendance, attending, attention, attorney,
attorney-general, attorneys, attributed, attributions, audit, audited, auditor, auditor-general,
august, authorisation, authorise, authorised, authorises, authorising, authorities, authorization,
authorize, authorized, automatically, autonomous, autonomy, available, avoid, award, awards,
azerbaijan, back, bahamas, balance, balanced, ballot, bangladesh, bank, banking, bankrupt, banks,
bar, barbuda, base, based, bases, basic, basis, bear, bearing, became, because, become, becomes,
becoming, begin, beginning, begins, behalf, being, beings, belarus, belief, beliefs, belize, belong,
belonging, belongs, below, beneficial, benefit, benefits, best, better, between, beyond, bills,
binding, birth, board, boards, bodies, body, bolivian, books, border, borders, born, borrowing,
both, botswana, bound, boundaries, branch, branches, breach, bring, bringing, british, broadcasting,
brought, budget, budgetary, budgets, build, building, bundesrat, bundestag, burden, bureau,
business, businesses, by-laws, cabinet, calamity, calculated, calendar, call, called, calling, can,
canada, candidate, candidates, cannot, cantons, capable, capacity, capital, care, career, carried,
carries, carry, carrying, cases, cassation, cast, casting, categories, cause, caused, causes, cease,
ceased, ceases, ceasing, censorship, censure, census, cent, centers, central, certain, certificate,
certified, chair, chairman, chairmen, chairperson, challenge, challenged, chamber, chambers,
chancellor, change, changed, changes, character, characteristics, charge, charged, charges, charter,
chief, chiefs, child, children, china, choice, choose, chosen, christopher, church, circumstance,
circumstances, cities, citizen, citizens, citizenship, city, civic, civil, civilian, claim, claims,
class, classes, clause, clauses, clearly, clerk, close, closed, code, coexistence, cognizance,
collect, collected, collection, collective, collectively, collectivities, college, colour, combat,
come, comes, coming, command, commander, commander-in-chief, commence, commenced, commencement,
commencing, commerce, commercial, commissioner, commissioners, commissions, commit, commitment,
commitments, commits, committed, committee, committees, committing, common, commonwealth, communal,
communes, communicate, communicated, communication, communications, communities, community,
companies, company, compatible, compelled, compensation, competence, competences, competencies,
competent, competition, competitive, complaint, complaints, complementary, complete, completed,
completion, compliance, complied, comply, composed, composing, composition, comprehensive, comprise,
comprised, comprises, comprising, comptroller, compulsorily, compulsory, concern, concerned,
concerning, concerns, concession, concessions, conclude, concluded, conclusion, conclusive, concur,
concurrence, concurrent, concurrently, concurs, condition, conditions, conduct, conducted,
conducting, conducts, confederation, confer, conference, conferred, conferring, confers, confidence,
confidentiality, confirm, confirmation, confirmed, confiscation, conflict, conflicts, conform,
conforming, conformity, congress, connected, connection, conscience, conscientiously, consecutive,
consent, consequence, consequences, conservation, consider, consideration, considered, considering,
considers, consist, consistent, consisting, consists, consolidated, consolidation, constituencies,
constituency, constituent, constitute, constituted, constitutes, constituting, constitutionality,
constitutions, construction, construed, consular, consult, consultation, consultations,
consultative, consulted, consulting, consumption, contain, contained, containing, contains,
contemplated, contempt, content, contents, context, continental, continuance, continue, continued,
continues, continuing, continuity, continuous, continuously, contract, contracts, contrary,
contravene, contravened, contravention, contribute, contribution, contributions, control,
controlled, controlling, controls, convene, convened, convenes, convenient, convening, convention,
conventions, convicted, conviction, convictions, convocation, convoke, convoked, cooperate,
cooperation, cooperative, cooperatives, coordinate, coordination, copies, copy, corporate,
corporation, corporations, corps, corpus, correct, correctional, correspond, correspondence,
corresponding, corresponds, corruption, cost, costs, could, councillors, councilors, councils,
counsel, counted, countersigned, counties, counting, countries, country, county, course, courts,
cover, covered, create, created, creating, creation, creative, credentials, credit, credits, creed,
crime, crimes, criminal, criminally, criteria, croatia, croatian, crown, cruel, cultural, culture,
cultures, currency, current, custody, custom, customary, customs, damage, damages, danger,
dangerous, data, date, dates, day, de, deadline, deal, dealing, dealt, death, debate, debated,
debates, debt, debts, december, decent, decentralization, decentralized, decide, decided, decides,
deciding, decision, decision-making, decisions, declaration, declarations, declare, declared,
declares, declaring, decorations, decree, decreed, decrees, deem, deemed, deems, default, defence,
defend, defendant, defender, defense, define, defined, definition, definitive, definitively,
degrading, degree, delay, delegate, delegated, delegates, delegation, deliberate, deliberation,
deliberations, delicto, delimitation, deliver, delivered, delivery, demand, demands, democracy,
democratic, denied, denomination, department, departmental, departments, depend, deposit, deposited,
deprivation, deprive, deprived, deputies, deputy, derived, descent, described, description,
designate, designated, designation, designed, desirable, desire, detail, detailed, details,
detained, detention, determination, determine, determined, determines, determining, detriment,
develop, developing, development, di-pertuan, did, dies, diet, differences, different, dignity,
diplomatic, direct, directed, direction, directions, directive, directives, directly, director,
directors, directs, disabilities, disability, disabled, disadvantage, disaster, disasters,
discharge, discharged, discharging, disciplinary, discipline, disciplined, disclose, disclosure,
discretion, discrimination, discriminatory, discuss, discussed, discussion, disease, dismiss,
dismissal, dismissed, disposal, dispose, disposition, dispute, disputes, disqualification,
disqualified, disseminate, dissemination, dissolution, dissolve, dissolved, distinction,
distributed, distribution, district, districts, diversity, divided, division, divisions, do,
document, documents, does, doing, domain, domestic, domicile, dominica, done, doubt, down, draft,
drafting, draw, drawing, drawn, drugs, due, duly, duration, during, duties, duty, each, earlier,
east, ecological, economic, economy, educate, education, educational, effect, effected, effective,
effectively, effectiveness, effects, efficiency, efficient, efforts, eight, eighteen, either,
elapsed, elderly, elect, electing, elections, elective, elector, electoral, electorate, electors,
elects, elements, eligibility, eligible, eliminate, elimination, elsewhere, emblem, emergency,
emolument, emoluments, employed, employee, employees, employers, employment, empowered, enable,
enabling, enact, enacted, enactment, encourage, end, endanger, endeavour, ending, ends, enemy,
energy, enforce, enforceable, enforced, enforcement, enforcing, engage, engaged, english, enhance,
enjoy, enjoying, enjoyment, enjoys, enquire, enquired, enshrined, ensure, ensured, ensures,
ensuring, enter, entered, entering, enterprise, enterprises, enters, entire, entities, entitled,
entity, entrusted, entry, enumerated, environment, environmental, envisaged, envoys, equal,
equality, equally, equitable, equity, equivalent, especially, essential, establish, establishes,
establishing, establishment, establishments, estate, estimate, estimates, etc, ethics, ethnic,
european, evaluation, even, event, events, every, everyone, evidence, ex, examination, examine,
examined, exceed, exceeding, exceeds, except, excepted, exception, exceptional, exceptionally,
exceptions, excess, exchange, exclude, excluded, excluding, exclusion, exclusive, exclusively,
execute, executed, execution, executive, exempt, exercisable, exercised, exercises, exercising,
exist, existence, existing, exists, expedient, expelled, expended, expenditure, expenditures,
expense, expenses, experience, expiration, expire, expired, expires, expiry, explanation,
exploitation, express, expressed, expression, expressions, expressly, expropriation, expulsion,
extend, extended, extends, extension, extent, external, extradition, extraordinary, facilitate,
facilities, fact, factors, facts, fail, failed, fails, failure, fair, fairly, faith, faithful,
faithfully, fall, falling, falls, families, family, far, farmers, father, favor, favorable, favour,
favourable, fear, february, federation, fee, fees, feminine, fewer, field, fields, fifteen, fifth,
fifty, file, filed, fill, filled, final, finally, finance, financed, finances, financial, financing,
findings, finds, fine, first, fiscal, fit, five, fix, fixed, flag, flagrante, follow, followed,
follows, food, forbidden, forced, forces, foregoing, foreign, foreigners, forests, forfeiture, form,
formal, formalities, formation, formed, former, forming, forms, formulate, formulation, forth,
forthwith, forty, forty-eight, forty-five, forward, foster, found, foundation, foundations, founded,
four, fourteen, fourth, framework, free, freedom, freedoms, freely, french, fulfil, fulfill,
fulfilling, fulfillment, fulfilment, full, fully, function, functional, functionaries, functioning,
fund, fundamental, funding, funds, furnish, further, future, gambia, gazette, gender, generality,
generally, generation, generations, geographical, georgia, ghana, give, given, gives, giving, goals,
god, good, goods, govern, governance, governed, governing, governmental, governments, governor,
governor-general, governors, grand, grant, granted, granting, grants, gratuities, gratuity, grave,
great, greater, greatest, green, grenada, gross, ground, grounds, group, groups, growth, guarantee,
guaranteed, guaranteeing, guarantees, guarantor, guardian, guide, guided, guidelines, guilty,
guinea, guyana, habeas, half, hand, handicapped, harm, harmful, harmonious, harmony, having, head,
headed, heads, health, healthy, hear, heard, hearing, hearings, held, help, hereby, herein,
hereinafter, hereof, heritage, herself, high, higher, highest, him, himself, hindered, historic,
historical, history, hluttaw, hold, holder, holders, holding, holds, holidays, holy, home, homeland,
honor, honorary, honour, hours, houses, housing, how, however, human, humanity, hundred, hygiene,
ideas, identical, identity, ideological, ideology, ii, iii, illegal, illness, immediate,
immediately, immigration, imminent, immunities, immunity, impartial, impartiality, impeached,
impeachment, impediment, implement, implementation, implemented, implementing, importance,
important, impose, imposed, imposes, imposing, imposition, impracticable, imprisoned, imprisonment,
improve, improvement, improving, inability, inalienable, incapable, incapacitated, incapacity,
incidental, include, included, includes, including, inclusion, inclusive, income, incompatibilities,
incompatibility, incompatible, inconsistency, inconsistent, incorporated, increase, increased,
increasing, incumbent, incurred, independence, independent, independently, india, indicate,
indicated, indigenous, indirect, indirectly, indispensable, individual, individually, individuals,
indivisible, industrial, industry, inferior, infirmity, influence, inform, information, informed,
infrastructure, infringe, infringed, infringement, inhabitants, inherent, inheritance, inhuman,
initial, initiate, initiated, initiative, initiatives, innocent, inquire, inquiries, inquiry,
inserted, insofar, inspect, inspection, installation, instance, instances, instead, institute,
instituted, institution, institutional, institutions, instruction, instructions, instrument,
instruments, insufficient, insurance, integral, integrated, integration, integrity, intellectual,
intelligence, intended, intention, interest, interested, interests, interfere, interference,
interim, interior, internal, international, interpellation, interpretation, interpreted,
interpreter, interval, intervals, intervene, intervention, introduce, introduced, introduction,
invalid, invalidate, invested, investigate, investigated, investigating, investigation,
investigations, investment, investments, inviolability, inviolable, involve, involved, involves,
involving, irrespective, islam, islamic, island, islands, issuance, issue, issued, issues, issuing,
item, items, itself, iv, jamaica, january, job, join, joint, jointly, journal, judge, judged,
judgement, judges, judgment, judgments, judicature, judiciary, july, june, juridical, jurisdiction,
jurisdictional, jurisdictions, jury, just, justices, justifiable, justified, kazakhstan, keep,
keeping, kenya, kept, kind, king, kingdom, kiribati, knesset, knowledge, known, kosovo, la, labor,
labour, lack, laid, land, lands, language, languages, lanka, lapse, lapsed, largest, last, later,
latest, latter, lawful, lawfully, lawyer, lawyers, lay, lead, leader, leaders, leadership, leading,
learning, lease, least, leave, left, legal, legality, legally, legislate, legislation, legislative,
legislature, legislatures, legitimate, length, leone, lesotho, less, letters, level, levels, levied,
levy, liabilities, liability, liable, liberation, liberties, liberty, lie, life, like, likely,
likewise, limit, limitation, limitations, limited, limits, line, linguistic, list, listed, lists,
lithuania, live, lives, living, loan, loans, local, located, long, longer, lose, loss, lost, lower,
loyal, loyalty, macedonia, magistrate, magistrates, magistrature, main, maintain, maintained,
maintaining, maintenance, majesty, majlis, majlis-e-shoora, major, majority, make, makes, making,
malawi, maldives, male, malta, man, manage, managed, management, managing, mandate, mandates,
mandatory, maneaba, manifest, manner, many, march, maritime, market, marriage, married, martial,
masculine, mass, material, materials, maternity, matter, matters, maungatabu, mauritius, maximum,
mayor, mayors, me, mean, meaning, means, measure, measures, mechanisms, media, medical, meet,
meeting, meetings, meets, membership, men, mental, mentioned, mercy, merely, merit, message,
messages, met, method, methods, metropolitan, might, military, milli, mind, mineral, minerals,
minimum, ministerial, ministers, ministries, ministry, minor, minorities, minority, minors, minutes,
misbehaviour, misconduct, mission, missions, mobilization, modalities, mode, modification,
modifications, modified, modify, moldova, moment, monetary, money, moneys, monies, monitor,
monitoring, montenegro, month, months, monuments, moral, morality, morals, more, most, mother,
motion, motions, move, moved, movement, movements, municipal, municipalities, municipality,
mutandis, mutatis, mutual, my, name, named, namely, names, namibia, nation, nationalities,
nationality, nationals, nations, native, natural, naturalization, nature, naval, navy, nearly,
necessary, necessity, need, needed, needs, neither, nepal, neutrality, never, nevertheless, nevis,
new, newly, next, ni, nine, ninety, nitijela, nominate, nominated, nomination, nominations, none,
nor, normal, normative, norms, notably, nothing, notice, notification, notified, notify,
notwithstanding, november, now, number, numbers, oath, oaths, obedience, obey, object, objection,
objections, objective, objectives, objects, obligated, obligation, obligations, obligatorily,
obligatory, obliged, observance, observations, observe, observed, observing, obtain, obtained,
obtaining, obtains, occasion, occupation, occupy, occur, occurred, occurrence, occurs, october,
offence, offences, offense, offenses, offer, officer, officers, offices, official, officially,
officials, officio, old, ombudsman, omission, omissions, omitted, once, one-fifth, one-fourth, one-
half, one-third, ones, open, opened, opening, operate, operating, operation, operations, opinion,
opinions, opportunities, opportunity, opposition, option, oral, ordered, orders, ordinance,
ordinances, ordinarily, ordinary, organ, organic, organisation, organisations, organised,
organization, organizations, organize, organized, organs, origin, original, others, otherwise,
ought, our, out, outside, over, overall, oversee, oversight, owing, own, owned, owner, owners,
ownership, paid, pakistan, paper, papers, papua, para, pardon, pardons, parent, parents,
parliamentary, partial, partially, participate, participating, participation, particular,
particularly, particulars, parties, party, pass, passage, passed, passes, passing, past, patrimony,
pay, payable, payment, payments, peace, peaceful, penal, penalties, penalty, pending, pension,
pensions, people, peoples, per, percent, percentage, perform, performance, performed, performing,
performs, periodic, periods, permanent, permanently, permissible, permission, permit, permits,

term_str               abide  ability  able  abolish  abolished  abolition  \
country_id  article_n
Afghanistan 1            0.0      0.0   0.0      0.0        0.0        0.0
            2            0.0      0.0   0.0      0.0        0.0        0.0
            3            0.0      0.0   0.0      0.0        0.0        0.0
            4            0.0      0.0   0.0      0.0        0.0        0.0
            5            0.0      0.0   0.0      0.0        0.0        0.0
            6            0.0      0.0   0.0      0.0        0.0        0.0
            7            0.0      0.0   0.0      0.0        0.0        0.0
            8            0.0      0.0   0.0      0.0        0.0        0.0
            9            0.0      0.0   0.0      0.0        0.0        0.0
            10           0.0      0.0   0.0      0.0        0.0        0.0

term_str               about  above  abroad  abrogated  absence  absent  \
country_id  article_n
Afghanistan 1            0.0    0.0     0.0        0.0      0.0     0.0
            2            0.0    0.0     0.0        0.0      0.0     0.0
            3            0.0    0.0     0.0        0.0      0.0     0.0
            4            0.0    0.0     0.0        0.0      0.0     0.0
            5            0.0    0.0     0.0        0.0      0.0     0.0
            6            0.0    0.0     0.0        0.0      0.0     0.0
            7            0.0    0.0     0.0        0.0      0.0     0.0
            8            0.0    0.0     0.0        0.0      0.0     0.0
            9            0.0    0.0     0.0        0.0      0.0     0.0
            10           0.0    0.0     0.0        0.0      0.0     0.0

term_str               absolute  abuse  academic  accept  acceptance  \
country_id  article_n
Afghanistan 1               0.0    0.0       0.0     0.0         0.0
            2               0.0    0.0       0.0     0.0         0.0
            3               0.0    0.0       0.0     0.0         0.0
            4               0.0    0.0       0.0     0.0         0.0
            5               0.0    0.0       0.0     0.0         0.0
            6               0.0    0.0       0.0     0.0         0.0
            7               0.0    0.0       0.0     0.0         0.0
            8               0.0    0.0       0.0     0.0         0.0
            9               0.0    0.0       0.0     0.0         0.0
            10              0.0    0.0       0.0     0.0         0.0

term_str               accepted  accepts  access  accessible  accompanied  \
country_id  article_n
Afghanistan 1               0.0      0.0     0.0         0.0          0.0
            2               0.0      0.0     0.0         0.0          0.0
            3               0.0      0.0     0.0         0.0          0.0
            4               0.0      0.0     0.0         0.0          0.0
            5               0.0      0.0     0.0         0.0          0.0
            6               0.0      0.0     0.0         0.0          0.0
            7               0.0      0.0     0.0         0.0          0.0
            8               0.0      0.0     0.0         0.0          0.0
            9               0.0      0.0     0.0         0.0          0.0
            10              0.0      0.0     0.0         0.0          0.0

term_str               accord  accorded  according  accordingly  account  \
country_id  article_n
Afghanistan 1             0.0       0.0        0.0          0.0      0.0
            2             0.0       0.0        0.0          0.0      0.0
            3             0.0       0.0        0.0          0.0      0.0
            4             0.0       0.0        0.0          0.0      0.0
            5             0.0       0.0        0.0          0.0      0.0
            6             0.0       0.0        0.0          0.0      0.0
            7             0.0       0.0        0.0          0.0      0.0
            8             0.0       0.0        0.0          0.0      0.0
            9             0.0       0.0        0.0          0.0      0.0
            10            0.0       0.0        0.0          0.0      0.0

term_str               accountability  accountable  accounting  accounts  \
country_id  article_n
Afghanistan 1                     0.0          0.0         0.0       0.0
            2                     0.0          0.0         0.0       0.0
            3                     0.0          0.0         0.0       0.0
            4                     0.0          0.0         0.0       0.0
            5                     0.0          0.0         0.0       0.0
            6                     0.0          0.0         0.0       0.0
            7                     0.0          0.0         0.0       0.0
            8                     0.0          0.0         0.0       0.0
            9                     0.0          0.0         0.0       0.0
            10                    0.0          0.0         0.0       0.0

term_str               accredited  accusation  accused  achieve  achieving  \
country_id  article_n
Afghanistan 1                 0.0         0.0      0.0      0.0        0.0
            2                 0.0         0.0      0.0      0.0        0.0
            3                 0.0         0.0      0.0      0.0        0.0
            4                 0.0         0.0      0.0      0.0        0.0
            5                 0.0         0.0      0.0      0.0        0.0
            6                 0.0         0.0      0.0      0.0        0.0
            7                 0.0         0.0      0.0      0.0        0.0
            8                 0.0         0.0      0.0      0.0        0.0
            9                 0.0         0.0      0.0      0.0        0.0
            10                0.0         0.0      0.0      0.0        0.0

term_str               acquire  acquired  acquisition  acquitted  acted  \
country_id  article_n
Afghanistan 1              0.0       0.0          0.0        0.0    0.0
            2              0.0       0.0          0.0        0.0    0.0
            3              0.0       0.0          0.0        0.0    0.0
            4              0.0       0.0          0.0        0.0    0.0
            5              0.0       0.0          0.0        0.0    0.0
            6              0.0       0.0          0.0        0.0    0.0
            7              0.0       0.0          0.0        0.0    0.0
            8              0.0       0.0          0.0        0.0    0.0
            9              0.0       0.0          0.0        0.0    0.0
            10             0.0       0.0          0.0        0.0    0.0

term_str               acting  action  actions  active  activities  activity  \
country_id  article_n
Afghanistan 1             0.0     0.0      0.0     0.0    0.000000       0.0
            2             0.0     0.0      0.0     0.0    0.000000       0.0
            3             0.0     0.0      0.0     0.0    0.000000       0.0
            4             0.0     0.0      0.0     0.0    0.000000       0.0
            5             0.0     0.0      0.0     0.0    0.000000       0.0
            6             0.0     0.0      0.0     0.0    0.000000       0.0
            7             0.0     0.0      0.0     0.0    0.000000       0.0
            8             0.0     0.0      0.0     0.0    0.222988       0.0
            9             0.0     0.0      0.0     0.0    0.000000       0.0
            10            0.0     0.0      0.0     0.0    0.000000       0.0

term_str               acts  actual   ad  ...      well  well-being  what  \
country_id  article_n                     ...
Afghanistan 1           0.0     0.0  0.0  ...  0.245513         0.0   0.0
            2           0.0     0.0  0.0  ...  0.000000         0.0   0.0
            3           0.0     0.0  0.0  ...  0.000000         0.0   0.0
            4           0.0     0.0  0.0  ...  0.000000         0.0   0.0
            5           0.0     0.0  0.0  ...  0.000000         0.0   0.0
            6           0.0     0.0  0.0  ...  0.000000         0.0   0.0
            7           0.0     0.0  0.0  ...  0.149778         0.0   0.0
            8           0.0     0.0  0.0  ...  0.190451         0.0   0.0
            9           0.0     0.0  0.0  ...  0.203606         0.0   0.0
            10          0.0     0.0  0.0  ...  0.373683         0.0   0.0

term_str               whatever  whatsoever  whenever  where  whereas  \
country_id  article_n
Afghanistan 1               0.0         0.0       0.0    0.0      0.0
            2               0.0         0.0       0.0    0.0      0.0
            3               0.0         0.0       0.0    0.0      0.0
            4               0.0         0.0       0.0    0.0      0.0
            5               0.0         0.0       0.0    0.0      0.0
            6               0.0         0.0       0.0    0.0      0.0
            7               0.0         0.0       0.0    0.0      0.0
            8               0.0         0.0       0.0    0.0      0.0
            9               0.0         0.0       0.0    0.0      0.0
            10              0.0         0.0       0.0    0.0      0.0

term_str               whereby  whether  whichever  while  white  whoever  \
country_id  article_n
Afghanistan 1              0.0      0.0        0.0    0.0    0.0      0.0
            2              0.0      0.0        0.0    0.0    0.0      0.0
            3              0.0      0.0        0.0    0.0    0.0      0.0
            4              0.0      0.0        0.0    0.0    0.0      0.0
            5              0.0      0.0        0.0    0.0    0.0      0.0
            6              0.0      0.0        0.0    0.0    0.0      0.0
            7              0.0      0.0        0.0    0.0    0.0      0.0
            8              0.0      0.0        0.0    0.0    0.0      0.0
            9              0.0      0.0        0.0    0.0    0.0      0.0
            10             0.0      0.0        0.0    0.0    0.0      0.0

term_str               whole  wholly  whom  whose  wish  wishes  withdraw  \
country_id  article_n
Afghanistan 1            0.0     0.0   0.0    0.0   0.0     0.0       0.0
            2            0.0     0.0   0.0    0.0   0.0     0.0       0.0
            3            0.0     0.0   0.0    0.0   0.0     0.0       0.0
            4            0.0     0.0   0.0    0.0   0.0     0.0       0.0
            5            0.0     0.0   0.0    0.0   0.0     0.0       0.0
            6            0.0     0.0   0.0    0.0   0.0     0.0       0.0
            7            0.0     0.0   0.0    0.0   0.0     0.0       0.0
            8            0.0     0.0   0.0    0.0   0.0     0.0       0.0
            9            0.0     0.0   0.0    0.0   0.0     0.0       0.0
            10           0.0     0.0   0.0    0.0   0.0     0.0       0.0

term_str               withdrawal  withdrawn  witness  witnesses  woman  \
country_id  article_n
Afghanistan 1                 0.0        0.0      0.0        0.0    0.0
            2                 0.0        0.0      0.0        0.0    0.0
            3                 0.0        0.0      0.0        0.0    0.0
            4                 0.0        0.0      0.0        0.0    0.0
            5                 0.0        0.0      0.0        0.0    0.0
            6                 0.0        0.0      0.0        0.0    0.0
            7                 0.0        0.0      0.0        0.0    0.0
            8                 0.0        0.0      0.0        0.0    0.0
            9                 0.0        0.0      0.0        0.0    0.0
            10                0.0        0.0      0.0        0.0    0.0

term_str               women  words  work  worker  workers  working  works  \
country_id  article_n
Afghanistan 1            0.0    0.0   0.0     0.0      0.0      0.0    0.0
            2            0.0    0.0   0.0     0.0      0.0      0.0    0.0
            3            0.0    0.0   0.0     0.0      0.0      0.0    0.0
            4            0.0    0.0   0.0     0.0      0.0      0.0    0.0
            5            0.0    0.0   0.0     0.0      0.0      0.0    0.0
            6            0.0    0.0   0.0     0.0      0.0      0.0    0.0
            7            0.0    0.0   0.0     0.0      0.0      0.0    0.0
            8            0.0    0.0   0.0     0.0      0.0      0.0    0.0
            9            0.0    0.0   0.0     0.0      0.0      0.0    0.0
            10           0.0    0.0   0.0     0.0      0.0      0.0    0.0

term_str               world  worship  would  writ  writing  writs  written  \
country_id  article_n
Afghanistan 1            0.0      0.0    0.0   0.0      0.0    0.0      0.0
            2            0.0      0.0    0.0   0.0      0.0    0.0      0.0
            3            0.0      0.0    0.0   0.0      0.0    0.0      0.0
            4            0.0      0.0    0.0   0.0      0.0    0.0      0.0
            5            0.0      0.0    0.0   0.0      0.0    0.0      0.0
            6            0.0      0.0    0.0   0.0      0.0    0.0      0.0
            7            0.0      0.0    0.0   0.0      0.0    0.0      0.0
            8            0.0      0.0    0.0   0.0      0.0    0.0      0.0
            9            0.0      0.0    0.0   0.0      0.0    0.0      0.0
            10           0.0      0.0    0.0   0.0      0.0    0.0      0.0

term_str               yang  year  yet  young  youth  yuan  zambia  zimbabwe  \
country_id  article_n
Afghanistan 1           0.0   0.0  0.0    0.0    0.0   0.0     0.0       0.0
            2           0.0   0.0  0.0    0.0    0.0   0.0     0.0       0.0
            3           0.0   0.0  0.0    0.0    0.0   0.0     0.0       0.0
            4           0.0   0.0  0.0    0.0    0.0   0.0     0.0       0.0
            5           0.0   0.0  0.0    0.0    0.0   0.0     0.0       0.0
            6           0.0   0.0  0.0    0.0    0.0   0.0     0.0       0.0
            7           0.0   0.0  0.0    0.0    0.0   0.0     0.0       0.0
            8           0.0   0.0  0.0    0.0    0.0   0.0     0.0       0.0
            9           0.0   0.0  0.0    0.0    0.0   0.0     0.0       0.0
            10          0.0   0.0  0.0    0.0    0.0   0.0     0.0       0.0

term_str               zone  zones
country_id  article_n
Afghanistan 1           0.0    0.0
            2           0.0    0.0
            3           0.0    0.0
            4           0.0    0.0
            5           0.0    0.0
            6           0.0    0.0
            7           0.0    0.0
            8           0.0    0.0
            9           0.0    0.0
            10          0.0    0.0

[10 rows x 3006 columns]

## PCA Components

This section inspects the PCA components table produced from the reduced TFIDF representation.

In [6]:
PCA_COMPS = inspect_table(
    section='PCA Components',
    box_url='https://virginia.box.com/shared/static/z8ytkodps3omi9wmgf8vdmk98s8s8c0h',
    local_path='pca_comps.parquet',
    file_format='parquet'
)

Section: PCA Components
Box URL: https://virginia.box.com/shared/static/z8ytkodps3omi9wmgf8vdmk98s8s8c0h
Local file: pca_comps.parquet
Loaded from: Box download
Format: parquet
Shape: 3,006 rows x 3,006 columns
Number of observations: 3,006
Column names:
abide, ability, able, abolish, abolished, abolition, about, above, abroad, abrogated, absence,
absent, absolute, abuse, academic, accept, acceptance, accepted, accepts, access, accessible,
accompanied, accord, accorded, according, accordingly, account, accountability, accountable,
accounting, accounts, accredited, accusation, accused, achieve, achieving, acquire, acquired,
acquisition, acquitted, acted, acting, action, actions, active, activities, activity, acts, actual,
ad, adaptations, added, addition, additional, address, addressed, adequate, adherence, adjourn,
adjournment, adjudged, adjudicate, administer, administered, administering, administration,
administrations, administrative, administrator, admissible, admission, admitted, adopt, adopted,
adopting, adoption, adopts, adult, advance, advanced, advancement, advice, advise, adviser, advises,
advisory, advocate, affairs, affect, affected, affecting, affection, affects, affiliation, affirm,
affirmation, affirmative, afforded, aforementioned, aforesaid, african, again, against, age,
agencies, agency, agenda, agent, agents, aggregate, aggression, aggrieved, agong, agree, agreed,
agreement, agreements, agricultural, agriculture, aid, aim, aimed, aims, air, aliens, alleged,
allegiance, allocated, allocation, allow, allowance, allowances, allowed, almighty, alone, along,
already, also, alter, alteration, altered, altering, alternate, alternative, always, ambassadors,
amend, amended, amending, amendment, amendments, amnesty, among, amongst, amount, amounts, animals,
announced, announcement, annual, annually, annul, another, answer, answerable, anthem, antigua,
anyone, anything, apart, appeal, appealed, appeals, appear, appears, appellate, applicable,
application, applications, applied, applies, apply, applying, appoint, appointing, appointment,
appointments, appoints, appropriate, appropriated, appropriation, appropriations, approval, approve,
approved, approves, approving, april, arab, arbitration, area, areas, arise, arisen, arises,
arising, armed, arms, army, arrangements, arrest, arrested, art, artistic, arts, aside, ask,
aspects, aspirations, assemble, assemblies, assent, assented, assessment, assets, assign, assigned,
assignment, assist, assistance, assistant, assisted, associate, associated, association,
associations, assume, assumed, assumes, assuming, assumption, assure, assured, assures, assuring,
asylum, attached, attained, attaining, attains, attend, attendance, attending, attention, attorney,
attorney-general, attorneys, attributed, attributions, audit, audited, auditor, auditor-general,
august, authorisation, authorise, authorised, authorises, authorising, authorities, authorization,
authorize, authorized, automatically, autonomous, autonomy, available, avoid, award, awards,
azerbaijan, back, bahamas, balance, balanced, ballot, bangladesh, bank, banking, bankrupt, banks,
bar, barbuda, base, based, bases, basic, basis, bear, bearing, became, because, become, becomes,
becoming, begin, beginning, begins, behalf, being, beings, belarus, belief, beliefs, belize, belong,
belonging, belongs, below, beneficial, benefit, benefits, best, better, between, beyond, bills,
binding, birth, board, boards, bodies, body, bolivian, books, border, borders, born, borrowing,
both, botswana, bound, boundaries, branch, branches, breach, bring, bringing, british, broadcasting,
brought, budget, budgetary, budgets, build, building, bundesrat, bundestag, burden, bureau,
business, businesses, by-laws, cabinet, calamity, calculated, calendar, call, called, calling, can,
canada, candidate, candidates, cannot, cantons, capable, capacity, capital, care, career, carried,
carries, carry, carrying, cases, cassation, cast, casting, categories, cause, caused, causes, cease,
ceased, ceases, ceasing, censorship, censure, census, cent, centers, central, certain, certificate,
certified, chair, chairman, chairmen, chairperson, challenge, challenged, chamber, chambers,
chancellor, change, changed, changes, character, characteristics, charge, charged, charges, charter,
chief, chiefs, child, children, china, choice, choose, chosen, christopher, church, circumstance,
circumstances, cities, citizen, citizens, citizenship, city, civic, civil, civilian, claim, claims,
class, classes, clause, clauses, clearly, clerk, close, closed, code, coexistence, cognizance,
collect, collected, collection, collective, collectively, collectivities, college, colour, combat,
come, comes, coming, command, commander, commander-in-chief, commence, commenced, commencement,
commencing, commerce, commercial, commissioner, commissioners, commissions, commit, commitment,
commitments, commits, committed, committee, committees, committing, common, commonwealth, communal,
communes, communicate, communicated, communication, communications, communities, community,
companies, company, compatible, compelled, compensation, competence, competences, competencies,
competent, competition, competitive, complaint, complaints, complementary, complete, completed,
completion, compliance, complied, comply, composed, composing, composition, comprehensive, comprise,
comprised, comprises, comprising, comptroller, compulsorily, compulsory, concern, concerned,
concerning, concerns, concession, concessions, conclude, concluded, conclusion, conclusive, concur,
concurrence, concurrent, concurrently, concurs, condition, conditions, conduct, conducted,
conducting, conducts, confederation, confer, conference, conferred, conferring, confers, confidence,
confidentiality, confirm, confirmation, confirmed, confiscation, conflict, conflicts, conform,
conforming, conformity, congress, connected, connection, conscience, conscientiously, consecutive,
consent, consequence, consequences, conservation, consider, consideration, considered, considering,
considers, consist, consistent, consisting, consists, consolidated, consolidation, constituencies,
constituency, constituent, constitute, constituted, constitutes, constituting, constitutionality,
constitutions, construction, construed, consular, consult, consultation, consultations,
consultative, consulted, consulting, consumption, contain, contained, containing, contains,
contemplated, contempt, content, contents, context, continental, continuance, continue, continued,
continues, continuing, continuity, continuous, continuously, contract, contracts, contrary,
contravene, contravened, contravention, contribute, contribution, contributions, control,
controlled, controlling, controls, convene, convened, convenes, convenient, convening, convention,
conventions, convicted, conviction, convictions, convocation, convoke, convoked, cooperate,
cooperation, cooperative, cooperatives, coordinate, coordination, copies, copy, corporate,
corporation, corporations, corps, corpus, correct, correctional, correspond, correspondence,
corresponding, corresponds, corruption, cost, costs, could, councillors, councilors, councils,
counsel, counted, countersigned, counties, counting, countries, country, county, course, courts,
cover, covered, create, created, creating, creation, creative, credentials, credit, credits, creed,
crime, crimes, criminal, criminally, criteria, croatia, croatian, crown, cruel, cultural, culture,
cultures, currency, current, custody, custom, customary, customs, damage, damages, danger,
dangerous, data, date, dates, day, de, deadline, deal, dealing, dealt, death, debate, debated,
debates, debt, debts, december, decent, decentralization, decentralized, decide, decided, decides,
deciding, decision, decision-making, decisions, declaration, declarations, declare, declared,
declares, declaring, decorations, decree, decreed, decrees, deem, deemed, deems, default, defence,
defend, defendant, defender, defense, define, defined, definition, definitive, definitively,
degrading, degree, delay, delegate, delegated, delegates, delegation, deliberate, deliberation,
deliberations, delicto, delimitation, deliver, delivered, delivery, demand, demands, democracy,
democratic, denied, denomination, department, departmental, departments, depend, deposit, deposited,
deprivation, deprive, deprived, deputies, deputy, derived, descent, described, description,
designate, designated, designation, designed, desirable, desire, detail, detailed, details,
detained, detention, determination, determine, determined, determines, determining, detriment,
develop, developing, development, di-pertuan, did, dies, diet, differences, different, dignity,
diplomatic, direct, directed, direction, directions, directive, directives, directly, director,
directors, directs, disabilities, disability, disabled, disadvantage, disaster, disasters,
discharge, discharged, discharging, disciplinary, discipline, disciplined, disclose, disclosure,
discretion, discrimination, discriminatory, discuss, discussed, discussion, disease, dismiss,
dismissal, dismissed, disposal, dispose, disposition, dispute, disputes, disqualification,
disqualified, disseminate, dissemination, dissolution, dissolve, dissolved, distinction,
distributed, distribution, district, districts, diversity, divided, division, divisions, do,
document, documents, does, doing, domain, domestic, domicile, dominica, done, doubt, down, draft,
drafting, draw, drawing, drawn, drugs, due, duly, duration, during, duties, duty, each, earlier,
east, ecological, economic, economy, educate, education, educational, effect, effected, effective,
effectively, effectiveness, effects, efficiency, efficient, efforts, eight, eighteen, either,
elapsed, elderly, elect, electing, elections, elective, elector, electoral, electorate, electors,
elects, elements, eligibility, eligible, eliminate, elimination, elsewhere, emblem, emergency,
emolument, emoluments, employed, employee, employees, employers, employment, empowered, enable,
enabling, enact, enacted, enactment, encourage, end, endanger, endeavour, ending, ends, enemy,
energy, enforce, enforceable, enforced, enforcement, enforcing, engage, engaged, english, enhance,
enjoy, enjoying, enjoyment, enjoys, enquire, enquired, enshrined, ensure, ensured, ensures,
ensuring, enter, entered, entering, enterprise, enterprises, enters, entire, entities, entitled,
entity, entrusted, entry, enumerated, environment, environmental, envisaged, envoys, equal,
equality, equally, equitable, equity, equivalent, especially, essential, establish, establishes,
establishing, establishment, establishments, estate, estimate, estimates, etc, ethics, ethnic,
european, evaluation, even, event, events, every, everyone, evidence, ex, examination, examine,
examined, exceed, exceeding, exceeds, except, excepted, exception, exceptional, exceptionally,
exceptions, excess, exchange, exclude, excluded, excluding, exclusion, exclusive, exclusively,
execute, executed, execution, executive, exempt, exercisable, exercised, exercises, exercising,
exist, existence, existing, exists, expedient, expelled, expended, expenditure, expenditures,
expense, expenses, experience, expiration, expire, expired, expires, expiry, explanation,
exploitation, express, expressed, expression, expressions, expressly, expropriation, expulsion,
extend, extended, extends, extension, extent, external, extradition, extraordinary, facilitate,
facilities, fact, factors, facts, fail, failed, fails, failure, fair, fairly, faith, faithful,
faithfully, fall, falling, falls, families, family, far, farmers, father, favor, favorable, favour,
favourable, fear, february, federation, fee, fees, feminine, fewer, field, fields, fifteen, fifth,
fifty, file, filed, fill, filled, final, finally, finance, financed, finances, financial, financing,
findings, finds, fine, first, fiscal, fit, five, fix, fixed, flag, flagrante, follow, followed,
follows, food, forbidden, forced, forces, foregoing, foreign, foreigners, forests, forfeiture, form,
formal, formalities, formation, formed, former, forming, forms, formulate, formulation, forth,
forthwith, forty, forty-eight, forty-five, forward, foster, found, foundation, foundations, founded,
four, fourteen, fourth, framework, free, freedom, freedoms, freely, french, fulfil, fulfill,
fulfilling, fulfillment, fulfilment, full, fully, function, functional, functionaries, functioning,
fund, fundamental, funding, funds, furnish, further, future, gambia, gazette, gender, generality,
generally, generation, generations, geographical, georgia, ghana, give, given, gives, giving, goals,
god, good, goods, govern, governance, governed, governing, governmental, governments, governor,
governor-general, governors, grand, grant, granted, granting, grants, gratuities, gratuity, grave,
great, greater, greatest, green, grenada, gross, ground, grounds, group, groups, growth, guarantee,
guaranteed, guaranteeing, guarantees, guarantor, guardian, guide, guided, guidelines, guilty,
guinea, guyana, habeas, half, hand, handicapped, harm, harmful, harmonious, harmony, having, head,
headed, heads, health, healthy, hear, heard, hearing, hearings, held, help, hereby, herein,
hereinafter, hereof, heritage, herself, high, higher, highest, him, himself, hindered, historic,
historical, history, hluttaw, hold, holder, holders, holding, holds, holidays, holy, home, homeland,
honor, honorary, honour, hours, houses, housing, how, however, human, humanity, hundred, hygiene,
ideas, identical, identity, ideological, ideology, ii, iii, illegal, illness, immediate,
immediately, immigration, imminent, immunities, immunity, impartial, impartiality, impeached,
impeachment, impediment, implement, implementation, implemented, implementing, importance,
important, impose, imposed, imposes, imposing, imposition, impracticable, imprisoned, imprisonment,
improve, improvement, improving, inability, inalienable, incapable, incapacitated, incapacity,
incidental, include, included, includes, including, inclusion, inclusive, income, incompatibilities,
incompatibility, incompatible, inconsistency, inconsistent, incorporated, increase, increased,
increasing, incumbent, incurred, independence, independent, independently, india, indicate,
indicated, indigenous, indirect, indirectly, indispensable, individual, individually, individuals,
indivisible, industrial, industry, inferior, infirmity, influence, inform, information, informed,
infrastructure, infringe, infringed, infringement, inhabitants, inherent, inheritance, inhuman,
initial, initiate, initiated, initiative, initiatives, innocent, inquire, inquiries, inquiry,
inserted, insofar, inspect, inspection, installation, instance, instances, instead, institute,
instituted, institution, institutional, institutions, instruction, instructions, instrument,
instruments, insufficient, insurance, integral, integrated, integration, integrity, intellectual,
intelligence, intended, intention, interest, interested, interests, interfere, interference,
interim, interior, internal, international, interpellation, interpretation, interpreted,
interpreter, interval, intervals, intervene, intervention, introduce, introduced, introduction,
invalid, invalidate, invested, investigate, investigated, investigating, investigation,
investigations, investment, investments, inviolability, inviolable, involve, involved, involves,
involving, irrespective, islam, islamic, island, islands, issuance, issue, issued, issues, issuing,
item, items, itself, iv, jamaica, january, job, join, joint, jointly, journal, judge, judged,
judgement, judges, judgment, judgments, judicature, judiciary, july, june, juridical, jurisdiction,
jurisdictional, jurisdictions, jury, just, justices, justifiable, justified, kazakhstan, keep,
keeping, kenya, kept, kind, king, kingdom, kiribati, knesset, knowledge, known, kosovo, la, labor,
labour, lack, laid, land, lands, language, languages, lanka, lapse, lapsed, largest, last, later,
latest, latter, lawful, lawfully, lawyer, lawyers, lay, lead, leader, leaders, leadership, leading,
learning, lease, least, leave, left, legal, legality, legally, legislate, legislation, legislative,
legislature, legislatures, legitimate, length, leone, lesotho, less, letters, level, levels, levied,
levy, liabilities, liability, liable, liberation, liberties, liberty, lie, life, like, likely,
likewise, limit, limitation, limitations, limited, limits, line, linguistic, list, listed, lists,
lithuania, live, lives, living, loan, loans, local, located, long, longer, lose, loss, lost, lower,
loyal, loyalty, macedonia, magistrate, magistrates, magistrature, main, maintain, maintained,
maintaining, maintenance, majesty, majlis, majlis-e-shoora, major, majority, make, makes, making,
malawi, maldives, male, malta, man, manage, managed, management, managing, mandate, mandates,
mandatory, maneaba, manifest, manner, many, march, maritime, market, marriage, married, martial,
masculine, mass, material, materials, maternity, matter, matters, maungatabu, mauritius, maximum,
mayor, mayors, me, mean, meaning, means, measure, measures, mechanisms, media, medical, meet,
meeting, meetings, meets, membership, men, mental, mentioned, mercy, merely, merit, message,
messages, met, method, methods, metropolitan, might, military, milli, mind, mineral, minerals,
minimum, ministerial, ministers, ministries, ministry, minor, minorities, minority, minors, minutes,
misbehaviour, misconduct, mission, missions, mobilization, modalities, mode, modification,
modifications, modified, modify, moldova, moment, monetary, money, moneys, monies, monitor,
monitoring, montenegro, month, months, monuments, moral, morality, morals, more, most, mother,
motion, motions, move, moved, movement, movements, municipal, municipalities, municipality,
mutandis, mutatis, mutual, my, name, named, namely, names, namibia, nation, nationalities,
nationality, nationals, nations, native, natural, naturalization, nature, naval, navy, nearly,
necessary, necessity, need, needed, needs, neither, nepal, neutrality, never, nevertheless, nevis,
new, newly, next, ni, nine, ninety, nitijela, nominate, nominated, nomination, nominations, none,
nor, normal, normative, norms, notably, nothing, notice, notification, notified, notify,
notwithstanding, november, now, number, numbers, oath, oaths, obedience, obey, object, objection,
objections, objective, objectives, objects, obligated, obligation, obligations, obligatorily,
obligatory, obliged, observance, observations, observe, observed, observing, obtain, obtained,
obtaining, obtains, occasion, occupation, occupy, occur, occurred, occurrence, occurs, october,
offence, offences, offense, offenses, offer, officer, officers, offices, official, officially,
officials, officio, old, ombudsman, omission, omissions, omitted, once, one-fifth, one-fourth, one-
half, one-third, ones, open, opened, opening, operate, operating, operation, operations, opinion,
opinions, opportunities, opportunity, opposition, option, oral, ordered, orders, ordinance,
ordinances, ordinarily, ordinary, organ, organic, organisation, organisations, organised,
organization, organizations, organize, organized, organs, origin, original, others, otherwise,
ought, our, out, outside, over, overall, oversee, oversight, owing, own, owned, owner, owners,
ownership, paid, pakistan, paper, papers, papua, para, pardon, pardons, parent, parents,
parliamentary, partial, partially, participate, participating, participation, particular,
particularly, particulars, parties, party, pass, passage, passed, passes, passing, past, patrimony,
pay, payable, payment, payments, peace, peaceful, penal, penalties, penalty, pending, pension,
pensions, people, peoples, per, percent, percentage, perform, performance, performed, performing,
performs, periodic, periods, permanent, permanently, permissible, permission, permit, permits,

term_str,abide,ability,able,abolish,abolished,abolition,about,above,abroad,abrogated,absence,absent,absolute,abuse,academic,accept,acceptance,accepted,accepts,access,accessible,accompanied,accord,accorded,according,accordingly,account,accountability,accountable,accounting,accounts,accredited,accusation,accused,achieve,achieving,acquire,acquired,acquisition,acquitted,acted,acting,action,actions,active,activities,activity,acts,actual,ad,...,well,well-being,what,whatever,whatsoever,whenever,where,whereas,whereby,whether,whichever,while,white,whoever,whole,wholly,whom,whose,wish,wishes,withdraw,withdrawal,withdrawn,witness,witnesses,woman,women,words,work,worker,workers,working,works,world,worship,would,writ,writing,writs,written,yang,year,yet,young,youth,yuan,zambia,zimbabwe,zone,zones
component_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
PC0,0.004547,0.004360,-0.003622,-0.000026,-0.001277,-0.001204,0.003576,-0.003921,0.009625,0.001503,-0.040956,-0.020681,-0.027455,0.007871,0.005867,-0.004586,-1.585838e-03,-0.002106,-0.001262,0.039567,0.005799,-0.002040,-0.000838,0.002840,0.014254,-0.004795,0.000185,0.004487,-0.000164,-0.000059,-0.006864,-0.000435,-0.002457,-0.000770,0.012532,0.005673,0.006993,0.006818,0.007413,-0.000614,-0.005042,-0.089392,0.001043,0.010758,0.005878,0.040548,0.025211,-0.000450,0.000529,-0.002677,...,0.060130,0.013205,0.001863,0.002478,0.000262,-0.019553,-0.058397,0.004397,5.014299e-07,-0.026568,-0.004843,-0.014207,0.001145,-0.000303,-0.002598,0.000371,-0.016562,-0.005212,-0.000287,-0.000302,-0.001630,-0.005985,-0.004350,-0.000248,-0.002451,0.006367,0.031117,-0.003621,0.064598,0.008057,0.032505,0.014850,0.010409,0.010662,0.008469,-0.013839,-0.001457,-0.028526,-0.004583,-0.011502,-0.011976,-0.046282,-0.001525,0.011740,1.246459e-02,-0.004729,-0.000319,0.002138,0.005743,0.003393
PC1,0.000818,0.002703,0.002483,0.001074,0.008414,0.001653,0.005403,-0.007031,-0.002352,-0.006668,0.011700,0.009130,-0.052199,0.004870,0.001386,-0.004829,-2.583812e-03,-0.006969,-0.001450,0.008231,0.001623,-0.004640,0.000863,0.003422,-0.007988,0.006610,0.003679,-0.000734,-0.005481,-0.002957,-0.006613,0.000755,0.000078,0.021060,-0.001337,-0.000506,0.000998,0.005391,0.007704,0.004377,0.004562,0.121059,0.020264,0.004472,0.002166,-0.005106,0.004421,0.003312,0.000723,0.000094,...,-0.006729,0.001444,-0.000505,0.004142,0.003387,0.000328,0.054160,0.000043,9.797513e-04,0.041357,0.000900,0.013345,-0.002079,-0.001149,-0.006444,0.002591,0.016265,0.013047,-0.001908,-0.000896,-0.002310,-0.001715,0.000616,0.003105,0.012036,0.001985,-0.002740,0.004625,-0.001177,0.000836,-0.000467,-0.007657,-0.001139,-0.001368,0.003402,0.011071,0.002570,0.018854,0.005728,0.006630,0.008994,-0.076998,-0.001730,0.000571,8.221552e-07,-0.012311,0.004439,0.002248,-0.000328,-0.000804
PC2,-0.002043,-0.004250,-0.006693,0.001043,0.000387,0.000684,-0.002190,0.004625,-0.007156,0.000145,-0.023411,-0.018006,-0.001754,-0.005379,-0.002349,0.000675,-1.474312e-04,-0.000394,-0.000089,-0.020530,-0.002400,0.000323,0.003756,-0.005201,0.006280,-0.006717,-0.003927,0.003946,0.015770,0.004650,0.048711,0.000349,0.000555,-0.010423,-0.002466,-0.000705,-0.006944,-0.014275,-0.011300,-0.003101,-0.002981,-0.034503,0.006135,0.015350,-0.000055,0.026171,0.016007,0.062153,-0.000281,0.001356,...,0.053734,-0.008655,0.004691,-0.005089,-0.002662,-0.009516,-0.041112,-0.003762,-2.731449e-03,-0.018427,-0.003115,-0.007391,-0.001173,-0.000505,-0.000499,-0.002683,-0.007173,0.006674,-0.000857,-0.001016,-0.000589,-0.002995,-0.003644,-0.002269,-0.005845,-0.011516,-0.020224,-0.004303,-0.021619,-0.005187,-0.006099,-0.007431,0.001968,-0.003719,-0.010594,-0.020671,-0.002634,-0.027143,0.000379,-0.005576,-0.004182,0.003497,-0.000524,-0.006837,-5.577974e-03,0.013115,-0.006562,-0.001171,0.005709,0.002006
PC3,0.003396,0.005048,0.004605,0.000487,-0.002822,-0.001382,-0.000449,-0.003691,0.000828,-0.003105,0.053840,0.023551,-0.030553,0.000614,0.000828,0.003287,-6.670267e-04,-0.004052,0.001965,0.002956,0.000979,-0.001645,-0.002263,-0.001271,-0.001551,0.000496,-0.000524,0.003340,0.020269,-0.001880,-0.016156,0.002633,-0.002979,-0.012587,0.002762,0.001331,-0.000888,-0.003880,-0.002944,-0.002210,0.003114,0.093743,-0.006747,0.004166,0.003406,0.014175,0.011857,0.002385,-0.000692,-0.000799,...,-0.013138,0.005520,-0.001869,-0.000882,0.002597,0.017169,-0.007989,-0.000074,-1.719018e-03,-0.001170,-0.001479,0.007125,-0.000546,0.000845,-0.003025,-0.001326,0.006199,0.000410,0.001007,0.001169,-0.000535,-0.003920,-0.003671,-0.000572,-0.004610,0.000986,0.005404,0.000707,0.038473,0.001736,0.007892,0.002263,0.003169,0.002630,0.001960,0.000826,-0.000907,0.028965,-0.003977,0.004866,0.010768,-0.060422,-0.000274,0.003732,3.896440e-03,0.000253,0.000032,-0.000456,-0.001203,-0.000037
PC4,-0.004006,-0.004115,0.000257,0.001428,-0.000440,0.005766,-0.001668,-0.003743,-0.009116,0.002830,-0.003356,0.002580,-0.042151,-0.003921,-0.001315,-0.003750,-1.907445e-03,-0.002133,-0.000968,-0.007557,-0.000084,0.006391,0.002329,-0.000361,-0.011472,0.002315,0.027601,0.000168,-0.007015,0.006650,0.068117,0.000154,-0.006025,-0.012381,0.000760,0.000650,0.001627,0.004443,0.007872,-0.000405,0.002618,0.044170,0.000164,-0.005873,-0.005099,0.003977,-0.016041,-0.019381,0.001066,-0.001234,...,-0.019880,-0.002469,-0.000526,0.001255,-0.000313,0.003700,0.039690,-0.002423,1.235474e-03,0.015266,0.011888,-0.005590,-0.000436,-0.001589,0.000672,0.004056,0.002481,0.006944,-0.000902,-0.000800,-0.002607,0.028098,0.024305,-0.001277,-0.000622,-0.004459,-0.015779,0.001941,-0.030935,-0.001229,0.002264,-0.006079,0.007136,-0.004507,-0.006207,0.012147,-0.000585,0.008183,-0.000686,0.004154,0.010982,0.194970,0.001047,-0.003101,-2.170928e-03,0.006764,0.000955,0.001145,0.004454,0.001761
PC5,-0.001368,-0.008342,-0.007005,-0.002000,0.002749,0.000891,0.008020,0.000496,-0.000538,0.013723,-0.035842,-0.025564,0.001310,0.001315,-0.001549,0.001761,-3.251011e-07,0.001703,0.000729,-0.007446,-0.001989,0.001267,-0.002666,0.003561,0.003728,-0.001041,0.010541,-0.003622,0.004733,-0.000944,-0.004775,0.001150,0.004666,0.039852,-0.009831,-0.004558,0.007786,0.014775,0.013134,0.007834,-0.001302,-0.079461,0.018698,0.005521,-0.007772,-0.030209,-0.020073,0.056805,0.001590,-0.001861,...,-0.037913,-0.007945,0.007118,0.003906,0.004530,-0.007966,0.014209,-0.000738,2.487355e-03,0.005253,0.000232,-0.004314,0.001076,0.002964,0.002942,0.003104,-0.007919,-0.005137,0.001387,0.000226,0.000790,0.007552,0.009648,0.002689,0.012729,-0.000020,-0.024815,0.000933,-0.036126,-0.001358,-0.020164,-0.012831,-0.005047,-0.008062,0.008264,0.005282,0.003199,-0.022626,0.001303,0.018894,0.005652,0.030716,0.000452,-0.008331,-9.545406e-03,0.006693,0.003490,-0.004939,-0.004063,-0.002514
PC6,0.004920,0.007147,0.002142,-0.000170,0.001904,-0.001720,-0.011708,0.000699,0.011277,0.018888,-0.021763,-0.012027,-0.040585,-0.005920,-0.004064,-0.002888,-4.950506e-04,-0.001893,0.000776,-0.031656,-0.004622,-0.004219,0.003042,0.000214,-0.001099,-0.002440,-0.016810,-0.001414,-0.001385,-0.000985,-0.007556,0.005738,-0.005404,-0.017179,-0.006171,-0.002888,0.004037,0.013785,0.004903,-0.003354,-0.000014,0.014893,-0.026326,-0.010083,0.007486,-0.026564,-0.015811,-0.008649,-0.000526,-0.002897,...,-0.032207,-0.002417,-0.004229,-0.002414,-0.001651,-0.008705,-0.042871,-0.001174,-1.768808e-03,-0.026541,0.003000,-0.007289,0.008109,0.001512,-0.002942,-0.002115,-0.003200,0.003531,-0.000490,0.001186,-0.000971,-0.004100,-0.002177,-0.001372,-0.013941,0.007120,-0.014896,0.000650,-0.039771,-0.003758,-0.021413,-0.005673,-0.007373,-0.000961,-0.007483,-0.001245,-0.001712,-0.017126,-0.003713,-0.019820,0.007764,0.009347,0.001531,-0.008251,-7.918662e-03,0.007922,0.010710,0.009493,0.000178,-0.000822
PC7,0.006490,0.005086,-0.008452,-0.000978,0.000331,0.001844,-0.003177,-0.004768,-0.002904,0.017892,0.024242,0.015477,-0.024395,-0.001865,-0.003330,-0.000902,-1.386741e-06,0.002356,0.002136,-0.028105,-0.004258,0.000936,0.003885,-0.003921,0.000073,0.001080,-0.010537,-0.000168,-0.006399,-0.002093,-0.002527,0.000630,-0.000960,0.002599,-0.004452,-0.000738,-0.003306,-0.009166,-0.008605,-0.000701,-0.006481,-0.107799,-0.003327,-0.004788,-0.003568,-0.018771,-0.016375,0.013446,-0.000585,0.000691,...,-0.010665,0.001771,-0.001821,-0.001783,-0.000310,0.002151,-0.029371,0.003199,-1.786539e-03,-0.020465,-0.001807,-0.000612,0.005871,0.000085,0.001593,-0.002487,-0.007563,-0.017600,-0.000019,-0.000144,-0.000792,0.001796,0.002390,0.003374,-0.001840,-0.007401,-0.028815,0.004711,-0.057766,-0.006837,-0.017964,-0.011071,-0.004431,0.006190,0.001027,-0.001614,0.001728,0.015710,-0.000671,0.002581,0.004791,-0.021356,-0.000161,-0.005431,-6.824516e-03,0.002847,-0.003208,0.001809,0.002751,-0.000217
PC8,0.000539,0.003806,-0.004266,-0.003044,0.002379,-0.000197,-0.008095,-0.009051,-0.003912,0.005999,0.005772,-0.002680,-0.016930,0.002479,0.006401,-0.005963,-2.456517e-03,-0.005477,-0.001744,0.020812,0.005322,0.001938,-0.000702,-0.001506,0.012961,-0.004447,0.008662,-0.001365,0.000453,0.003225,0.034117,-0.005308,-0.000634,-0.008669,0.002052,-0.000479,-0.000456,-0.001905,-0.002630,-0.002874,-0.006098,-0.108912,-0.020163,-0.005822,-0.004255,0.005645,0.020969,-0.044289,-0.001696,0.000733,...,-0.006511,0.000204,-0.003924,-0.001267,-0.000235,-0.007356,-0.048711,-0.002844,-3.671023e-03,-0.032454,0.008394,-0.002061,0.002877,0.000223,-0.015235,-0.001552,-0.006084,-0.007765,-0.000172,-0.000655,-0.002582,0.012971,0.014145,-0.000974,-0.007319,0.007400,0.020808,-0.003826,0.065175,0.007639,0.014196,0.016278,0.002108,-0.005174,0.004598,-0.008982,-0.001393,-0.006238,-0.002515,-0.003850,-0.000849,0.153926,0.000492,0.006995,8.147139e-03,-0.000046,-0.004298,-0.005800,-0.005881,-0.001962
PC9,-0.000997,-0.004755,-0.004264,-0.000801,-0.000008,0.000748,0.005383,0.001423,0.000906,-0.000739,0.019315,0.010811,-0.021126,-0.000753,-0.000939,-0.005188,-1.577932e-03,-0.004369,-0.000587,0.008910,-0.000149,-0.001896,-0.001825,0.003889,0.002333,0.001252,0.000687,0.001307,0.009275,-0.001277,-0.004007,-0.003880,-0.000474,0.011790,-0.006036,-0.003916,0.007907,0.015186,0.015155,0.003301,-0.002989,-0.079024,0.002493,0.008401,-0.007026,-0.001576,0.002439,0.039174,-0.000791,-0.000623,...,-0.007617,-0.010713,0.001793,-0.000183,0.000389,-0.001676,-0.003056,-0.002286,1.362360e-03,0.000137,-0.003347,-0.008586,-0.001135,-0.000749,-0.002581,0.001803,0.000771,0.005258,-0.000903,0.000157,-0.001325,-0.003417,-0.002009,0.001040,0.005048,0.000609,-0.014382,-0.001047,-0.008115,-0.001808,-0.018521,-0.010992,-0.003222,-0.011286,0.005401,0.011358,0.002367,0.015134,-0.000894,0.007361,-0.004110,-0.092451,-0.000496,-0.009604,-9.081081e-03,0.000694,0.004765,0.003318,-0.002144,-0.001677

## PCA DCM

This section inspects the PCA document-component matrix that places documents in the PCA component space.

In [7]:
PCA_DCM = inspect_table(
    section='PCA DCM',
    box_url='https://virginia.box.com/shared/static/uwq75d5c2d3e1dcvlrne11sjucuyctko',
    local_path='pca_dcm.parquet',
    file_format='parquet'
)

Section: PCA DCM
Box URL: https://virginia.box.com/shared/static/uwq75d5c2d3e1dcvlrne11sjucuyctko
Local file: pca_dcm.parquet
Loaded from: Box download
Format: parquet
Shape: 33,726 rows x 3,006 columns
Number of observations: 33,726
Column names:
PC0, PC1, PC2, PC3, PC4, PC5, PC6, PC7, PC8, PC9, PC10, PC11, PC12, PC13, PC14, PC15, PC16, PC17,
PC18, PC19, PC20, PC21, PC22, PC23, PC24, PC25, PC26, PC27, PC28, PC29, PC30, PC31, PC32, PC33,
PC34, PC35, PC36, PC37, PC38, PC39, PC40, PC41, PC42, PC43, PC44, PC45, PC46, PC47, PC48, PC49,
PC50, PC51, PC52, PC53, PC54, PC55, PC56, PC57, PC58, PC59, PC60, PC61, PC62, PC63, PC64, PC65,
PC66, PC67, PC68, PC69, PC70, PC71, PC72, PC73, PC74, PC75, PC76, PC77, PC78, PC79, PC80, PC81,
PC82, PC83, PC84, PC85, PC86, PC87, PC88, PC89, PC90, PC91, PC92, PC93, PC94, PC95, PC96, PC97,
PC98, PC99, PC100, PC101, PC102, PC103, PC104, PC105, PC106, PC107, PC108, PC109, PC110, PC111,
PC112, PC113, PC114, PC115, PC116, PC117, PC118, PC119, PC120, PC121, PC122, PC123, PC124, PC125,
PC126, PC127, PC128, PC129, PC130, PC131, PC132, PC133, PC134, PC135, PC136, PC137, PC138, PC139,
PC140, PC141, PC142, PC143, PC144, PC145, PC146, PC147, PC148, PC149, PC150, PC151, PC152, PC153,
PC154, PC155, PC156, PC157, PC158, PC159, PC160, PC161, PC162, PC163, PC164, PC165, PC166, PC167,
PC168, PC169, PC170, PC171, PC172, PC173, PC174, PC175, PC176, PC177, PC178, PC179, PC180, PC181,
PC182, PC183, PC184, PC185, PC186, PC187, PC188, PC189, PC190, PC191, PC192, PC193, PC194, PC195,
PC196, PC197, PC198, PC199, PC200, PC201, PC202, PC203, PC204, PC205, PC206, PC207, PC208, PC209,
PC210, PC211, PC212, PC213, PC214, PC215, PC216, PC217, PC218, PC219, PC220, PC221, PC222, PC223,
PC224, PC225, PC226, PC227, PC228, PC229, PC230, PC231, PC232, PC233, PC234, PC235, PC236, PC237,
PC238, PC239, PC240, PC241, PC242, PC243, PC244, PC245, PC246, PC247, PC248, PC249, PC250, PC251,
PC252, PC253, PC254, PC255, PC256, PC257, PC258, PC259, PC260, PC261, PC262, PC263, PC264, PC265,
PC266, PC267, PC268, PC269, PC270, PC271, PC272, PC273, PC274, PC275, PC276, PC277, PC278, PC279,
PC280, PC281, PC282, PC283, PC284, PC285, PC286, PC287, PC288, PC289, PC290, PC291, PC292, PC293,
PC294, PC295, PC296, PC297, PC298, PC299, PC300, PC301, PC302, PC303, PC304, PC305, PC306, PC307,
PC308, PC309, PC310, PC311, PC312, PC313, PC314, PC315, PC316, PC317, PC318, PC319, PC320, PC321,
PC322, PC323, PC324, PC325, PC326, PC327, PC328, PC329, PC330, PC331, PC332, PC333, PC334, PC335,
PC336, PC337, PC338, PC339, PC340, PC341, PC342, PC343, PC344, PC345, PC346, PC347, PC348, PC349,
PC350, PC351, PC352, PC353, PC354, PC355, PC356, PC357, PC358, PC359, PC360, PC361, PC362, PC363,
PC364, PC365, PC366, PC367, PC368, PC369, PC370, PC371, PC372, PC373, PC374, PC375, PC376, PC377,
PC378, PC379, PC380, PC381, PC382, PC383, PC384, PC385, PC386, PC387, PC388, PC389, PC390, PC391,
PC392, PC393, PC394, PC395, PC396, PC397, PC398, PC399, PC400, PC401, PC402, PC403, PC404, PC405,
PC406, PC407, PC408, PC409, PC410, PC411, PC412, PC413, PC414, PC415, PC416, PC417, PC418, PC419,
PC420, PC421, PC422, PC423, PC424, PC425, PC426, PC427, PC428, PC429, PC430, PC431, PC432, PC433,
PC434, PC435, PC436, PC437, PC438, PC439, PC440, PC441, PC442, PC443, PC444, PC445, PC446, PC447,
PC448, PC449, PC450, PC451, PC452, PC453, PC454, PC455, PC456, PC457, PC458, PC459, PC460, PC461,
PC462, PC463, PC464, PC465, PC466, PC467, PC468, PC469, PC470, PC471, PC472, PC473, PC474, PC475,
PC476, PC477, PC478, PC479, PC480, PC481, PC482, PC483, PC484, PC485, PC486, PC487, PC488, PC489,
PC490, PC491, PC492, PC493, PC494, PC495, PC496, PC497, PC498, PC499, PC500, PC501, PC502, PC503,
PC504, PC505, PC506, PC507, PC508, PC509, PC510, PC511, PC512, PC513, PC514, PC515, PC516, PC517,
PC518, PC519, PC520, PC521, PC522, PC523, PC524, PC525, PC526, PC527, PC528, PC529, PC530, PC531,
PC532, PC533, PC534, PC535, PC536, PC537, PC538, PC539, PC540, PC541, PC542, PC543, PC544, PC545,
PC546, PC547, PC548, PC549, PC550, PC551, PC552, PC553, PC554, PC555, PC556, PC557, PC558, PC559,
PC560, PC561, PC562, PC563, PC564, PC565, PC566, PC567, PC568, PC569, PC570, PC571, PC572, PC573,
PC574, PC575, PC576, PC577, PC578, PC579, PC580, PC581, PC582, PC583, PC584, PC585, PC586, PC587,
PC588, PC589, PC590, PC591, PC592, PC593, PC594, PC595, PC596, PC597, PC598, PC599, PC600, PC601,
PC602, PC603, PC604, PC605, PC606, PC607, PC608, PC609, PC610, PC611, PC612, PC613, PC614, PC615,
PC616, PC617, PC618, PC619, PC620, PC621, PC622, PC623, PC624, PC625, PC626, PC627, PC628, PC629,
PC630, PC631, PC632, PC633, PC634, PC635, PC636, PC637, PC638, PC639, PC640, PC641, PC642, PC643,
PC644, PC645, PC646, PC647, PC648, PC649, PC650, PC651, PC652, PC653, PC654, PC655, PC656, PC657,
PC658, PC659, PC660, PC661, PC662, PC663, PC664, PC665, PC666, PC667, PC668, PC669, PC670, PC671,
PC672, PC673, PC674, PC675, PC676, PC677, PC678, PC679, PC680, PC681, PC682, PC683, PC684, PC685,
PC686, PC687, PC688, PC689, PC690, PC691, PC692, PC693, PC694, PC695, PC696, PC697, PC698, PC699,
PC700, PC701, PC702, PC703, PC704, PC705, PC706, PC707, PC708, PC709, PC710, PC711, PC712, PC713,
PC714, PC715, PC716, PC717, PC718, PC719, PC720, PC721, PC722, PC723, PC724, PC725, PC726, PC727,
PC728, PC729, PC730, PC731, PC732, PC733, PC734, PC735, PC736, PC737, PC738, PC739, PC740, PC741,
PC742, PC743, PC744, PC745, PC746, PC747, PC748, PC749, PC750, PC751, PC752, PC753, PC754, PC755,
PC756, PC757, PC758, PC759, PC760, PC761, PC762, PC763, PC764, PC765, PC766, PC767, PC768, PC769,
PC770, PC771, PC772, PC773, PC774, PC775, PC776, PC777, PC778, PC779, PC780, PC781, PC782, PC783,
PC784, PC785, PC786, PC787, PC788, PC789, PC790, PC791, PC792, PC793, PC794, PC795, PC796, PC797,
PC798, PC799, PC800, PC801, PC802, PC803, PC804, PC805, PC806, PC807, PC808, PC809, PC810, PC811,
PC812, PC813, PC814, PC815, PC816, PC817, PC818, PC819, PC820, PC821, PC822, PC823, PC824, PC825,
PC826, PC827, PC828, PC829, PC830, PC831, PC832, PC833, PC834, PC835, PC836, PC837, PC838, PC839,
PC840, PC841, PC842, PC843, PC844, PC845, PC846, PC847, PC848, PC849, PC850, PC851, PC852, PC853,
PC854, PC855, PC856, PC857, PC858, PC859, PC860, PC861, PC862, PC863, PC864, PC865, PC866, PC867,
PC868, PC869, PC870, PC871, PC872, PC873, PC874, PC875, PC876, PC877, PC878, PC879, PC880, PC881,
PC882, PC883, PC884, PC885, PC886, PC887, PC888, PC889, PC890, PC891, PC892, PC893, PC894, PC895,
PC896, PC897, PC898, PC899, PC900, PC901, PC902, PC903, PC904, PC905, PC906, PC907, PC908, PC909,
PC910, PC911, PC912, PC913, PC914, PC915, PC916, PC917, PC918, PC919, PC920, PC921, PC922, PC923,
PC924, PC925, PC926, PC927, PC928, PC929, PC930, PC931, PC932, PC933, PC934, PC935, PC936, PC937,
PC938, PC939, PC940, PC941, PC942, PC943, PC944, PC945, PC946, PC947, PC948, PC949, PC950, PC951,
PC952, PC953, PC954, PC955, PC956, PC957, PC958, PC959, PC960, PC961, PC962, PC963, PC964, PC965,
PC966, PC967, PC968, PC969, PC970, PC971, PC972, PC973, PC974, PC975, PC976, PC977, PC978, PC979,
PC980, PC981, PC982, PC983, PC984, PC985, PC986, PC987, PC988, PC989, PC990, PC991, PC992, PC993,
PC994, PC995, PC996, PC997, PC998, PC999, PC1000, PC1001, PC1002, PC1003, PC1004, PC1005, PC1006,
PC1007, PC1008, PC1009, PC1010, PC1011, PC1012, PC1013, PC1014, PC1015, PC1016, PC1017, PC1018,
PC1019, PC1020, PC1021, PC1022, PC1023, PC1024, PC1025, PC1026, PC1027, PC1028, PC1029, PC1030,
PC1031, PC1032, PC1033, PC1034, PC1035, PC1036, PC1037, PC1038, PC1039, PC1040, PC1041, PC1042,
PC1043, PC1044, PC1045, PC1046, PC1047, PC1048, PC1049, PC1050, PC1051, PC1052, PC1053, PC1054,
PC1055, PC1056, PC1057, PC1058, PC1059, PC1060, PC1061, PC1062, PC1063, PC1064, PC1065, PC1066,
PC1067, PC1068, PC1069, PC1070, PC1071, PC1072, PC1073, PC1074, PC1075, PC1076, PC1077, PC1078,
PC1079, PC1080, PC1081, PC1082, PC1083, PC1084, PC1085, PC1086, PC1087, PC1088, PC1089, PC1090,
PC1091, PC1092, PC1093, PC1094, PC1095, PC1096, PC1097, PC1098, PC1099, PC1100, PC1101, PC1102,
PC1103, PC1104, PC1105, PC1106, PC1107, PC1108, PC1109, PC1110, PC1111, PC1112, PC1113, PC1114,
PC1115, PC1116, PC1117, PC1118, PC1119, PC1120, PC1121, PC1122, PC1123, PC1124, PC1125, PC1126,
PC1127, PC1128, PC1129, PC1130, PC1131, PC1132, PC1133, PC1134, PC1135, PC1136, PC1137, PC1138,
PC1139, PC1140, PC1141, PC1142, PC1143, PC1144, PC1145, PC1146, PC1147, PC1148, PC1149, PC1150,
PC1151, PC1152, PC1153, PC1154, PC1155, PC1156, PC1157, PC1158, PC1159, PC1160, PC1161, PC1162,
PC1163, PC1164, PC1165, PC1166, PC1167, PC1168, PC1169, PC1170, PC1171, PC1172, PC1173, PC1174,
PC1175, PC1176, PC1177, PC1178, PC1179, PC1180, PC1181, PC1182, PC1183, PC1184, PC1185, PC1186,
PC1187, PC1188, PC1189, PC1190, PC1191, PC1192, PC1193, PC1194, PC1195, PC1196, PC1197, PC1198,
PC1199, PC1200, PC1201, PC1202, PC1203, PC1204, PC1205, PC1206, PC1207, PC1208, PC1209, PC1210,
PC1211, PC1212, PC1213, PC1214, PC1215, PC1216, PC1217, PC1218, PC1219, PC1220, PC1221, PC1222,
PC1223, PC1224, PC1225, PC1226, PC1227, PC1228, PC1229, PC1230, PC1231, PC1232, PC1233, PC1234,
PC1235, PC1236, PC1237, PC1238, PC1239, PC1240, PC1241, PC1242, PC1243, PC1244, PC1245, PC1246,
PC1247, PC1248, PC1249, PC1250, PC1251, PC1252, PC1253, PC1254, PC1255, PC1256, PC1257, PC1258,
PC1259, PC1260, PC1261, PC1262, PC1263, PC1264, PC1265, PC1266, PC1267, PC1268, PC1269, PC1270,
PC1271, PC1272, PC1273, PC1274, PC1275, PC1276, PC1277, PC1278, PC1279, PC1280, PC1281, PC1282,
PC1283, PC1284, PC1285, PC1286, PC1287, PC1288, PC1289, PC1290, PC1291, PC1292, PC1293, PC1294,
PC1295, PC1296, PC1297, PC1298, PC1299, PC1300, PC1301, PC1302, PC1303, PC1304, PC1305, PC1306,
PC1307, PC1308, PC1309, PC1310, PC1311, PC1312, PC1313, PC1314, PC1315, PC1316, PC1317, PC1318,
PC1319, PC1320, PC1321, PC1322, PC1323, PC1324, PC1325, PC1326, PC1327, PC1328, PC1329, PC1330,
PC1331, PC1332, PC1333, PC1334, PC1335, PC1336, PC1337, PC1338, PC1339, PC1340, PC1341, PC1342,
PC1343, PC1344, PC1345, PC1346, PC1347, PC1348, PC1349, PC1350, PC1351, PC1352, PC1353, PC1354,
PC1355, PC1356, PC1357, PC1358, PC1359, PC1360, PC1361, PC1362, PC1363, PC1364, PC1365, PC1366,
PC1367, PC1368, PC1369, PC1370, PC1371, PC1372, PC1373, PC1374, PC1375, PC1376, PC1377, PC1378,
PC1379, PC1380, PC1381, PC1382, PC1383, PC1384, PC1385, PC1386, PC1387, PC1388, PC1389, PC1390,
PC1391, PC1392, PC1393, PC1394, PC1395, PC1396, PC1397, PC1398, PC1399, PC1400, PC1401, PC1402,
PC1403, PC1404, PC1405, PC1406, PC1407, PC1408, PC1409, PC1410, PC1411, PC1412, PC1413, PC1414,
PC1415, PC1416, PC1417, PC1418, PC1419, PC1420, PC1421, PC1422, PC1423, PC1424, PC1425, PC1426,
PC1427, PC1428, PC1429, PC1430, PC1431, PC1432, PC1433, PC1434, PC1435, PC1436, PC1437, PC1438,
PC1439, PC1440, PC1441, PC1442, PC1443, PC1444, PC1445, PC1446, PC1447, PC1448, PC1449, PC1450,
PC1451, PC1452, PC1453, PC1454, PC1455, PC1456, PC1457, PC1458, PC1459, PC1460, PC1461, PC1462,
PC1463, PC1464, PC1465, PC1466, PC1467, PC1468, PC1469, PC1470, PC1471, PC1472, PC1473, PC1474,
PC1475, PC1476, PC1477, PC1478, PC1479, PC1480, PC1481, PC1482, PC1483, PC1484, PC1485, PC1486,
PC1487, PC1488, PC1489, PC1490, PC1491, PC1492, PC1493, PC1494, PC1495, PC1496, PC1497, PC1498,
PC1499, PC1500, PC1501, PC1502, PC1503, PC1504, PC1505, PC1506, PC1507, PC1508, PC1509, PC1510,
PC1511, PC1512, PC1513, PC1514, PC1515, PC1516, PC1517, PC1518, PC1519, PC1520, PC1521, PC1522,
PC1523, PC1524, PC1525, PC1526, PC1527, PC1528, PC1529, PC1530, PC1531, PC1532, PC1533, PC1534,
PC1535, PC1536, PC1537, PC1538, PC1539, PC1540, PC1541, PC1542, PC1543, PC1544, PC1545, PC1546,
PC1547, PC1548, PC1549, PC1550, PC1551, PC1552, PC1553, PC1554, PC1555, PC1556, PC1557, PC1558,
PC1559, PC1560, PC1561, PC1562, PC1563, PC1564, PC1565, PC1566, PC1567, PC1568, PC1569, PC1570,
PC1571, PC1572, PC1573, PC1574, PC1575, PC1576, PC1577, PC1578, PC1579, PC1580, PC1581, PC1582,
PC1583, PC1584, PC1585, PC1586, PC1587, PC1588, PC1589, PC1590, PC1591, PC1592, PC1593, PC1594,
PC1595, PC1596, PC1597, PC1598, PC1599, PC1600, PC1601, PC1602, PC1603, PC1604, PC1605, PC1606,
PC1607, PC1608, PC1609, PC1610, PC1611, PC1612, PC1613, PC1614, PC1615, PC1616, PC1617, PC1618,
PC1619, PC1620, PC1621, PC1622, PC1623, PC1624, PC1625, PC1626, PC1627, PC1628, PC1629, PC1630,
PC1631, PC1632, PC1633, PC1634, PC1635, PC1636, PC1637, PC1638, PC1639, PC1640, PC1641, PC1642,
PC1643, PC1644, PC1645, PC1646, PC1647, PC1648, PC1649, PC1650, PC1651, PC1652, PC1653, PC1654,
PC1655, PC1656, PC1657, PC1658, PC1659, PC1660, PC1661, PC1662, PC1663, PC1664, PC1665, PC1666,
PC1667, PC1668, PC1669, PC1670, PC1671, PC1672, PC1673, PC1674, PC1675, PC1676, PC1677, PC1678,
PC1679, PC1680, PC1681, PC1682, PC1683, PC1684, PC1685, PC1686, PC1687, PC1688, PC1689, PC1690,
PC1691, PC1692, PC1693, PC1694, PC1695, PC1696, PC1697, PC1698, PC1699, PC1700, PC1701, PC1702,
PC1703, PC1704, PC1705, PC1706, PC1707, PC1708, PC1709, PC1710, PC1711, PC1712, PC1713, PC1714,
PC1715, PC1716, PC1717, PC1718, PC1719, PC1720, PC1721, PC1722, PC1723, PC1724, PC1725, PC1726,
PC1727, PC1728, PC1729, PC1730, PC1731, PC1732, PC1733, PC1734, PC1735, PC1736, PC1737, PC1738,
PC1739, PC1740, PC1741, PC1742, PC1743, PC1744, PC1745, PC1746, PC1747, PC1748, PC1749, PC1750,
PC1751, PC1752, PC1753, PC1754, PC1755, PC1756, PC1757, PC1758, PC1759, PC1760, PC1761, PC1762,
PC1763, PC1764, PC1765, PC1766, PC1767, PC1768, PC1769, PC1770, PC1771, PC1772, PC1773, PC1774,
PC1775, PC1776, PC1777, PC1778, PC1779, PC1780, PC1781, PC1782, PC1783, PC1784, PC1785, PC1786,
PC1787, PC1788, PC1789, PC1790, PC1791, PC1792, PC1793, PC1794, PC1795, PC1796, PC1797, PC1798,
PC1799, PC1800, PC1801, PC1802, PC1803, PC1804, PC1805, PC1806, PC1807, PC1808, PC1809, PC1810,
PC1811, PC1812, PC1813, PC1814, PC1815, PC1816, PC1817, PC1818, PC1819, PC1820, PC1821, PC1822,
PC1823, PC1824, PC1825, PC1826, PC1827, PC1828, PC1829, PC1830, PC1831, PC1832, PC1833, PC1834,
PC1835, PC1836, PC1837, PC1838, PC1839, PC1840, PC1841, PC1842, PC1843, PC1844, PC1845, PC1846,
PC1847, PC1848, PC1849, PC1850, PC1851, PC1852, PC1853, PC1854, PC1855, PC1856, PC1857, PC1858,
PC1859, PC1860, PC1861, PC1862, PC1863, PC1864, PC1865, PC1866, PC1867, PC1868, PC1869, PC1870,
PC1871, PC1872, PC1873, PC1874, PC1875, PC1876, PC1877, PC1878, PC1879, PC1880, PC1881, PC1882,
PC1883, PC1884, PC1885, PC1886, PC1887, PC1888, PC1889, PC1890, PC1891, PC1892, PC1893, PC1894,
PC1895, PC1896, PC1897, PC1898, PC1899, PC1900, PC1901, PC1902, PC1903, PC1904, PC1905, PC1906,
PC1907, PC1908, PC1909, PC1910, PC1911, PC1912, PC1913, PC1914, PC1915, PC1916, PC1917, PC1918,
PC1919, PC1920, PC1921, PC1922, PC1923, PC1924, PC1925, PC1926, PC1927, PC1928, PC1929, PC1930,
PC1931, PC1932, PC1933, PC1934, PC1935, PC1936, PC1937, PC1938, PC1939, PC1940, PC1941, PC1942,
PC1943, PC1944, PC1945, PC1946, PC1947, PC1948, PC1949, PC1950, PC1951, PC1952, PC1953, PC1954,
PC1955, PC1956, PC1957, PC1958, PC1959, PC1960, PC1961, PC1962, PC1963, PC1964, PC1965, PC1966,
PC1967, PC1968, PC1969, PC1970, PC1971, PC1972, PC1973, PC1974, PC1975, PC1976, PC1977, PC1978,
PC1979, PC1980, PC1981, PC1982, PC1983, PC1984, PC1985, PC1986, PC1987, PC1988, PC1989, PC1990,
PC1991, PC1992, PC1993, PC1994, PC1995, PC1996, PC1997, PC1998, PC1999, PC2000, PC2001, PC2002,
PC2003, PC2004, PC2005, PC2006, PC2007, PC2008, PC2009, PC2010, PC2011, PC2012, PC2013, PC2014,
PC2015, PC2016, PC2017, PC2018, PC2019, PC2020, PC2021, PC2022, PC2023, PC2024, PC2025, PC2026,
PC2027, PC2028, PC2029, PC2030, PC2031, PC2032, PC2033, PC2034, PC2035, PC2036, PC2037, PC2038,
PC2039, PC2040, PC2041, PC2042, PC2043, PC2044, PC2045, PC2046, PC2047, PC2048, PC2049, PC2050,
PC2051, PC2052, PC2053, PC2054, PC2055, PC2056, PC2057, PC2058, PC2059, PC2060, PC2061, PC2062,
PC2063, PC2064, PC2065, PC2066, PC2067, PC2068, PC2069, PC2070, PC2071, PC2072, PC2073, PC2074,
PC2075, PC2076, PC2077, PC2078, PC2079, PC2080, PC2081, PC2082, PC2083, PC2084, PC2085, PC2086,
PC2087, PC2088, PC2089, PC2090, PC2091, PC2092, PC2093, PC2094, PC2095, PC2096, PC2097, PC2098,
PC2099, PC2100, PC2101, PC2102, PC2103, PC2104, PC2105, PC2106, PC2107, PC2108, PC2109, PC2110,
PC2111, PC2112, PC2113, PC2114, PC2115, PC2116, PC2117, PC2118, PC2119, PC2120, PC2121, PC2122,
PC2123, PC2124, PC2125, PC2126, PC2127, PC2128, PC2129, PC2130, PC2131, PC2132, PC2133, PC2134,
PC2135, PC2136, PC2137, PC2138, PC2139, PC2140, PC2141, PC2142, PC2143, PC2144, PC2145, PC2146,
PC2147, PC2148, PC2149, PC2150, PC2151, PC2152, PC2153, PC2154, PC2155, PC2156, PC2157, PC2158,
PC2159, PC2160, PC2161, PC2162, PC2163, PC2164, PC2165, PC2166, PC2167, PC2168, PC2169, PC2170,
PC2171, PC2172, PC2173, PC2174, PC2175, PC2176, PC2177, PC2178, PC2179, PC2180, PC2181, PC2182,
PC2183, PC2184, PC2185, PC2186, PC2187, PC2188, PC2189, PC2190, PC2191, PC2192, PC2193, PC2194,
PC2195, PC2196, PC2197, PC2198, PC2199, PC2200, PC2201, PC2202, PC2203, PC2204, PC2205, PC2206,
PC2207, PC2208, PC2209, PC2210, PC2211, PC2212, PC2213, PC2214, PC2215, PC2216, PC2217, PC2218,
PC2219, PC2220, PC2221, PC2222, PC2223, PC2224, PC2225, PC2226, PC2227, PC2228, PC2229, PC2230,
PC2231, PC2232, PC2233, PC2234, PC2235, PC2236, PC2237, PC2238, PC2239, PC2240, PC2241, PC2242,
PC2243, PC2244, PC2245, PC2246, PC2247, PC2248, PC2249, PC2250, PC2251, PC2252, PC2253, PC2254,
PC2255, PC2256, PC2257, PC2258, PC2259, PC2260, PC2261, PC2262, PC2263, PC2264, PC2265, PC2266,
PC2267, PC2268, PC2269, PC2270, PC2271, PC2272, PC2273, PC2274, PC2275, PC2276, PC2277, PC2278,
PC2279, PC2280, PC2281, PC2282, PC2283, PC2284, PC2285, PC2286, PC2287, PC2288, PC2289, PC2290,
PC2291, PC2292, PC2293, PC2294, PC2295, PC2296, PC2297, PC2298, PC2299, PC2300, PC2301, PC2302,
PC2303, PC2304, PC2305, PC2306, PC2307, PC2308, PC2309, PC2310, PC2311, PC2312, PC2313, PC2314,
PC2315, PC2316, PC2317, PC2318, PC2319, PC2320, PC2321, PC2322, PC2323, PC2324, PC2325, PC2326,
PC2327, PC2328, PC2329, PC2330, PC2331, PC2332, PC2333, PC2334, PC2335, PC2336, PC2337, PC2338,
PC2339, PC2340, PC2341, PC2342, PC2343, PC2344, PC2345, PC2346, PC2347, PC2348, PC2349, PC2350,
PC2351, PC2352, PC2353, PC2354, PC2355, PC2356, PC2357, PC2358, PC2359, PC2360, PC2361, PC2362,
PC2363, PC2364, PC2365, PC2366, PC2367, PC2368, PC2369, PC2370, PC2371, PC2372, PC2373, PC2374,
PC2375, PC2376, PC2377, PC2378, PC2379, PC2380, PC2381, PC2382, PC2383, PC2384, PC2385, PC2386,
PC2387, PC2388, PC2389, PC2390, PC2391, PC2392, PC2393, PC2394, PC2395, PC2396, PC2397, PC2398,
PC2399, PC2400, PC2401, PC2402, PC2403, PC2404, PC2405, PC2406, PC2407, PC2408, PC2409, PC2410,
PC2411, PC2412, PC2413, PC2414, PC2415, PC2416, PC2417, PC2418, PC2419, PC2420, PC2421, PC2422,
PC2423, PC2424, PC2425, PC2426, PC2427, PC2428, PC2429, PC2430, PC2431, PC2432, PC2433, PC2434,
PC2435, PC2436, PC2437, PC2438, PC2439, PC2440, PC2441, PC2442, PC2443, PC2444, PC2445, PC2446,
PC2447, PC2448, PC2449, PC2450, PC2451, PC2452, PC2453, PC2454, PC2455, PC2456, PC2457, PC2458,
PC2459, PC2460, PC2461, PC2462, PC2463, PC2464, PC2465, PC2466, PC2467, PC2468, PC2469, PC2470,
PC2471, PC2472, PC2473, PC2474, PC2475, PC2476, PC2477, PC2478, PC2479, PC2480, PC2481, PC2482,
PC2483, PC2484, PC2485, PC2486, PC2487, PC2488, PC2489, PC2490, PC2491, PC2492, PC2493, PC2494,
PC2495, PC2496, PC2497, PC2498, PC2499, PC2500, PC2501, PC2502, PC2503, PC2504, PC2505, PC2506,
PC2507, PC2508, PC2509, PC2510, PC2511, PC2512, PC2513, PC2514, PC2515, PC2516, PC2517, PC2518,
PC2519, PC2520, PC2521, PC2522, PC2523, PC2524, PC2525, PC2526, PC2527, PC2528, PC2529, PC2530,
PC2531, PC2532, PC2533, PC2534, PC2535, PC2536, PC2537, PC2538, PC2539, PC2540, PC2541, PC2542,
PC2543, PC2544, PC2545, PC2546, PC2547, PC2548, PC2549, PC2550, PC2551, PC2552, PC2553, PC2554,
PC2555, PC2556, PC2557, PC2558, PC2559, PC2560, PC2561, PC2562, PC2563, PC2564, PC2565, PC2566,
PC2567, PC2568, PC2569, PC2570, PC2571, PC2572, PC2573, PC2574, PC2575, PC2576, PC2577, PC2578,
PC2579, PC2580, PC2581, PC2582, PC2583, PC2584, PC2585, PC2586, PC2587, PC2588, PC2589, PC2590,
PC2591, PC2592, PC2593, PC2594, PC2595, PC2596, PC2597, PC2598, PC2599, PC2600, PC2601, PC2602,

                            PC0       PC1       PC2       PC3       PC4  \
country_id  article_n
Afghanistan 1          0.210665 -0.027579 -0.056931  0.023060 -0.075607
            2          0.028282 -0.002873  0.018675 -0.003923 -0.010452
            3          0.081144  0.012865 -0.067011  0.025213 -0.045069
            4          0.036248 -0.001025 -0.028926  0.009372 -0.012973
            5          0.064454 -0.020695 -0.062457  0.002191 -0.065924
            6          0.106634  0.009979  0.003753  0.048305 -0.050854
            7          0.198942 -0.010473 -0.041032  0.032957 -0.034989
            8          0.100001 -0.029839  0.017749 -0.005214 -0.015696
            9          0.115856 -0.013223  0.018342  0.024399 -0.024211
            10         0.138556  0.002136  0.007901  0.008888  0.046323

                            PC5       PC6       PC7       PC8       PC9  \
country_id  article_n
Afghanistan 1         -0.099074 -0.023701  0.062940 -0.073178 -0.141306
            2         -0.003854  0.049081  0.049474  0.020311  0.003358
            3          0.032218  0.000346  0.018002  0.048850  0.023367
            4          0.031950  0.017045  0.030386  0.023870  0.012059
            5          0.028862  0.157077  0.003884 -0.019737  0.048431
            6         -0.033930  0.099515  0.108876 -0.089064 -0.085167
            7         -0.087302 -0.055771  0.011489 -0.010324 -0.103635
            8          0.017471  0.015903  0.095749 -0.129115 -0.069369
            9         -0.029182  0.046669  0.043469 -0.059914 -0.043894
            10        -0.016826 -0.059387 -0.019701  0.017269 -0.001812

                           PC10      PC11      PC12      PC13      PC14  \
country_id  article_n
Afghanistan 1          0.093413  0.013744  0.024961  0.000319  0.124925
            2          0.033283 -0.033117 -0.026787  0.046269 -0.009705
            3          0.053603 -0.086619 -0.037494  0.120289 -0.052639
            4          0.033630 -0.048057 -0.033433  0.056139 -0.041449
            5         -0.007002  0.149809 -0.015750 -0.007414  0.034788
            6         -0.054336  0.042688  0.105186  0.005055  0.003456
            7          0.051581  0.023584 -0.030923 -0.034464  0.074286
            8          0.020443  0.041965 -0.078163 -0.056241  0.047418
            9         -0.018288  0.050480  0.003171 -0.026829  0.016663
            10        -0.033957  0.014352  0.011285 -0.096444 -0.008260

                           PC15      PC16      PC17      PC18      PC19  \
country_id  article_n
Afghanistan 1         -0.006486  0.027834 -0.019398 -0.042186  0.047467
            2         -0.015735 -0.032110 -0.022591 -0.018906 -0.012593
            3          0.023280  0.067201  0.078033  0.025923  0.033825
            4         -0.000750  0.019390  0.034420  0.003067  0.017207
            5          0.131022 -0.041892 -0.042411 -0.065569  0.047492
            6          0.013805  0.024862  0.007895 -0.036087  0.017812
            7         -0.007688  0.017449 -0.029438 -0.035063 -0.014334
            8         -0.064406  0.171728 -0.131972  0.027852 -0.014438
            9          0.003008  0.025154 -0.021065 -0.013358  0.021443
            10        -0.054962 -0.105535 -0.071720  0.052105  0.107470

                           PC20      PC21      PC22      PC23      PC24  \
country_id  article_n
Afghanistan 1          0.010549 -0.075694 -0.021360  0.020613 -0.005342
            2         -0.030071 -0.009179 -0.012634 -0.036277 -0.004964
            3         -0.009032  0.020494  0.075700 -0.033219 -0.025731
            4         -0.005436 -0.002266  0.036569 -0.033897 -0.009490
            5         -0.027722 -0.032570  0.025546 -0.030391 -0.060594
            6          0.027970 -0.061962 -0.044338 -0.008680  0.011984
            7          0.037990 -0.055066 -0.092975  0.034220  0.084587
            8          0.011300 -0.014763  0.039089  0.022519  0.074501
            9         -0.005198 -0.048024  0.012190 -0.029354 -0.022590
            10        -0.003317  0.005441  0.000539 -0.059033  0.033790

                           PC25      PC26      PC27      PC28      PC29  \
country_id  article_n
Afghanistan 1         -0.021114  0.052905 -0.063583  0.042039 -0.000091
            2          0.006952  0.009785 -0.029596  0.006792  0.011247
            3          0.012145  0.001114  0.030956  0.077637  0.041190
            4          0.031803  0.002968  0.009964  0.044950  0.018114
            5         -0.052543 -0.022382  0.036096  0.009286  0.002963
            6         -0.007215  0.027873 -0.022579  0.007868 -0.016421
            7          0.019408  0.076141 -0.125218 -0.012395 -0.021334
            8         -0.080064  0.006980 -0.078096 -0.024353  0.067827
            9         -0.018660  0.002744 -0.026829  0.043560  0.029033
            10        -0.057786 -0.054682 -0.002701 -0.071643  0.012211

                           PC30      PC31      PC32      PC33      PC34  \
country_id  article_n
Afghanistan 1          0.034913 -0.008033  0.044405  0.081722  0.046572
            2         -0.000166 -0.040940  0.024484  0.008483  0.010375
            3          0.010799 -0.022568  0.096777  0.078470 -0.074169
            4          0.006408 -0.025987  0.057750  0.031607 -0.040226
            5          0.043611 -0.007810  0.004696  0.041453  0.089563
            6         -0.000636  0.012707 -0.001580  0.078490  0.075584
            7          0.012332 -0.050317  0.046942  0.102930  0.044644
            8          0.028293  0.031577  0.044030 -0.007435 -0.023960
            9          0.031184  0.035209  0.026379  0.026532  0.091749
            10        -0.037478 -0.004073  0.000362  0.005438  0.019371

                           PC35      PC36      PC37      PC38      PC39  \
country_id  article_n
Afghanistan 1          0.003892 -0.026178  0.038947 -0.010116 -0.024989
            2         -0.017918  0.002253  0.001624 -0.005802 -0.036017
            3          0.040927 -0.015569  0.074909  0.000967  0.022891
            4          0.017070 -0.008228  0.042339  0.008041  0.018490
            5         -0.027076 -0.063410  0.061014 -0.003170 -0.039919
            6         -0.026822  0.000169 -0.011118 -0.078071 -0.062718
            7         -0.019869 -0.014842  0.046810  0.001166 -0.018124
            8          0.026837  0.054519  0.027277 -0.016349  0.046185
            9         -0.022803  0.007351 -0.010359 -0.076937 -0.026571
            10         0.006579  0.008801 -0.034021 -0.044007  0.000710

                           PC40      PC41      PC42      PC43      PC44  \
country_id  article_n
Afghanistan 1          0.021897 -0.010784  0.019455  0.012325 -0.000515
            2         -0.011810  0.030111 -0.005080  0.049154  0.025262
            3          0.130293 -0.033154  0.088779  0.067342  0.077554
            4          0.066758 -0.018883  0.039353  0.032321  0.034089
            5         -0.018413 -0.066179 -0.039643  0.021047 -0.011115
            6          0.022912 -0.019700 -0.020629 -0.044017  0.008236
            7         -0.038993  0.004366  0.011492  0.007548 -0.003449
            8          0.004605 -0.009932 -0.013089  0.072264 -0.006169
            9          0.040036  0.020134 -0.026481 -0.016679 -0.015679
            10         0.040195 -0.002638 -0.003529 -0.058670 -0.081411

                           PC45      PC46      PC47      PC48      PC49  ...  \
country_id  article_n                                                    ...
Afghanistan 1         -0.025771 -0.000904 -0.003295  0.029574  0.024513  ...
            2          0.043578 -0.034494  0.027400 -0.020706 -0.005568  ...
            3         -0.018898  0.129458  0.047132 -0.072716  0.024528  ...
            4         -0.004221  0.062836  0.025726 -0.046317  0.016396  ...
            5         -0.048444 -0.023765  0.049400  0.004028  0.008351  ...
            6          0.003021 -0.040344  0.005123  0.030182 -0.033850  ...
            7         -0.020944 -0.018716  0.008898  0.031685  0.011820  ...
            8          0.002074 -0.024929 -0.005667  0.022216 -0.004219  ...
            9          0.040487 -0.058222  0.011582 -0.014724  0.010728  ...
            10         0.015795 -0.016851  0.077740 -0.003650  0.009327  ...

                         PC2956    PC2957    PC2958    PC2959    PC2960  \
country_id  article_n
Afghanistan 1          0.000118 -0.001558  0.002348 -0.001758 -0.006545
            2         -0.000386  0.000355 -0.000648  0.000256  0.001128
            3         -0.001385  0.001204  0.001286  0.000668  0.000965
            4         -0.001316 -0.005058 -0.001443 -0.004720 -0.000451
            5          0.000126 -0.001010  0.001051 -0.000449  0.002245
            6         -0.001833 -0.003732 -0.000638 -0.002183  0.001126
            7         -0.011755 -0.003920 -0.001544  0.005641  0.001485
            8          0.005202  0.001465  0.002938 -0.000579 -0.000596
            9         -0.010936  0.002594  0.005136 -0.000682 -0.000006
            10         0.003757  0.002500  0.001069 -0.003714  0.004877

                         PC2961    PC2962    PC2963        PC2964    PC2965  \
country_id  article_n
Afghanistan 1          0.000766  0.001896 -0.001526 -2.053453e-03  0.000320
            2          0.002196  0.000761  0.000756  1.279938e-03 -0.003081
            3         -0.001171  0.000288 -0.000137  5.331709e-04  0.000627
            4         -0.003889 -0.001366 -0.002227  2.221683e-03  0.000580
            5         -0.002863 -0.003396  0.001453 -3.006994e-03 -0.000122
            6          0.001721 -0.002565 -0.002708  3.466718e-05 -0.000061
            7         -0.001213 -0.006149 -0.000960  1.545829e-03 -0.001446
            8          0.000261  0.001504  0.001184 -7.161281e-07 -0.001552
            9         -0.000912  0.001115  0.001120  2.353413e-03 -0.002198
            10        -0.000647 -0.000056  0.000919 -1.734064e-03  0.000077

                         PC2966    PC2967    PC2968    PC2969    PC2970  \
country_id  article_n
Afghanistan 1         -0.002046 -0.002840  0.000034  0.001377  0.005058
            2          0.000274  0.000141  0.001388 -0.001649  0.001609
            3          0.001597 -0.001078  0.002056  0.000165  0.000461
            4         -0.002144 -0.002150  0.000661  0.001734 -0.000859
            5         -0.001388 -0.002059  0.000489 -0.000139  0.001675
            6         -0.001491 -0.001384 -0.000020 -0.002662  0.001753
            7         -0.001167 -0.000929 -0.002005  0.000146  0.002675
            8          0.000199  0.000664 -0.002412  0.002492 -0.000169
            9         -0.000203 -0.001130 -0.001960  0.000817 -0.002800
            10        -0.003264  0.001276 -0.003348  0.002238 -0.001768

                         PC2971    PC2972    PC2973    PC2974    PC2975  \
country_id  article_n
Afghanistan 1          0.000852  0.000097  0.000006 -0.001290  0.000972
            2         -0.001593 -0.000287 -0.000255 -0.000335 -0.000228
            3         -0.000220 -0.000473  0.000006 -0.000903  0.001029
            4          0.000587 -0.001943 -0.001543 -0.001507  0.000200
            5          0.001100 -0.000354  0.000355 -0.000369 -0.000163
            6          0.001461  0.000210  0.004210  0.006324 -0.003089
            7          0.001877 -0.004270  0.004500 -0.000418  0.001221
            8         -0.000106 -0.002488 -0.002481 -0.002654 -0.001991
            9          0.002189 -0.001155 -0.000859 -0.002554  0.000766
            10         0.002356 -0.001103 -0.001978  0.001576  0.001164

                         PC2976    PC2977    PC2978    PC2979    PC2980  \
country_id  article_n
Afghanistan 1          0.001538  0.000160  0.001831 -0.001433  0.003550
            2         -0.000392  0.000605 -0.000467 -0.000679  0.001275
            3         -0.001025  0.000646  0.000359  0.000562 -0.000154
            4          0.001352 -0.001377  0.001880 -0.002310 -0.001370
            5         -0.002174 -0.000473 -0.000799 -0.000107 -0.000648
            6          0.001275 -0.003047  0.007601 -0.004293 -0.002320
            7         -0.000204 -0.001921 -0.002810  0.000879 -0.002421
            8          0.000721  0.001040  0.000675  0.001067 -0.000286
            9         -0.001166  0.001148 -0.000587  0.001608  0.001246
            10         0.001033  0.000705  0.000357  0.000330 -0.000341

                         PC2981    PC2982    PC2983    PC2984    PC2985  \
country_id  article_n
Afghanistan 1          0.000562 -0.000687  0.001355 -0.000273 -0.000271
            2         -0.000528  0.007505  0.004088 -0.000732  0.000101
            3          0.000380 -0.001331  0.000285 -0.000705 -0.000248
            4          0.001361 -0.001471  0.001690 -0.002811  0.001103
            5          0.001061 -0.001896 -0.000963 -0.000793  0.000772
            6         -0.000855  0.000341 -0.001319  0.002572  0.000092
            7          0.000408  0.002405  0.002189  0.002165  0.000621
            8          0.001000  0.000449 -0.000032 -0.001327 -0.001992
            9          0.000154  0.001419 -0.000613 -0.001422  0.000545
            10        -0.001079 -0.001228 -0.000114  0.002702 -0.000912

                         PC2986    PC2987    PC2988    PC2989    PC2990  \
country_id  article_n
Afghanistan 1         -0.000407  0.000807 -0.000413  0.001786  0.000767
            2          0.002298 -0.001188  0.000078 -0.000214 -0.000332
            3          0.003020 -0.001011  0.000111 -0.000027  0.000389
            4         -0.000848  0.002022  0.000421  0.000187  0.001159
            5          0.003089 -0.001112 -0.000563  0.001129  0.000673
            6          0.002498  0.001011  0.000036  0.001790  0.000192
            7         -0.000540  0.000249 -0.000463  0.000173  0.000935
            8          0.000808 -0.000685 -0.000039  0.000010  0.000755
            9         -0.000022 -0.001525 -0.000216  0.001445 -0.000716
            10         0.001442  0.000446 -0.000380  0.001156  0.000626

                         PC2991    PC2992    PC2993    PC2994    PC2995  \
country_id  article_n
Afghanistan 1          0.000640 -0.001502  0.000054 -0.000695 -0.001935
            2         -0.000598 -0.000009 -0.000361 -0.000017  0.000318
            3         -0.000161  0.000224 -0.000295 -0.000271  0.000298
            4          0.001157 -0.000327 -0.000289  0.001192 -0.006824
            5         -0.000499  0.000043  0.000906 -0.000136  0.000502
            6          0.000394  0.000916  0.000295 -0.000080 -0.000163
            7         -0.000423  0.000454 -0.000906 -0.000473  0.000230
            8         -0.001265 -0.000337  0.000055 -0.000269 -0.000115
            9         -0.003089 -0.003169  0.000927  0.000299  0.000044
            10        -0.000458  0.000556  0.000061  0.000524  0.000715

                         PC2996    PC2997    PC2998    PC2999    PC3000  \
country_id  article_n
Afghanistan 1          0.012389  0.001431 -0.000566  0.000300 -0.000056
            2         -0.000364 -0.000055 -0.000115  0.000300  0.000015
            3          0.000295 -0.000358  0.000528  0.000120 -0.000147
            4          0.000012  0.000133  0.001086  0.000457  0.000171
            5          0.000954 -0.000263 -0.000034  0.000017  0.000010
            6         -0.002381  0.000460  0.000009 -0.000178  0.000015
            7          0.000845 -0.000735 -0.000296  0.000879 -0.000067
            8         -0.000081  0.000250  0.000113  0.000226  0.000077
            9         -0.000692 -0.000067 -0.000575 -0.000638  0.000052
            10        -0.000264 -0.000398  0.000505 -0.000030  0.000095

                         PC3001    PC3002    PC3003    PC3004        PC3005
country_id  article_n
Afghanistan 1         -0.000419 -0.000534  0.000012 -0.000288 -4.103543e-17
            2          0.000156  0.000063  0.000022  0.000063  1.380211e-17
            3          0.000006  0.000032  0.000046  0.000033  3.744447e-17
            4          0.000088  0.000355  0.000061  0.000149  1.817003e-17
            5         -0.000104  0.000287  0.000307  0.000013 -4.772946e-17
            6          0.000015  0.000017 -0.000210 -0.000009 -8.242890e-18
            7         -0.000365 -0.000057  0.000022 -0.000216 -2.110633e-17
            8          0.000109 -0.000262 -0.000077  0.000085 -1.520382e-17
            9         -0.000209  0.000010  0.000110  0.000059  2.328051e-17
            10         0.000181  0.000151  0.000042  0.000037 -1.926363e-17

[10 rows x 3006 columns]

## PCA Loadings

This section inspects the PCA loadings table, which connects terms to principal components.

In [8]:
PCA_LOADINGS = inspect_table(
    section='PCA Loadings',
    box_url='https://virginia.box.com/shared/static/czlfhh4uprbcx2dg87jn8iyyft0yvaex',
    local_path='pca_loadings.parquet',
    file_format='parquet'
)

Section: PCA Loadings
Box URL: https://virginia.box.com/shared/static/czlfhh4uprbcx2dg87jn8iyyft0yvaex
Local file: pca_loadings.parquet
Loaded from: Box download
Format: parquet
Shape: 3,006 rows x 3,006 columns
Number of observations: 3,006
Column names:
PC0, PC1, PC2, PC3, PC4, PC5, PC6, PC7, PC8, PC9, PC10, PC11, PC12, PC13, PC14, PC15, PC16, PC17,
PC18, PC19, PC20, PC21, PC22, PC23, PC24, PC25, PC26, PC27, PC28, PC29, PC30, PC31, PC32, PC33,
PC34, PC35, PC36, PC37, PC38, PC39, PC40, PC41, PC42, PC43, PC44, PC45, PC46, PC47, PC48, PC49,
PC50, PC51, PC52, PC53, PC54, PC55, PC56, PC57, PC58, PC59, PC60, PC61, PC62, PC63, PC64, PC65,
PC66, PC67, PC68, PC69, PC70, PC71, PC72, PC73, PC74, PC75, PC76, PC77, PC78, PC79, PC80, PC81,
PC82, PC83, PC84, PC85, PC86, PC87, PC88, PC89, PC90, PC91, PC92, PC93, PC94, PC95, PC96, PC97,
PC98, PC99, PC100, PC101, PC102, PC103, PC104, PC105, PC106, PC107, PC108, PC109, PC110, PC111,
PC112, PC113, PC114, PC115, PC116, PC117, PC118, PC119, PC120, PC121, PC122, PC123, PC124, PC125,
PC126, PC127, PC128, PC129, PC130, PC131, PC132, PC133, PC134, PC135, PC136, PC137, PC138, PC139,
PC140, PC141, PC142, PC143, PC144, PC145, PC146, PC147, PC148, PC149, PC150, PC151, PC152, PC153,
PC154, PC155, PC156, PC157, PC158, PC159, PC160, PC161, PC162, PC163, PC164, PC165, PC166, PC167,
PC168, PC169, PC170, PC171, PC172, PC173, PC174, PC175, PC176, PC177, PC178, PC179, PC180, PC181,
PC182, PC183, PC184, PC185, PC186, PC187, PC188, PC189, PC190, PC191, PC192, PC193, PC194, PC195,
PC196, PC197, PC198, PC199, PC200, PC201, PC202, PC203, PC204, PC205, PC206, PC207, PC208, PC209,
PC210, PC211, PC212, PC213, PC214, PC215, PC216, PC217, PC218, PC219, PC220, PC221, PC222, PC223,
PC224, PC225, PC226, PC227, PC228, PC229, PC230, PC231, PC232, PC233, PC234, PC235, PC236, PC237,
PC238, PC239, PC240, PC241, PC242, PC243, PC244, PC245, PC246, PC247, PC248, PC249, PC250, PC251,
PC252, PC253, PC254, PC255, PC256, PC257, PC258, PC259, PC260, PC261, PC262, PC263, PC264, PC265,
PC266, PC267, PC268, PC269, PC270, PC271, PC272, PC273, PC274, PC275, PC276, PC277, PC278, PC279,
PC280, PC281, PC282, PC283, PC284, PC285, PC286, PC287, PC288, PC289, PC290, PC291, PC292, PC293,
PC294, PC295, PC296, PC297, PC298, PC299, PC300, PC301, PC302, PC303, PC304, PC305, PC306, PC307,
PC308, PC309, PC310, PC311, PC312, PC313, PC314, PC315, PC316, PC317, PC318, PC319, PC320, PC321,
PC322, PC323, PC324, PC325, PC326, PC327, PC328, PC329, PC330, PC331, PC332, PC333, PC334, PC335,
PC336, PC337, PC338, PC339, PC340, PC341, PC342, PC343, PC344, PC345, PC346, PC347, PC348, PC349,
PC350, PC351, PC352, PC353, PC354, PC355, PC356, PC357, PC358, PC359, PC360, PC361, PC362, PC363,
PC364, PC365, PC366, PC367, PC368, PC369, PC370, PC371, PC372, PC373, PC374, PC375, PC376, PC377,
PC378, PC379, PC380, PC381, PC382, PC383, PC384, PC385, PC386, PC387, PC388, PC389, PC390, PC391,
PC392, PC393, PC394, PC395, PC396, PC397, PC398, PC399, PC400, PC401, PC402, PC403, PC404, PC405,
PC406, PC407, PC408, PC409, PC410, PC411, PC412, PC413, PC414, PC415, PC416, PC417, PC418, PC419,
PC420, PC421, PC422, PC423, PC424, PC425, PC426, PC427, PC428, PC429, PC430, PC431, PC432, PC433,
PC434, PC435, PC436, PC437, PC438, PC439, PC440, PC441, PC442, PC443, PC444, PC445, PC446, PC447,
PC448, PC449, PC450, PC451, PC452, PC453, PC454, PC455, PC456, PC457, PC458, PC459, PC460, PC461,
PC462, PC463, PC464, PC465, PC466, PC467, PC468, PC469, PC470, PC471, PC472, PC473, PC474, PC475,
PC476, PC477, PC478, PC479, PC480, PC481, PC482, PC483, PC484, PC485, PC486, PC487, PC488, PC489,
PC490, PC491, PC492, PC493, PC494, PC495, PC496, PC497, PC498, PC499, PC500, PC501, PC502, PC503,
PC504, PC505, PC506, PC507, PC508, PC509, PC510, PC511, PC512, PC513, PC514, PC515, PC516, PC517,
PC518, PC519, PC520, PC521, PC522, PC523, PC524, PC525, PC526, PC527, PC528, PC529, PC530, PC531,
PC532, PC533, PC534, PC535, PC536, PC537, PC538, PC539, PC540, PC541, PC542, PC543, PC544, PC545,
PC546, PC547, PC548, PC549, PC550, PC551, PC552, PC553, PC554, PC555, PC556, PC557, PC558, PC559,
PC560, PC561, PC562, PC563, PC564, PC565, PC566, PC567, PC568, PC569, PC570, PC571, PC572, PC573,
PC574, PC575, PC576, PC577, PC578, PC579, PC580, PC581, PC582, PC583, PC584, PC585, PC586, PC587,
PC588, PC589, PC590, PC591, PC592, PC593, PC594, PC595, PC596, PC597, PC598, PC599, PC600, PC601,
PC602, PC603, PC604, PC605, PC606, PC607, PC608, PC609, PC610, PC611, PC612, PC613, PC614, PC615,
PC616, PC617, PC618, PC619, PC620, PC621, PC622, PC623, PC624, PC625, PC626, PC627, PC628, PC629,
PC630, PC631, PC632, PC633, PC634, PC635, PC636, PC637, PC638, PC639, PC640, PC641, PC642, PC643,
PC644, PC645, PC646, PC647, PC648, PC649, PC650, PC651, PC652, PC653, PC654, PC655, PC656, PC657,
PC658, PC659, PC660, PC661, PC662, PC663, PC664, PC665, PC666, PC667, PC668, PC669, PC670, PC671,
PC672, PC673, PC674, PC675, PC676, PC677, PC678, PC679, PC680, PC681, PC682, PC683, PC684, PC685,
PC686, PC687, PC688, PC689, PC690, PC691, PC692, PC693, PC694, PC695, PC696, PC697, PC698, PC699,
PC700, PC701, PC702, PC703, PC704, PC705, PC706, PC707, PC708, PC709, PC710, PC711, PC712, PC713,
PC714, PC715, PC716, PC717, PC718, PC719, PC720, PC721, PC722, PC723, PC724, PC725, PC726, PC727,
PC728, PC729, PC730, PC731, PC732, PC733, PC734, PC735, PC736, PC737, PC738, PC739, PC740, PC741,
PC742, PC743, PC744, PC745, PC746, PC747, PC748, PC749, PC750, PC751, PC752, PC753, PC754, PC755,
PC756, PC757, PC758, PC759, PC760, PC761, PC762, PC763, PC764, PC765, PC766, PC767, PC768, PC769,
PC770, PC771, PC772, PC773, PC774, PC775, PC776, PC777, PC778, PC779, PC780, PC781, PC782, PC783,
PC784, PC785, PC786, PC787, PC788, PC789, PC790, PC791, PC792, PC793, PC794, PC795, PC796, PC797,
PC798, PC799, PC800, PC801, PC802, PC803, PC804, PC805, PC806, PC807, PC808, PC809, PC810, PC811,
PC812, PC813, PC814, PC815, PC816, PC817, PC818, PC819, PC820, PC821, PC822, PC823, PC824, PC825,
PC826, PC827, PC828, PC829, PC830, PC831, PC832, PC833, PC834, PC835, PC836, PC837, PC838, PC839,
PC840, PC841, PC842, PC843, PC844, PC845, PC846, PC847, PC848, PC849, PC850, PC851, PC852, PC853,
PC854, PC855, PC856, PC857, PC858, PC859, PC860, PC861, PC862, PC863, PC864, PC865, PC866, PC867,
PC868, PC869, PC870, PC871, PC872, PC873, PC874, PC875, PC876, PC877, PC878, PC879, PC880, PC881,
PC882, PC883, PC884, PC885, PC886, PC887, PC888, PC889, PC890, PC891, PC892, PC893, PC894, PC895,
PC896, PC897, PC898, PC899, PC900, PC901, PC902, PC903, PC904, PC905, PC906, PC907, PC908, PC909,
PC910, PC911, PC912, PC913, PC914, PC915, PC916, PC917, PC918, PC919, PC920, PC921, PC922, PC923,
PC924, PC925, PC926, PC927, PC928, PC929, PC930, PC931, PC932, PC933, PC934, PC935, PC936, PC937,
PC938, PC939, PC940, PC941, PC942, PC943, PC944, PC945, PC946, PC947, PC948, PC949, PC950, PC951,
PC952, PC953, PC954, PC955, PC956, PC957, PC958, PC959, PC960, PC961, PC962, PC963, PC964, PC965,
PC966, PC967, PC968, PC969, PC970, PC971, PC972, PC973, PC974, PC975, PC976, PC977, PC978, PC979,
PC980, PC981, PC982, PC983, PC984, PC985, PC986, PC987, PC988, PC989, PC990, PC991, PC992, PC993,
PC994, PC995, PC996, PC997, PC998, PC999, PC1000, PC1001, PC1002, PC1003, PC1004, PC1005, PC1006,
PC1007, PC1008, PC1009, PC1010, PC1011, PC1012, PC1013, PC1014, PC1015, PC1016, PC1017, PC1018,
PC1019, PC1020, PC1021, PC1022, PC1023, PC1024, PC1025, PC1026, PC1027, PC1028, PC1029, PC1030,
PC1031, PC1032, PC1033, PC1034, PC1035, PC1036, PC1037, PC1038, PC1039, PC1040, PC1041, PC1042,
PC1043, PC1044, PC1045, PC1046, PC1047, PC1048, PC1049, PC1050, PC1051, PC1052, PC1053, PC1054,
PC1055, PC1056, PC1057, PC1058, PC1059, PC1060, PC1061, PC1062, PC1063, PC1064, PC1065, PC1066,
PC1067, PC1068, PC1069, PC1070, PC1071, PC1072, PC1073, PC1074, PC1075, PC1076, PC1077, PC1078,
PC1079, PC1080, PC1081, PC1082, PC1083, PC1084, PC1085, PC1086, PC1087, PC1088, PC1089, PC1090,
PC1091, PC1092, PC1093, PC1094, PC1095, PC1096, PC1097, PC1098, PC1099, PC1100, PC1101, PC1102,
PC1103, PC1104, PC1105, PC1106, PC1107, PC1108, PC1109, PC1110, PC1111, PC1112, PC1113, PC1114,
PC1115, PC1116, PC1117, PC1118, PC1119, PC1120, PC1121, PC1122, PC1123, PC1124, PC1125, PC1126,
PC1127, PC1128, PC1129, PC1130, PC1131, PC1132, PC1133, PC1134, PC1135, PC1136, PC1137, PC1138,
PC1139, PC1140, PC1141, PC1142, PC1143, PC1144, PC1145, PC1146, PC1147, PC1148, PC1149, PC1150,
PC1151, PC1152, PC1153, PC1154, PC1155, PC1156, PC1157, PC1158, PC1159, PC1160, PC1161, PC1162,
PC1163, PC1164, PC1165, PC1166, PC1167, PC1168, PC1169, PC1170, PC1171, PC1172, PC1173, PC1174,
PC1175, PC1176, PC1177, PC1178, PC1179, PC1180, PC1181, PC1182, PC1183, PC1184, PC1185, PC1186,
PC1187, PC1188, PC1189, PC1190, PC1191, PC1192, PC1193, PC1194, PC1195, PC1196, PC1197, PC1198,
PC1199, PC1200, PC1201, PC1202, PC1203, PC1204, PC1205, PC1206, PC1207, PC1208, PC1209, PC1210,
PC1211, PC1212, PC1213, PC1214, PC1215, PC1216, PC1217, PC1218, PC1219, PC1220, PC1221, PC1222,
PC1223, PC1224, PC1225, PC1226, PC1227, PC1228, PC1229, PC1230, PC1231, PC1232, PC1233, PC1234,
PC1235, PC1236, PC1237, PC1238, PC1239, PC1240, PC1241, PC1242, PC1243, PC1244, PC1245, PC1246,
PC1247, PC1248, PC1249, PC1250, PC1251, PC1252, PC1253, PC1254, PC1255, PC1256, PC1257, PC1258,
PC1259, PC1260, PC1261, PC1262, PC1263, PC1264, PC1265, PC1266, PC1267, PC1268, PC1269, PC1270,
PC1271, PC1272, PC1273, PC1274, PC1275, PC1276, PC1277, PC1278, PC1279, PC1280, PC1281, PC1282,
PC1283, PC1284, PC1285, PC1286, PC1287, PC1288, PC1289, PC1290, PC1291, PC1292, PC1293, PC1294,
PC1295, PC1296, PC1297, PC1298, PC1299, PC1300, PC1301, PC1302, PC1303, PC1304, PC1305, PC1306,
PC1307, PC1308, PC1309, PC1310, PC1311, PC1312, PC1313, PC1314, PC1315, PC1316, PC1317, PC1318,
PC1319, PC1320, PC1321, PC1322, PC1323, PC1324, PC1325, PC1326, PC1327, PC1328, PC1329, PC1330,
PC1331, PC1332, PC1333, PC1334, PC1335, PC1336, PC1337, PC1338, PC1339, PC1340, PC1341, PC1342,
PC1343, PC1344, PC1345, PC1346, PC1347, PC1348, PC1349, PC1350, PC1351, PC1352, PC1353, PC1354,
PC1355, PC1356, PC1357, PC1358, PC1359, PC1360, PC1361, PC1362, PC1363, PC1364, PC1365, PC1366,
PC1367, PC1368, PC1369, PC1370, PC1371, PC1372, PC1373, PC1374, PC1375, PC1376, PC1377, PC1378,
PC1379, PC1380, PC1381, PC1382, PC1383, PC1384, PC1385, PC1386, PC1387, PC1388, PC1389, PC1390,
PC1391, PC1392, PC1393, PC1394, PC1395, PC1396, PC1397, PC1398, PC1399, PC1400, PC1401, PC1402,
PC1403, PC1404, PC1405, PC1406, PC1407, PC1408, PC1409, PC1410, PC1411, PC1412, PC1413, PC1414,
PC1415, PC1416, PC1417, PC1418, PC1419, PC1420, PC1421, PC1422, PC1423, PC1424, PC1425, PC1426,
PC1427, PC1428, PC1429, PC1430, PC1431, PC1432, PC1433, PC1434, PC1435, PC1436, PC1437, PC1438,
PC1439, PC1440, PC1441, PC1442, PC1443, PC1444, PC1445, PC1446, PC1447, PC1448, PC1449, PC1450,
PC1451, PC1452, PC1453, PC1454, PC1455, PC1456, PC1457, PC1458, PC1459, PC1460, PC1461, PC1462,
PC1463, PC1464, PC1465, PC1466, PC1467, PC1468, PC1469, PC1470, PC1471, PC1472, PC1473, PC1474,
PC1475, PC1476, PC1477, PC1478, PC1479, PC1480, PC1481, PC1482, PC1483, PC1484, PC1485, PC1486,
PC1487, PC1488, PC1489, PC1490, PC1491, PC1492, PC1493, PC1494, PC1495, PC1496, PC1497, PC1498,
PC1499, PC1500, PC1501, PC1502, PC1503, PC1504, PC1505, PC1506, PC1507, PC1508, PC1509, PC1510,
PC1511, PC1512, PC1513, PC1514, PC1515, PC1516, PC1517, PC1518, PC1519, PC1520, PC1521, PC1522,
PC1523, PC1524, PC1525, PC1526, PC1527, PC1528, PC1529, PC1530, PC1531, PC1532, PC1533, PC1534,
PC1535, PC1536, PC1537, PC1538, PC1539, PC1540, PC1541, PC1542, PC1543, PC1544, PC1545, PC1546,
PC1547, PC1548, PC1549, PC1550, PC1551, PC1552, PC1553, PC1554, PC1555, PC1556, PC1557, PC1558,
PC1559, PC1560, PC1561, PC1562, PC1563, PC1564, PC1565, PC1566, PC1567, PC1568, PC1569, PC1570,
PC1571, PC1572, PC1573, PC1574, PC1575, PC1576, PC1577, PC1578, PC1579, PC1580, PC1581, PC1582,
PC1583, PC1584, PC1585, PC1586, PC1587, PC1588, PC1589, PC1590, PC1591, PC1592, PC1593, PC1594,
PC1595, PC1596, PC1597, PC1598, PC1599, PC1600, PC1601, PC1602, PC1603, PC1604, PC1605, PC1606,
PC1607, PC1608, PC1609, PC1610, PC1611, PC1612, PC1613, PC1614, PC1615, PC1616, PC1617, PC1618,
PC1619, PC1620, PC1621, PC1622, PC1623, PC1624, PC1625, PC1626, PC1627, PC1628, PC1629, PC1630,
PC1631, PC1632, PC1633, PC1634, PC1635, PC1636, PC1637, PC1638, PC1639, PC1640, PC1641, PC1642,
PC1643, PC1644, PC1645, PC1646, PC1647, PC1648, PC1649, PC1650, PC1651, PC1652, PC1653, PC1654,
PC1655, PC1656, PC1657, PC1658, PC1659, PC1660, PC1661, PC1662, PC1663, PC1664, PC1665, PC1666,
PC1667, PC1668, PC1669, PC1670, PC1671, PC1672, PC1673, PC1674, PC1675, PC1676, PC1677, PC1678,
PC1679, PC1680, PC1681, PC1682, PC1683, PC1684, PC1685, PC1686, PC1687, PC1688, PC1689, PC1690,
PC1691, PC1692, PC1693, PC1694, PC1695, PC1696, PC1697, PC1698, PC1699, PC1700, PC1701, PC1702,
PC1703, PC1704, PC1705, PC1706, PC1707, PC1708, PC1709, PC1710, PC1711, PC1712, PC1713, PC1714,
PC1715, PC1716, PC1717, PC1718, PC1719, PC1720, PC1721, PC1722, PC1723, PC1724, PC1725, PC1726,
PC1727, PC1728, PC1729, PC1730, PC1731, PC1732, PC1733, PC1734, PC1735, PC1736, PC1737, PC1738,
PC1739, PC1740, PC1741, PC1742, PC1743, PC1744, PC1745, PC1746, PC1747, PC1748, PC1749, PC1750,
PC1751, PC1752, PC1753, PC1754, PC1755, PC1756, PC1757, PC1758, PC1759, PC1760, PC1761, PC1762,
PC1763, PC1764, PC1765, PC1766, PC1767, PC1768, PC1769, PC1770, PC1771, PC1772, PC1773, PC1774,
PC1775, PC1776, PC1777, PC1778, PC1779, PC1780, PC1781, PC1782, PC1783, PC1784, PC1785, PC1786,
PC1787, PC1788, PC1789, PC1790, PC1791, PC1792, PC1793, PC1794, PC1795, PC1796, PC1797, PC1798,
PC1799, PC1800, PC1801, PC1802, PC1803, PC1804, PC1805, PC1806, PC1807, PC1808, PC1809, PC1810,
PC1811, PC1812, PC1813, PC1814, PC1815, PC1816, PC1817, PC1818, PC1819, PC1820, PC1821, PC1822,
PC1823, PC1824, PC1825, PC1826, PC1827, PC1828, PC1829, PC1830, PC1831, PC1832, PC1833, PC1834,
PC1835, PC1836, PC1837, PC1838, PC1839, PC1840, PC1841, PC1842, PC1843, PC1844, PC1845, PC1846,
PC1847, PC1848, PC1849, PC1850, PC1851, PC1852, PC1853, PC1854, PC1855, PC1856, PC1857, PC1858,
PC1859, PC1860, PC1861, PC1862, PC1863, PC1864, PC1865, PC1866, PC1867, PC1868, PC1869, PC1870,
PC1871, PC1872, PC1873, PC1874, PC1875, PC1876, PC1877, PC1878, PC1879, PC1880, PC1881, PC1882,
PC1883, PC1884, PC1885, PC1886, PC1887, PC1888, PC1889, PC1890, PC1891, PC1892, PC1893, PC1894,
PC1895, PC1896, PC1897, PC1898, PC1899, PC1900, PC1901, PC1902, PC1903, PC1904, PC1905, PC1906,
PC1907, PC1908, PC1909, PC1910, PC1911, PC1912, PC1913, PC1914, PC1915, PC1916, PC1917, PC1918,
PC1919, PC1920, PC1921, PC1922, PC1923, PC1924, PC1925, PC1926, PC1927, PC1928, PC1929, PC1930,
PC1931, PC1932, PC1933, PC1934, PC1935, PC1936, PC1937, PC1938, PC1939, PC1940, PC1941, PC1942,
PC1943, PC1944, PC1945, PC1946, PC1947, PC1948, PC1949, PC1950, PC1951, PC1952, PC1953, PC1954,
PC1955, PC1956, PC1957, PC1958, PC1959, PC1960, PC1961, PC1962, PC1963, PC1964, PC1965, PC1966,
PC1967, PC1968, PC1969, PC1970, PC1971, PC1972, PC1973, PC1974, PC1975, PC1976, PC1977, PC1978,
PC1979, PC1980, PC1981, PC1982, PC1983, PC1984, PC1985, PC1986, PC1987, PC1988, PC1989, PC1990,
PC1991, PC1992, PC1993, PC1994, PC1995, PC1996, PC1997, PC1998, PC1999, PC2000, PC2001, PC2002,
PC2003, PC2004, PC2005, PC2006, PC2007, PC2008, PC2009, PC2010, PC2011, PC2012, PC2013, PC2014,
PC2015, PC2016, PC2017, PC2018, PC2019, PC2020, PC2021, PC2022, PC2023, PC2024, PC2025, PC2026,
PC2027, PC2028, PC2029, PC2030, PC2031, PC2032, PC2033, PC2034, PC2035, PC2036, PC2037, PC2038,
PC2039, PC2040, PC2041, PC2042, PC2043, PC2044, PC2045, PC2046, PC2047, PC2048, PC2049, PC2050,
PC2051, PC2052, PC2053, PC2054, PC2055, PC2056, PC2057, PC2058, PC2059, PC2060, PC2061, PC2062,
PC2063, PC2064, PC2065, PC2066, PC2067, PC2068, PC2069, PC2070, PC2071, PC2072, PC2073, PC2074,
PC2075, PC2076, PC2077, PC2078, PC2079, PC2080, PC2081, PC2082, PC2083, PC2084, PC2085, PC2086,
PC2087, PC2088, PC2089, PC2090, PC2091, PC2092, PC2093, PC2094, PC2095, PC2096, PC2097, PC2098,
PC2099, PC2100, PC2101, PC2102, PC2103, PC2104, PC2105, PC2106, PC2107, PC2108, PC2109, PC2110,
PC2111, PC2112, PC2113, PC2114, PC2115, PC2116, PC2117, PC2118, PC2119, PC2120, PC2121, PC2122,
PC2123, PC2124, PC2125, PC2126, PC2127, PC2128, PC2129, PC2130, PC2131, PC2132, PC2133, PC2134,
PC2135, PC2136, PC2137, PC2138, PC2139, PC2140, PC2141, PC2142, PC2143, PC2144, PC2145, PC2146,
PC2147, PC2148, PC2149, PC2150, PC2151, PC2152, PC2153, PC2154, PC2155, PC2156, PC2157, PC2158,
PC2159, PC2160, PC2161, PC2162, PC2163, PC2164, PC2165, PC2166, PC2167, PC2168, PC2169, PC2170,
PC2171, PC2172, PC2173, PC2174, PC2175, PC2176, PC2177, PC2178, PC2179, PC2180, PC2181, PC2182,
PC2183, PC2184, PC2185, PC2186, PC2187, PC2188, PC2189, PC2190, PC2191, PC2192, PC2193, PC2194,
PC2195, PC2196, PC2197, PC2198, PC2199, PC2200, PC2201, PC2202, PC2203, PC2204, PC2205, PC2206,
PC2207, PC2208, PC2209, PC2210, PC2211, PC2212, PC2213, PC2214, PC2215, PC2216, PC2217, PC2218,
PC2219, PC2220, PC2221, PC2222, PC2223, PC2224, PC2225, PC2226, PC2227, PC2228, PC2229, PC2230,
PC2231, PC2232, PC2233, PC2234, PC2235, PC2236, PC2237, PC2238, PC2239, PC2240, PC2241, PC2242,
PC2243, PC2244, PC2245, PC2246, PC2247, PC2248, PC2249, PC2250, PC2251, PC2252, PC2253, PC2254,
PC2255, PC2256, PC2257, PC2258, PC2259, PC2260, PC2261, PC2262, PC2263, PC2264, PC2265, PC2266,
PC2267, PC2268, PC2269, PC2270, PC2271, PC2272, PC2273, PC2274, PC2275, PC2276, PC2277, PC2278,
PC2279, PC2280, PC2281, PC2282, PC2283, PC2284, PC2285, PC2286, PC2287, PC2288, PC2289, PC2290,
PC2291, PC2292, PC2293, PC2294, PC2295, PC2296, PC2297, PC2298, PC2299, PC2300, PC2301, PC2302,
PC2303, PC2304, PC2305, PC2306, PC2307, PC2308, PC2309, PC2310, PC2311, PC2312, PC2313, PC2314,
PC2315, PC2316, PC2317, PC2318, PC2319, PC2320, PC2321, PC2322, PC2323, PC2324, PC2325, PC2326,
PC2327, PC2328, PC2329, PC2330, PC2331, PC2332, PC2333, PC2334, PC2335, PC2336, PC2337, PC2338,
PC2339, PC2340, PC2341, PC2342, PC2343, PC2344, PC2345, PC2346, PC2347, PC2348, PC2349, PC2350,
PC2351, PC2352, PC2353, PC2354, PC2355, PC2356, PC2357, PC2358, PC2359, PC2360, PC2361, PC2362,
PC2363, PC2364, PC2365, PC2366, PC2367, PC2368, PC2369, PC2370, PC2371, PC2372, PC2373, PC2374,
PC2375, PC2376, PC2377, PC2378, PC2379, PC2380, PC2381, PC2382, PC2383, PC2384, PC2385, PC2386,
PC2387, PC2388, PC2389, PC2390, PC2391, PC2392, PC2393, PC2394, PC2395, PC2396, PC2397, PC2398,
PC2399, PC2400, PC2401, PC2402, PC2403, PC2404, PC2405, PC2406, PC2407, PC2408, PC2409, PC2410,
PC2411, PC2412, PC2413, PC2414, PC2415, PC2416, PC2417, PC2418, PC2419, PC2420, PC2421, PC2422,
PC2423, PC2424, PC2425, PC2426, PC2427, PC2428, PC2429, PC2430, PC2431, PC2432, PC2433, PC2434,
PC2435, PC2436, PC2437, PC2438, PC2439, PC2440, PC2441, PC2442, PC2443, PC2444, PC2445, PC2446,
PC2447, PC2448, PC2449, PC2450, PC2451, PC2452, PC2453, PC2454, PC2455, PC2456, PC2457, PC2458,
PC2459, PC2460, PC2461, PC2462, PC2463, PC2464, PC2465, PC2466, PC2467, PC2468, PC2469, PC2470,
PC2471, PC2472, PC2473, PC2474, PC2475, PC2476, PC2477, PC2478, PC2479, PC2480, PC2481, PC2482,
PC2483, PC2484, PC2485, PC2486, PC2487, PC2488, PC2489, PC2490, PC2491, PC2492, PC2493, PC2494,
PC2495, PC2496, PC2497, PC2498, PC2499, PC2500, PC2501, PC2502, PC2503, PC2504, PC2505, PC2506,
PC2507, PC2508, PC2509, PC2510, PC2511, PC2512, PC2513, PC2514, PC2515, PC2516, PC2517, PC2518,
PC2519, PC2520, PC2521, PC2522, PC2523, PC2524, PC2525, PC2526, PC2527, PC2528, PC2529, PC2530,
PC2531, PC2532, PC2533, PC2534, PC2535, PC2536, PC2537, PC2538, PC2539, PC2540, PC2541, PC2542,
PC2543, PC2544, PC2545, PC2546, PC2547, PC2548, PC2549, PC2550, PC2551, PC2552, PC2553, PC2554,
PC2555, PC2556, PC2557, PC2558, PC2559, PC2560, PC2561, PC2562, PC2563, PC2564, PC2565, PC2566,
PC2567, PC2568, PC2569, PC2570, PC2571, PC2572, PC2573, PC2574, PC2575, PC2576, PC2577, PC2578,
PC2579, PC2580, PC2581, PC2582, PC2583, PC2584, PC2585, PC2586, PC2587, PC2588, PC2589, PC2590,
PC2591, PC2592, PC2593, PC2594, PC2595, PC2596, PC2597, PC2598, PC2599, PC2600, PC2601, PC2602,

component_id,PC0,PC1,PC2,PC3,PC4,PC5,PC6,PC7,PC8,PC9,PC10,PC11,PC12,PC13,PC14,PC15,PC16,PC17,PC18,PC19,PC20,PC21,PC22,PC23,PC24,PC25,PC26,PC27,PC28,PC29,PC30,PC31,PC32,PC33,PC34,PC35,PC36,PC37,PC38,PC39,PC40,PC41,PC42,PC43,PC44,PC45,PC46,PC47,PC48,PC49,...,PC2956,PC2957,PC2958,PC2959,PC2960,PC2961,PC2962,PC2963,PC2964,PC2965,PC2966,PC2967,PC2968,PC2969,PC2970,PC2971,PC2972,PC2973,PC2974,PC2975,PC2976,PC2977,PC2978,PC2979,PC2980,PC2981,PC2982,PC2983,PC2984,PC2985,PC2986,PC2987,PC2988,PC2989,PC2990,PC2991,PC2992,PC2993,PC2994,PC2995,PC2996,PC2997,PC2998,PC2999,PC3000,PC3001,PC3002,PC3003,PC3004,PC3005
term_str,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
abide,0.004547,0.000818,-0.002043,0.003396,-0.004006,-0.001368,0.004920,0.006490,0.000539,-0.000997,0.005317,0.000324,0.006210,-0.002322,-0.001972,0.003677,0.001010,-0.000622,0.003572,-0.001445,0.000806,-0.002600,-0.001187,-0.001051,0.001336,-0.001671,-0.002661,-0.002383,-0.000702,5.110166e-04,-0.000166,-0.002350,-0.000373,0.000051,0.001838,0.002361,0.003661,-0.001456,-0.005429,-0.001650,0.000125,0.002013,0.002037,-0.002125,0.002263,-0.000864,-0.000269,0.003643,0.003663,-0.004539,...,0.002796,-0.000846,-0.001374,-0.003725,-0.000407,-0.000239,-0.001879,-0.000728,-0.000045,0.004036,-0.000262,0.001712,0.001194,0.000300,-0.000737,-0.000322,0.000102,-0.000824,0.000040,0.001265,-0.000750,-0.000251,-0.000882,0.000292,0.000378,-0.001077,-0.001767,-0.003012,0.000935,0.000599,0.000380,0.000454,0.000337,-0.000801,-0.000419,0.000614,0.000821,0.000506,-0.002007,0.000069,-0.000523,-0.000362,0.000063,0.000235,-0.000032,0.000094,0.000129,-0.000176,0.000034,-3.592310e-18
ability,0.004360,0.002703,-0.004250,0.005048,-0.004115,-0.008342,0.007147,0.005086,0.003806,-0.004755,0.011964,-0.000538,0.014553,-0.004220,-0.008341,0.005852,-0.000118,0.001400,0.003774,-0.004769,0.000469,-0.000170,0.001406,0.001984,-0.000892,0.002628,-0.003025,0.002934,-0.000230,-1.397544e-03,0.002921,0.001880,-0.001314,0.003040,0.001448,-0.001078,0.001966,-0.002091,-0.002280,0.001683,0.007469,-0.000853,0.003162,-0.004837,0.007170,-0.006114,0.000041,0.004688,0.006592,-0.015274,...,0.006871,-0.003967,0.000868,-0.023248,-0.002449,-0.003306,0.001483,-0.000674,0.003036,0.002517,0.003034,-0.002493,-0.002513,-0.008132,-0.000724,0.001314,-0.000679,0.005042,0.003138,-0.003915,0.000929,-0.001574,0.002094,0.000239,-0.002869,-0.004170,0.001961,-0.006797,0.000421,-0.002414,-0.022333,0.008561,-0.000053,0.000576,0.001332,-0.001283,0.001159,0.000044,-0.001005,0.000914,-0.004179,0.000274,0.001985,0.000514,0.000082,0.000233,-0.000658,0.000218,0.000153,8.607667e-17
able,-0.003622,0.002483,-0.006693,0.004605,0.000257,-0.007005,0.002142,-0.008452,-0.004266,-0.004264,-0.005445,-0.002982,-0.000193,-0.001651,0.004871,0.004160,-0.002122,-0.000543,0.005109,-0.004749,0.003161,-0.001918,0.000077,0.000828,-0.001927,-0.001312,-0.001032,0.001392,-0.000471,8.557377e-05,-0.005838,0.001321,-0.002672,0.000337,-0.000193,0.004609,-0.001161,-0.002207,-0.007545,-0.008578,0.004646,-0.007074,0.000648,-0.000712,0.002584,-0.003179,0.001436,0.003318,0.005450,0.004201,...,0.001902,-0.000036,0.001065,0.002172,-0.001851,-0.008063,0.002607,0.006083,0.002803,0.003414,0.000290,-0.001923,0.000518,0.000921,0.001426,0.000463,0.000771,-0.003004,0.003457,0.001103,0.000037,0.001370,-0.002295,-0.001499,0.000089,0.001533,0.000817,-0.000852,0.002113,0.002595,0.002711,-0.003520,-0.000372,-0.000967,0.002418,-0.003021,0.003196,0.000617,-0.001159,-0.001016,0.003047,-0.002059,-0.000130,-0.000355,0.000241,-0.000082,0.000102,0.000158,-0.000015,1.572708e-16
abolish,-0.000026,0.001074,0.001043,0.000487,0.001428,-0.002000,-0.000170,-0.000978,-0.003044,-0.000801,0.000572,0.000464,0.001020,0.000216,0.001030,0.000978,0.000585,0.000417,0.001163,0.000617,0.000076,0.001057,-0.001404,0.001515,0.001389,-0.000326,-0.001536,0.000743,-0.000167,-1.324527e-03,0.002198,-0.000682,-0.000642,0.001329,0.001343,-0.001171,-0.001282,-0.001172,0.001955,0.003918,-0.002743,-0.000993,0.000785,0.002039,-0.000449,0.002007,-0.000501,-0.000826,0.002440,0.000157,...,0.015148,0.063377,-0.011651,-0.024442,-0.042231,0.014179,0.007797,0.003815,0.004260,0.012622,0.007348,-0.013304,-0.008442,-0.010196,0.012246,-0.007285,-0.027646,0.007603,0.030754,0.003697,-0.003480,0.000432,0.009475,0.024741,-0.007916,0.002586,-0.000113,-0.006837,-0.010992,0.005963,0.003394,0.011453,0.000578,-0.004102,-0.000362,-0.002423,-0.000695,0.002347,0.000907,0.001122,-0.002045,0.005533,0.000479,0.000460,0.000011,0.000083,-0.000463,-0.000545,0.000026,-3.223868e-17
abolished,-0.001277,0.008414,0.000387,-0.002822,-0.000440,0.002749,0.001904,0.000331,0.002379,-0.000008,0.002022,-0.001308,-0.000524,-0.002290,-0.003527,-0.005588,-0.002279,-0.003369,-0.008301,0.000345,0.001720,0.004102,0.000927,-0.001083,0.001060,0.003985,0.002343,-0.005658,-0.000139,-1.147134e-03,-0.005532,0.003685,0.000838,0.001010,0.001420,-0.005876,0.000516,0.002493,0.006878,-0.002173,-0.003038,0.000488,-0.005333,-0.001762,0.004122,-0.001833,0.004517,-0.002819,0.000056,0.001975,...,-0.002412,0.001907,-0.000979,-0.004641,0.006368,0.003362,0.003985,0.004635,0.000414,-0.002483,-0.000900,0.003096,0.002811,0.000985,-0.000130,-0.000106,0.000451,-0.000411,0.002130,0.000069,-0.002343,0.000700,-0.000081,-0.001108,-0.000406,-0.000282,0.000347,-0.001104,-0.001309,-0.000469,-0.000484,0.000330,-0.000345,-0.001456,0.000481,0.000175,0.000247,-0.002825,-0.000244,-0.000043,-0.000012,-0.001063,0.000394,-0.000271,0.000072,0.000062,0.000118,-0.000047,0.000019,-5.536596e-17
abolition,-0.001204,0.001653,0.000684,-0.001382,0.005766,0.000891,-0.001720,0.001844,-0.000197,0.000748,0.000737,0.004222,0.000695,0.002029,0.000064,-0.003320,0.001128,-0.001379,-0.000681,-0.000554,0.001979,0.000608,0.001158,0.004303,0.000263,-0.001061,0.005490,0.002516,-0.000719,-3.113355e-03,0.001172,0.001751,-0.001812,0.000242,-0.001419,-0.001437,-0.000261,-0.002032,-0.000698,-0.001882,-0.002505,-0.000056,0.001667,-0.003008,0.001334,0.000325,0.005041,0.001670,-0.001227,-0.000864,...,0.014028,-0.003646,-0.005910,0.004242,-0.004951,-0.006008,-0.000120,-0.008679,-0.003799,0.000250,0.005900,-0.001394,-0.003750,0.000963,-0.002304,0.006615,-0.005780,0.009829,-0.023969,-0.039858,-0.018821,0.000068,0.000193,-0.013572,0.013324,0.038957,0.004889,-0.003395,0.005734,-0.002754,-0.000377,0.002901,0.000766,0.000158,0.001713,0.000481,0.002212,0.000978,-0.001922,-0.001099,-0.001847,0.004365,-0.000506,-0.000617,0.000290,0.000234,-0.000060,0.000454,-0.000151,5.955516e-17
about,0.003576,0.005403,-0.002190,-0.000449,-0.001668,0.008020,-0.011708,-0.003177,-0.008095,0.005383,-0.000854,-0.006117,0.003618,-0.003355,0.002332,0.011293,0.003196,-0.006146,0.000101,-0.013372,0.005427,0.001622,-0.002384,0.000828,-0.010989,-0.006785,-0.002229,-0.002270,-0.003734,-3.043058e-07,0.001443,-0.004645,-0.006590,-0.009795,0.001606,-0.001129,0.006578,-0.009761,0.000563,-0.007325,0.004858,-0.009999,0.002027,-0.006815,-0.011704,-0.003715,-0.008287,0.009509,0.004771,-0.008792,...,0.000429,0.005444,-0.001641,0.002462,-0.000708,-0.003773,0.003377,0.002498,0.005663,0.000906,-0.002405,-0.000958,-0.000922,-0.000297,0.001074,-0.001752,0.000768,0.001497,-0.001246,-0.000280,0.001779,-0.000465,-0.001280,-0.003999,0.000608,0.000052,0.002488,-0.005477,-0.002281,0.003685,0.002247,0.000698,0.000151,0.000041,-0.008472,0.002648,-0.002794,-0.001176,0.000119,-0.004245,-0.002191,0.000258,0.000106,-0.001287,-0.000124,0.000082,0.000304,-0.000128,0.000005,2.623451e-18
above,-0.003921,-0.007031,0.004625,-0.003691,-0.003743,0.000496,0.000699,-0.004768,-0.009051,0.001423,-0.002207,0.001479,0.002156,-0.004523,0.004814,-0.001200,0.002815,-0.002899,0.003490,-0.000735,0.000859,0.000714,0.003920,0.002697,0.001424,-0.002343,-0.001488,0.004405,-0.004483,-8.068764e-04,0.003642,-0.006771,-0.001120,-0.001768,0.009216,-0.004402,-0.004411,0.000816,-0.005537,0.010766,-0.005811,-0.002399,0.010721,-0.006745,0.002435,-0.002488,-0.000440,-0.004894,0.002070,0.009444,...,0.001981,0.000745,-0.000094,0.001955,0.001194,-0.001062,0.003383,-0.000421,-0.003990,0.004652,0.000267,-0.000531,-0.001701,0.002095,0.000683,-0.002656,0.000797,0.001256,0.000384,0.000520,-0.000459,-0.001478,-0.000888,0.000366,0.000527,0.002637,-0.001567,0.004019,-0.004945,0.001292,0.000015,0.001504,0.000105,-0.001843,0.000441,-0.000055,-0.000645,-0.000922,0.000254,-0.000373,0.001556,0.000526,0.000158,0.000404,0.000119,0.000247,0.000051,0.000092,0.000036,8.644643e-17
abroad,0.009625,-0.002352,-0.007156,0.000828,-0.009116,-0.000538,0.011277,-0.002904,-0.003912,0.000906,-0.008579,0.017787,-0.002943,-0.002473,-0.001433,0.007033,0.006439,-0.007928,-0.000059,-0.001856,0.002003,-0.002374,0.002280,0.005757,0.006750,0.015076,-0.008347,0.012647,0.005539,9.182658e-03,0.004473,0.004921,0.004516,-0.007503,0.016199,-0.013220,0.004738,-0.005479,-0.012325,0.005314,0.008217,-0.004983,-0.007593,-0.007700,-0.014032,0.003486,-0.002415,0.001139,-0.003930,-0.002720,...,-0.000161,-0.000403,-0.000474,-0.000028,0.000153,0.002929,-0.000985,-0.001513,0.001371,0.000239,0.004636,0.000490,0.000629,-0.002135,-0.001645,0.000840,-0.001222,0.000552,-0.000033,-0.001827,-0.000367,-0.000097,0.000455,0.001905,-0.000567,-0.000374,0.000444,-0.000995,-0.001050,-0.000709,0.000806,-0.000382,0.000091,-0.000410,0.001185,-0.000206,0.001393,0.000363,-0.000095,0.000848,0.000865,-0.000134,0.000106,0.000908,0.000070,-0.000156,0.000032,0.000055,-0.000014,2.109951e-17
abrogated,0.001503,-0.006668,0.000145,-0.003105,0.002830,0.013723,0.018888,0.017892,0.005999,-0.000739,0.001496,-0.009959,-0.027022,0.001371,-0.028107,-0.014806,-0.012408,0.001457,-0.013361,-0.008595,-0.004715,-0.009012,0.001802,-0.030166,0.016405,0.015315,-0.003022,-0.009616,0.008186,2.154676e-03,-0.014612,-0.024230,-0.006070,-0.023796,-0.002254,-0.017263,-0.002276,0.007043,0.012051,-0.003636,-0.022941,0.014894,-0.000440,0.013737,0.012103,-0.008644,-0.005597,0.022321,-0.038696,0.020143,...,0.000408,-0.000479,0.000749,-0.000228,-0.000219,0.000063,-0.000889,0.000054,-0.000251,0.000008,-0.000784,-0.000413,0.000034,0.000216,-0.000405,-0.000376,-0.000367,0.000151,-0.000662,-0.000475,-0.000411,-0.000145,0.000559,-0.000135,0.000260,0.000536,-0.000294,0.000184,-0.000465,-0.000163,0.000235,0.000265,-0.000081,-0.000224,-0.000076,0.000631,0.000355,0.000011,-0.000021,0.000023,-0.000265,-0.000193,-0.000057,0.000027,-0.000045,0.000008,-0.000010,-0.000046,0.000013,3.401165e-18

## LDA DTM

This section inspects the LDA count matrix used as the source document-term table for topic modeling.

In [9]:
LDA_DTM = inspect_table(
    section='LDA DTM',
    box_url='https://virginia.box.com/shared/static/mfa6gtj63xpqedqjn2e4r394mx1y79ay',
    local_path='lda_dtm.parquet',
    file_format='parquet'
)

Section: LDA DTM
Box URL: https://virginia.box.com/shared/static/mfa6gtj63xpqedqjn2e4r394mx1y79ay
Local file: lda_dtm.parquet
Loaded from: Box download
Format: parquet
Shape: 33,220 rows x 3,504 columns
Number of observations: 33,220
Column names:
country_id, article_n, abandonment, abeyance, abide, abilities, ability, abolition, abroad,
abrogation, absence, absences, absent, absolute, abuse, abuses, accept, acceptance, accepts, access,
accessibility, accession, accident, accidents, accommodation, accomplices, accomplishment, accord,
accordance, accordingly, accords, account, accountability, accounting, accounts, accredit,
accreditation, accumulation, accusation, accusations, accused, achievement, achievements,
acknowledgement, acknowledgment, acquisition, acquittal, act, acting, action, actions, activities,
activity, acts, ad, adaptation, adaptations, addition, additions, address, addresses, adequate,
adherence, adjournment, adjudication, adjustment, adjustments, administer, administration,
administrations, administrative, administrator, administrators, admissibility, admission,
adolescents, adopt, adopted, adoption, adopts, adult, adults, advance, advancement, advances,
advantage, advantages, advertising, advice, advise, adviser, advisers, advocate, advocates, aegis,
affairs, affection, affiliation, affinity, affirm, affirmation, aforesaid, age, aged, agencies,
agency, agenda, agent, agents, ages, aggravation, aggregate, aggression, agreement, agreements,
agricultural, agriculture, aid, aids, aim, aims, air, aircraft, airports, airspace, al, alcohol,
alia, alien, alienation, aliens, allegation, allegations, alleges, allegiance, alliance, alliances,
allocation, allocations, allotment, allowance, allowances, alter, alteration, alterations,
alternate, alternates, alternation, alternative, ambassadors, ambit, amend, amended, amending,
amendment, amendments, amity, ammunition, amnesties, amnesty, amortisation, amortization, amounts,
amparo, analysis, ancestors, animal, animals, announce, announcement, annul, annulment, answer,
answers, anthem, anybody, apart, apparatus, appeal, appeals, appear, appearance, appellate,
applicability, applicable, applicant, applicants, application, applications, applies, apply,
appoint, appointees, appointing, appointment, appointments, appoints, apportionment, appraisal,
appreciation, apprehension, approach, appropriate, appropriation, appropriations, approval, approve,
approves, aptitude, arbitration, archives, area, areas, arguments, arise, arises, arising, armed,
armies, arms, army, arrange, arrangement, arrangements, arrest, arrested, art, artistic, artists,
arts, ascertains, aspect, aspects, aspirations, assault, assemblies, assembly, assent, assents,
assessment, assessments, assessors, asset, assets, assign, assignment, assignments, assist,
assistance, assistant, assistants, associate, association, associations, assumes, assumption,
assurance, assure, assures, asylum, attachment, attack, attacks, attainment, attempt, attempts,
attend, attendance, attention, attitude, attorney, attorneys, attributes, attribution, attributions,
audience, audit, auditing, auditor, auditors, audits, augmentation, autarchies, authenticity,
author, authorisation, authorise, authorises, authorities, authority, authorization, authorizations,
authorize, authors, autonomies, autonomy, availability, aviation, avoidance, award, awards,
awareness, background, bail, balance, balances, ballot, balloting, ballots, ban, band, bands, bank,
banking, bankrupt, banks, bar, bargaining, barracks, barrister, base, bases, basis, beaches, bearer,
bearers, bearing, begin, beginning, begins, behalf, behavior, behaviour, beings, belief, beliefs,
belong, belonging, belongs, bench, beneficial, beneficiaries, benefit, benefits, beverages, bidding,
bills, binding, biodiversity, birth, births, blessings, blindness, blood, blue, board, boards,
bodies, body, bond, bonds, bonus, book, books, border, borders, born, borrowing, bound, boundaries,
boundary, bounds, branch, branches, breach, breaches, break, breakdown, bribery, bridges, bringing,
broadcast, broadcasting, broadcasts, budget, budgeting, budgets, building, buildings, burden,
burdens, bureau, burial, business, businesses, bye, bylaws, cabinet, cadres, calamities, calamity,
calculation, calendar, called, camera, campaign, campaigns, cancellation, candidacies, candidacy,
candidate, candidates, candidature, candidatures, canton, cantons, capabilities, capability,
capacities, capacity, capital, card, care, career, careers, caretaker, cargo, carriage, carry, case,
cases, cash, cassation, cast, caste, casting, catastrophe, catastrophes, categories, category,
cause, causes, cease, ceases, ceasing, celebration, censorship, censure, census, cent, center,
centers, centre, centres, centum, centuries, ceremonies, ceremony, certainty, certificate,
certificates, certification, certifies, certiorari, cessation, cession, chain, chair, chairman,
chairmanship, chairmen, chairperson, chairpersons, challenge, challenges, chamber, chambers, change,
changes, changing, channels, character, characteristics, charge, charged, charges, charity, charter,
charters, checks, chemical, chief, chiefs, child, childbirth, childhood, children, choice, choices,
choosing, chosen, church, churches, circle, circulars, circulation, circumscription,
circumscriptions, circumstance, circumstances, cities, citizen, citizenry, citizens, citizenship,
city, civic, civil, civilian, civilians, civilization, civilizations, claim, claims, clarification,
class, classes, classification, clause, clauses, clemency, clerk, climate, close, closing, closure,
clothing, coalition, coalitions, coasts, coat, code, codes, coercion, coexistence, cognate,
cognizance, cohesion, coins, collaboration, collect, collection, collections, collective,
collectives, collectivities, collectivity, college, colleges, collegiate, colonialism, color,
colors, colour, colours, combat, combatants, combination, command, commander, commanders, commence,
commenced, commencement, commences, commencing, commensurate, comment, comments, commerce,
commercial, commercialization, commission, commissioner, commissioners, commissions, commitment,
commitments, commits, committed, committee, committees, commodities, common, communal, commune,
communes, communicate, communication, communications, communities, community, commutation, commute,
companies, company, comparison, compatibility, compensation, compensations, compensatory,
competence, competences, competencies, competency, competent, competition, competitiveness,
compilation, complainant, complaint, complaints, completion, compliance, complies, comply,
component, components, composition, comprises, comprising, compromise, compulsion, compulsorily,
compulsory, computing, concealment, concentration, concept, conception, concepts, concern,
concerned, concerning, concerns, concert, concession, concessions, conciliation, conclude,
conclusion, conclusions, concurrence, concurrent, concurs, condemnation, condition, conditions,
conduct, conducting, confederation, confer, conference, conferment, conferring, confers, confession,
confessions, confidence, confidentiality, confinement, confirm, confirmation, confiscation,
conflict, conflicts, conformity, congress, congresses, congressmen, conjunction, connection,
connexion, consanguinity, conscience, consciousness, consensus, consent, consents, consequence,
consequences, consequent, conservation, conserve, consider, consideration, considerations,
considers, consist, consistency, consistent, consisting, consists, consolidation, conspiracy,
constituencies, constituency, constituent, constituents, constitute, constituted, constitutes,
constitution, constitutional, constitutionality, constitutions, constraint, constraints,
construction, consuls, consult, consultation, consultations, consumer, consumers, consumption,
contact, contempt, content, contents, contest, context, contingencies, contingent, continuance,
continuation, continue, continuity, contract, contracting, contractors, contracts, contradiction,
contrary, contravention, contribute, contribution, contributions, contributory, control, controls,
controversies, controversy, convene, convenes, convenience, convenient, convening, convention,
conventions, conversations, conversion, conviction, convictions, convocation, cooperate,
cooperation, cooperative, cooperatives, coordinate, coordinating, coordination, copies, copy,
copyright, copyrights, core, corporate, corporation, corporations, corps, corpus, correction,
corrections, correspond, correspondence, corresponding, corresponds, corruption, cost, costs,
council, councillors, councilor, councilors, councils, counsel, count, counter, countersignature,
counties, counting, countries, country, county, coup, course, courses, court, courts, covenant,
covenants, coverage, create, creates, creation, creations, creativity, credentials, credit,
creditors, credits, creed, crescent, crime, crimes, criminal, criminals, crisis, criteria,
criterion, criticism, cross, cruel, cruelty, culpability, cult, cultivation, cults, cultural,
culture, cultures, currency, curricula, custody, custom, customs, cycle, da, damage, damages,
danger, dangers, data, database, date, dates, daughters, day, days, deadline, deadlines, deal,
dealings, deals, dealt, death, deaths, debate, debates, debt, debts, decency, decentralisation,
decentralization, decentralized, decide, decides, decision, decisions, declaration, declarations,
declare, declares, declaring, decline, decorations, decrease, decree, decreed, decrees, deductions,
deed, deeds, defamation, default, defect, defects, defence, defend, defendant, defendants, defender,
defenders, defense, deficiency, deficit, define, definition, degradation, degrading, degree,
degrees, delay, delays, delegate, delegates, delegation, delegations, deletion, deliberate,
deliberation, deliberations, delicto, delimitation, deliver, delivery, demand, demands, demarcation,
democracy, democratic, democratization, demonstration, demonstrations, denial, denomination,
denominations, denounce, density, denunciation, denunciations, department, departmental,
departments, departure, dependants, dependence, dependencies, dependency, dependent, dependents,
deployment, deportation, deposit, deposits, deprivation, deprive, depriving, deputies, deputy,
derogation, descendants, descent, description, descriptions, design, designate, designates,
designation, designations, desirability, desire, despatch, destination, destiny, destruction,
details, detained, detainee, detention, determination, determine, determines, detriment,
detrimental, develop, development, deviation, device, devolution, di, dialogue, dictates,
dictatorship, dies, difference, differences, difficulties, difficulty, diffusion, dignity,
diligence, dimensions, diminution, direct, direction, directions, directive, directives, directly,
director, directors, directs, disabilities, disability, disabled, disadvantage, disagreement,
disappearance, disapproval, disaster, disasters, disbursement, disbursements, discharge,
disciplinary, discipline, disclosure, discontinuance, discontinue, discovery, discretion,
discrimination, discriminatory, discussion, discussions, disease, diseases, dishonesty, dismiss,
dismissal, dismisses, disorder, dispatch, disposal, dispose, disposition, dispositions, dispute,
disputes, disqualification, disqualifications, disruption, disseminate, dissemination, disseminator,
dissolution, dissolve, dissolved, distance, distinction, distinctions, distribution, district,
districts, disturbance, disturbances, diverse, diversion, diversity, division, divisions, divorce,
doctor, doctors, doctrine, document, documentation, documents, dollars, domain, domains, domicile,
domination, dominion, donation, donations, doors, doubt, doubts, draft, drafting, drafts, draw,
drawing, drawn, drug, drugs, du, dues, duly, duration, duties, duty, dwelling, earlier, earnings,
earth, economic, economies, economy, ecosystems, edicts, editor, editorial, educate, education,
educational, effect, effective, effectiveness, effects, efficacy, efficiency, efficient, effort,
efforts, eighteen, elaboration, elderly, elect, elected, election, elections, elector, electorate,
electors, electricity, elects, element, elements, eligibility, eliminate, elimination, emanates,
embezzlement, emblem, emblems, emergence, emergencies, emergency, emigration, emir, emirates,
emission, emolument, emoluments, emphasis, employee, employees, employer, employers, employment,
employments, en, enabling, enact, enactment, enactments, enacts, encourage, encouragement,
encourages, encroachments, end, endeavors, endeavour, endorsement, ends, enemy, energy, enforce,
enforcement, engage, engagement, engagements, enhancement, enjoy, enjoyment, enquiry, enrichment,
enrolment, ensuing, ensures, enter, enterprise, enterprises, enters, entertainment, entirety,
entities, entitlement, entitlements, entity, entrance, entries, entry, enumeration, environment,
envoy, envoys, epidemic, epidemics, equal, equality, equalization, equals, equilibrium, equipment,
equity, equivalent, eradication, error, errors, escape, espionage, essence, establish, established,
establishes, establishing, establishment, establishments, estate, estates, estimate, estimates,
ethics, ethnic, ethnicity, evaluation, event, events, evidence, evolution, ex, examination,
examinations, examine, exceeds, exception, exceptions, excess, exchange, exchanges, excise,
exclusion, excuse, execute, execution, executive, executives, exemption, exemptions, exercise,
exercises, exercising, exhaustion, exhibition, exhibitions, exigencies, exist, existence, exists,
exit, expansion, expediency, expedient, expenditure, expenditures, expense, expenses, experience,
experimentation, experiments, expert, expertise, experts, expiration, expires, expiry, explanation,
explanations, exploitation, exploration, export, exportation, exports, express, expressed,
expression, expressions, expropriation, expropriations, expulsion, extend, extends, extension,
extensions, extent, extinction, extraction, extradition, face, facie, facilitation, facilities,
fact, faction, factions, facto, factor, factories, factors, facts, faculties, faculty, fail, fails,
failure, fair, fairness, faith, faithfully, faithfulness, faiths, fall, falls, families, family,
farm, farmer, farmers, farming, fashion, father, fatherhood, fatherland, fathers, fault, faults,
fauna, favor, favour, fear, features, federate, federation, fee, feelings, fees, felonies, felony,
female, feminine, fidelity, field, fields, fifth, fifths, fight, figure, figures, file, files,
filing, filling, finance, finances, financial, financing, finding, findings, fine, fines, firm,
firms, fisheries, fishing, fit, fix, fixing, flag, flagrante, flood, floor, flora, flow, fn,
followers, following, follows, food, foodstuffs, force, forces, foregoing, foreign, foreigner,
foreigners, forest, forestry, forests, forfeiture, form, formalities, formation, formations, forms,
formula, formulate, formulation, forth, forthwith, forum, foster, fostering, foundation,
foundations, fourth, fourths, fraction, frame, framework, franchise, fraternity, fraud, free,
freedom, freedoms, freely, frequencies, friend, friends, friendship, frontier, frontiers, fruits,
fuels, fulfillment, fulfilment, function, functionaries, functionary, functioning, functions, fund,
funding, funds, furtherance, future, gain, gains, games, gas, gathering, gazette, gender, general,
generality, generally, generation, generations, genocide, gift, gifts, given, glory, goal, goals,
gold, good, goods, governance, governing, government, governmental, governments, governor,
governorates, governors, grade, grades, grandparents, grant, granting, grants, grassroots,
gratuities, gratuity, grave, gravity, green, grievances, ground, grounds, group, groups, growth,
guarantee, guaranteed, guaranteeing, guarantees, guaranties, guarantor, guard, guardian, guardians,
guardianship, guidance, guidelines, guilt, guilty, habeas, habitat, half, hand, handicapped,
handling, hands, happiness, hardship, harm, harmonization, harmony, hatred, head, heading, headings,
headquarters, heads, health, healthcare, healthy, hear, hearing, hearings, heir, heirs, held, help,
hereinafter, hereof, heritage, heroes, heroic, hierarchy, highways, hindrance, historic, historical,
history, hoc, hold, holder, holders, holding, holdings, holiday, holidays, home, homeland, homes,
honest, honestly, honesty, honor, honors, honour, honours, hospital, hospitals, hostile,
hostilities, hostility, hour, hours, house, household, houses, housing, human, humane, humanity,
hunting, husband, husbandry, hydrocarbons, hygiene, ideal, ideals, ideas, identification,
identities, identity, ideology, ignorance, ii, iii, ill, illegality, illiteracy, illness, image,
images, imbalances, immediately, immigration, immunities, immunity, impact, impacts, impartial,
impartiality, impeachment, impediment, impediments, implement, implementation, implements,
implication, import, importance, importation, imports, imposes, imposing, imposition, impossibility,
imposts, imprisonment, improvement, improvements, inability, inauguration, incapable,
incapacitation, incapacity, incentives, incident, incidental, incitement, include, includes,
including, inclusion, inclusive, income, incomes, incompatibilities, incompatibility, incompetence,
inconsistency, inconsistent, incorporation, increase, increases, incumbent, indebtedness,
indefinite, indemnification, indemnities, indemnity, independence, independent, independently,
indication, indictment, individual, individuals, indivisibility, industrial, industrialization,
industries, industry, ineligibilities, ineligibility, inequalities, inequality, infirmity,
infliction, influence, influences, inform, information, infraction, infractions, infrastructure,
infringe, infringement, infringements, ingwenyama, inhabitant, inhabitants, inherent, inheritance,
inhuman, inhumane, initiate, initiation, initiative, initiatives, injunction, injuries, injury,
injustice, inland, innocence, innovation, inquire, inquiries, inquiry, insane, inscription,
insertion, insignia, insofar, insolvent, inspection, inspections, installation, installations,
installments, instance, instances, institute, institutes, institution, institutions, instruction,
instructions, instrument, instruments, insurance, insurrection, integration, integrity,
intellectual, intellectuals, intelligence, intent, intention, inter, interaction, interdependence,
interdiction, interests, interference, interim, interior, intermediary, interpellation,
interpellations, interpretation, interpreter, interrogation, interruption, interval, intervals,
intervene, intervenes, intervening, intervention, interventions, intimacy, intimidation,
intolerance, introduction, invalidity, invasion, invention, inventions, inventors, investigate,
investigating, investigation, investigations, investiture, investment, investments, investors,
inviolability, invitation, involvement, irregularities, irregularity, irrespective, irrigation,
island, islands, isolation, issuance, issue, issues, issuing, item, items, iv, jeopardy, job, jobs,
join, joint, jointly, journal, journalists, journey, judge, judgement, judgements, judges, judgment,
judgments, judicature, judicial, judiciary, jure, juridical, juries, jurisdiction, jurisdictions,
jurisprudence, jurist, jurists, jurors, jury, just, justice, justices, justification, kin, kind,
kinds, king, knowing, knowledge, labor, labour, lack, lakes, land, lands, language, languages,
lapse, lapses, later, latest, law, lawful, lawfulness, laws, lawsuit, lawsuits, lawyer, lawyers,
lay, leader, leaders, leadership, learning, lease, leases, leave, leaves, left, legality, legislate,
legislation, legislative, legislator, legislators, legislature, legislatures, legitimacy, leisure,

,country_id,article_n,abandonment,abeyance,abide,abilities,ability,abolition,abroad,abrogation,absence,absences,absent,absolute,abuse,abuses,accept,acceptance,accepts,access,accessibility,accession,accident,accidents,accommodation,accomplices,accomplishment,accord,accordance,accordingly,accords,account,accountability,accounting,accounts,accredit,accreditation,accumulation,accusation,accusations,accused,achievement,achievements,acknowledgement,acknowledgment,acquisition,acquittal,act,acting,action,...,weeks,weight,weights,welfare,wellbeing,whatsoever,whereof,whichever,whilst,white,wider,widow,widows,width,wife,wireless,wisdom,wish,wishes,withdrawal,withdrawals,withdrawn,withheld,withhold,withholding,witness,witnesses,woman,women,word,wording,words,work,worker,workers,working,workplace,works,world,worship,worth,writ,writing,writs,year,years,yellow,youth,zone,zones
0,Afghanistan,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Afghanistan,2,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Afghanistan,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Afghanistan,4,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Afghanistan,5,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,Afghanistan,6,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,Afghanistan,7,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,Afghanistan,8,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,Afghanistan,9,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,Afghanistan,10,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## LDA TOPIC

This section inspects the LDA topic summary table that lists the modeled topics and their top terms.

In [10]:
LDA_TOPIC = inspect_table(
    section='LDA TOPIC',
    box_url='https://virginia.box.com/shared/static/3tzt3hncq9z39786y93k4mvqw71sw6vt',
    local_path='lda_topics.parquet',
    file_format='parquet'
)

Section: LDA TOPIC
Box URL: https://virginia.box.com/shared/static/3tzt3hncq9z39786y93k4mvqw71sw6vt
Local file: lda_topics.parquet
Loaded from: Box download
Format: parquet
Shape: 20 rows x 3 columns
Number of observations: 20
Column names:
top_terms, doc_weight_mean, dominant_doc_count

,top_terms,doc_weight_mean,dominant_doc_count
topic_id,,,
T02,law laws courts matters jurisdiction decisions rules,0.079318,48
T13,office member election members term years person,0.073307,16
T15,rights people freedoms law citizens principles security,0.071653,29
T18,development education law resources services health protection,0.063536,24
T04,office person functions accordance advice appointment authority,0.060593,30
T00,days period law date time day force,0.057705,5
T06,duties functions law exercise members accordance powers,0.055221,3
T10,members majority vote votes election candidates number,0.054429,7
T17,government service power law authority powers legislation,0.053186,11
T19,members number session sessions referendum representatives law,0.051390,9

## LDA THETA

This section inspects the LDA `THETA` table containing document-by-topic weights.

In [11]:
LDA_THETA = inspect_table(
    section='LDA THETA',
    box_url='https://virginia.box.com/shared/static/oarntoraxn1mjwcuyiqdvvsvto4gv1si',
    local_path='lda_theta.parquet',
    file_format='parquet'
)

Section: LDA THETA
Box URL: https://virginia.box.com/shared/static/oarntoraxn1mjwcuyiqdvvsvto4gv1si
Local file: lda_theta.parquet
Loaded from: Box download
Format: parquet
Shape: 33,220 rows x 22 columns
Number of observations: 33,220
Column names:
country_id, article_n, T00, T01, T02, T03, T04, T05, T06, T07, T08, T09, T10, T11, T12, T13, T14,
T15, T16, T17, T18, T19

,country_id,article_n,T00,T01,T02,T03,T04,T05,T06,T07,T08,T09,T10,T11,T12,T13,T14,T15,T16,T17,T18,T19
0,Afghanistan,1,0.001042,0.001042,0.001042,0.062903,0.001042,0.001042,0.001042,0.001042,0.050439,0.001042,0.001042,0.001042,0.001042,0.001042,0.001042,0.868950,0.001042,0.001042,0.001042,0.001042
1,Afghanistan,2,0.016667,0.016667,0.016667,0.016667,0.016667,0.016667,0.016667,0.016667,0.683333,0.016667,0.016667,0.016667,0.016667,0.016667,0.016667,0.016667,0.016667,0.016667,0.016667,0.016667
2,Afghanistan,3,0.005556,0.005556,0.165357,0.222067,0.005556,0.122814,0.164047,0.005556,0.005556,0.005556,0.005556,0.242380,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556
3,Afghanistan,4,0.012500,0.012500,0.012500,0.012500,0.012500,0.012500,0.012500,0.012500,0.012500,0.012500,0.012500,0.479471,0.012500,0.012500,0.012500,0.012500,0.295529,0.012500,0.012500,0.012500
4,Afghanistan,5,0.002778,0.002778,0.002778,0.002778,0.002778,0.002778,0.002778,0.255626,0.002778,0.002778,0.002778,0.002778,0.250175,0.002778,0.002778,0.446977,0.002778,0.002778,0.002778,0.002778
5,Afghanistan,6,0.004545,0.004545,0.004545,0.004545,0.004545,0.004545,0.265707,0.004545,0.130454,0.004545,0.004545,0.004545,0.004545,0.004545,0.004545,0.526566,0.004545,0.004545,0.004545,0.004545
6,Afghanistan,7,0.002941,0.002941,0.002941,0.002941,0.002941,0.002941,0.002941,0.002941,0.053735,0.002941,0.002941,0.002941,0.002941,0.002941,0.002941,0.741467,0.002941,0.002941,0.154798,0.002941
7,Afghanistan,8,0.005556,0.005556,0.005556,0.005556,0.005556,0.256323,0.005556,0.005556,0.240068,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556,0.409164,0.005556
8,Afghanistan,9,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556,0.123324,0.005556,0.005556,0.005556,0.005556,0.005556,0.005556,0.776676,0.005556,0.005556,0.005556,0.005556
9,Afghanistan,10,0.006250,0.006250,0.006250,0.006250,0.006250,0.006250,0.006250,0.006250,0.116168,0.006250,0.006250,0.006250,0.006250,0.006250,0.006250,0.006250,0.006250,0.006250,0.771332,0.006250

## LDA PHI

This section inspects the LDA `PHI` table containing topic-by-term weights.

In [12]:
LDA_PHI = inspect_table(
    section='LDA PHI',
    box_url='https://virginia.box.com/shared/static/m8epjv3bddqkak7lt7qydwlziwq2euu5',
    local_path='lda_phi.parquet',
    file_format='parquet'
)

Section: LDA PHI
Box URL: https://virginia.box.com/shared/static/m8epjv3bddqkak7lt7qydwlziwq2euu5
Local file: lda_phi.parquet
Loaded from: Box download
Format: parquet
Shape: 20 rows x 3,502 columns
Number of observations: 20
Column names:
abandonment, abeyance, abide, abilities, ability, abolition, abroad, abrogation, absence, absences,
absent, absolute, abuse, abuses, accept, acceptance, accepts, access, accessibility, accession,
accident, accidents, accommodation, accomplices, accomplishment, accord, accordance, accordingly,
accords, account, accountability, accounting, accounts, accredit, accreditation, accumulation,
accusation, accusations, accused, achievement, achievements, acknowledgement, acknowledgment,
acquisition, acquittal, act, acting, action, actions, activities, activity, acts, ad, adaptation,
adaptations, addition, additions, address, addresses, adequate, adherence, adjournment,
adjudication, adjustment, adjustments, administer, administration, administrations, administrative,
administrator, administrators, admissibility, admission, adolescents, adopt, adopted, adoption,
adopts, adult, adults, advance, advancement, advances, advantage, advantages, advertising, advice,
advise, adviser, advisers, advocate, advocates, aegis, affairs, affection, affiliation, affinity,
affirm, affirmation, aforesaid, age, aged, agencies, agency, agenda, agent, agents, ages,
aggravation, aggregate, aggression, agreement, agreements, agricultural, agriculture, aid, aids,
aim, aims, air, aircraft, airports, airspace, al, alcohol, alia, alien, alienation, aliens,
allegation, allegations, alleges, allegiance, alliance, alliances, allocation, allocations,
allotment, allowance, allowances, alter, alteration, alterations, alternate, alternates,
alternation, alternative, ambassadors, ambit, amend, amended, amending, amendment, amendments,
amity, ammunition, amnesties, amnesty, amortisation, amortization, amounts, amparo, analysis,
ancestors, animal, animals, announce, announcement, annul, annulment, answer, answers, anthem,
anybody, apart, apparatus, appeal, appeals, appear, appearance, appellate, applicability,
applicable, applicant, applicants, application, applications, applies, apply, appoint, appointees,
appointing, appointment, appointments, appoints, apportionment, appraisal, appreciation,
apprehension, approach, appropriate, appropriation, appropriations, approval, approve, approves,
aptitude, arbitration, archives, area, areas, arguments, arise, arises, arising, armed, armies,
arms, army, arrange, arrangement, arrangements, arrest, arrested, art, artistic, artists, arts,
ascertains, aspect, aspects, aspirations, assault, assemblies, assembly, assent, assents,
assessment, assessments, assessors, asset, assets, assign, assignment, assignments, assist,
assistance, assistant, assistants, associate, association, associations, assumes, assumption,
assurance, assure, assures, asylum, attachment, attack, attacks, attainment, attempt, attempts,
attend, attendance, attention, attitude, attorney, attorneys, attributes, attribution, attributions,
audience, audit, auditing, auditor, auditors, audits, augmentation, autarchies, authenticity,
author, authorisation, authorise, authorises, authorities, authority, authorization, authorizations,
authorize, authors, autonomies, autonomy, availability, aviation, avoidance, award, awards,
awareness, background, bail, balance, balances, ballot, balloting, ballots, ban, band, bands, bank,
banking, bankrupt, banks, bar, bargaining, barracks, barrister, base, bases, basis, beaches, bearer,
bearers, bearing, begin, beginning, begins, behalf, behavior, behaviour, beings, belief, beliefs,
belong, belonging, belongs, bench, beneficial, beneficiaries, benefit, benefits, beverages, bidding,
bills, binding, biodiversity, birth, births, blessings, blindness, blood, blue, board, boards,
bodies, body, bond, bonds, bonus, book, books, border, borders, born, borrowing, bound, boundaries,
boundary, bounds, branch, branches, breach, breaches, break, breakdown, bribery, bridges, bringing,
broadcast, broadcasting, broadcasts, budget, budgeting, budgets, building, buildings, burden,
burdens, bureau, burial, business, businesses, bye, bylaws, cabinet, cadres, calamities, calamity,
calculation, calendar, called, camera, campaign, campaigns, cancellation, candidacies, candidacy,
candidate, candidates, candidature, candidatures, canton, cantons, capabilities, capability,
capacities, capacity, capital, card, care, career, careers, caretaker, cargo, carriage, carry, case,
cases, cash, cassation, cast, caste, casting, catastrophe, catastrophes, categories, category,
cause, causes, cease, ceases, ceasing, celebration, censorship, censure, census, cent, center,
centers, centre, centres, centum, centuries, ceremonies, ceremony, certainty, certificate,
certificates, certification, certifies, certiorari, cessation, cession, chain, chair, chairman,
chairmanship, chairmen, chairperson, chairpersons, challenge, challenges, chamber, chambers, change,
changes, changing, channels, character, characteristics, charge, charged, charges, charity, charter,
charters, checks, chemical, chief, chiefs, child, childbirth, childhood, children, choice, choices,
choosing, chosen, church, churches, circle, circulars, circulation, circumscription,
circumscriptions, circumstance, circumstances, cities, citizen, citizenry, citizens, citizenship,
city, civic, civil, civilian, civilians, civilization, civilizations, claim, claims, clarification,
class, classes, classification, clause, clauses, clemency, clerk, climate, close, closing, closure,
clothing, coalition, coalitions, coasts, coat, code, codes, coercion, coexistence, cognate,
cognizance, cohesion, coins, collaboration, collect, collection, collections, collective,
collectives, collectivities, collectivity, college, colleges, collegiate, colonialism, color,
colors, colour, colours, combat, combatants, combination, command, commander, commanders, commence,
commenced, commencement, commences, commencing, commensurate, comment, comments, commerce,
commercial, commercialization, commission, commissioner, commissioners, commissions, commitment,
commitments, commits, committed, committee, committees, commodities, common, communal, commune,
communes, communicate, communication, communications, communities, community, commutation, commute,
companies, company, comparison, compatibility, compensation, compensations, compensatory,
competence, competences, competencies, competency, competent, competition, competitiveness,
compilation, complainant, complaint, complaints, completion, compliance, complies, comply,
component, components, composition, comprises, comprising, compromise, compulsion, compulsorily,
compulsory, computing, concealment, concentration, concept, conception, concepts, concern,
concerned, concerning, concerns, concert, concession, concessions, conciliation, conclude,
conclusion, conclusions, concurrence, concurrent, concurs, condemnation, condition, conditions,
conduct, conducting, confederation, confer, conference, conferment, conferring, confers, confession,
confessions, confidence, confidentiality, confinement, confirm, confirmation, confiscation,
conflict, conflicts, conformity, congress, congresses, congressmen, conjunction, connection,
connexion, consanguinity, conscience, consciousness, consensus, consent, consents, consequence,
consequences, consequent, conservation, conserve, consider, consideration, considerations,
considers, consist, consistency, consistent, consisting, consists, consolidation, conspiracy,
constituencies, constituency, constituent, constituents, constitute, constituted, constitutes,
constitution, constitutional, constitutionality, constitutions, constraint, constraints,
construction, consuls, consult, consultation, consultations, consumer, consumers, consumption,
contact, contempt, content, contents, contest, context, contingencies, contingent, continuance,
continuation, continue, continuity, contract, contracting, contractors, contracts, contradiction,
contrary, contravention, contribute, contribution, contributions, contributory, control, controls,
controversies, controversy, convene, convenes, convenience, convenient, convening, convention,
conventions, conversations, conversion, conviction, convictions, convocation, cooperate,
cooperation, cooperative, cooperatives, coordinate, coordinating, coordination, copies, copy,
copyright, copyrights, core, corporate, corporation, corporations, corps, corpus, correction,
corrections, correspond, correspondence, corresponding, corresponds, corruption, cost, costs,
council, councillors, councilor, councilors, councils, counsel, count, counter, countersignature,
counties, counting, countries, country, county, coup, course, courses, court, courts, covenant,
covenants, coverage, create, creates, creation, creations, creativity, credentials, credit,
creditors, credits, creed, crescent, crime, crimes, criminal, criminals, crisis, criteria,
criterion, criticism, cross, cruel, cruelty, culpability, cult, cultivation, cults, cultural,
culture, cultures, currency, curricula, custody, custom, customs, cycle, da, damage, damages,
danger, dangers, data, database, date, dates, daughters, day, days, deadline, deadlines, deal,
dealings, deals, dealt, death, deaths, debate, debates, debt, debts, decency, decentralisation,
decentralization, decentralized, decide, decides, decision, decisions, declaration, declarations,
declare, declares, declaring, decline, decorations, decrease, decree, decreed, decrees, deductions,
deed, deeds, defamation, default, defect, defects, defence, defend, defendant, defendants, defender,
defenders, defense, deficiency, deficit, define, definition, degradation, degrading, degree,
degrees, delay, delays, delegate, delegates, delegation, delegations, deletion, deliberate,
deliberation, deliberations, delicto, delimitation, deliver, delivery, demand, demands, demarcation,
democracy, democratic, democratization, demonstration, demonstrations, denial, denomination,
denominations, denounce, density, denunciation, denunciations, department, departmental,
departments, departure, dependants, dependence, dependencies, dependency, dependent, dependents,
deployment, deportation, deposit, deposits, deprivation, deprive, depriving, deputies, deputy,
derogation, descendants, descent, description, descriptions, design, designate, designates,
designation, designations, desirability, desire, despatch, destination, destiny, destruction,
details, detained, detainee, detention, determination, determine, determines, detriment,
detrimental, develop, development, deviation, device, devolution, di, dialogue, dictates,
dictatorship, dies, difference, differences, difficulties, difficulty, diffusion, dignity,
diligence, dimensions, diminution, direct, direction, directions, directive, directives, directly,
director, directors, directs, disabilities, disability, disabled, disadvantage, disagreement,
disappearance, disapproval, disaster, disasters, disbursement, disbursements, discharge,
disciplinary, discipline, disclosure, discontinuance, discontinue, discovery, discretion,
discrimination, discriminatory, discussion, discussions, disease, diseases, dishonesty, dismiss,
dismissal, dismisses, disorder, dispatch, disposal, dispose, disposition, dispositions, dispute,
disputes, disqualification, disqualifications, disruption, disseminate, dissemination, disseminator,
dissolution, dissolve, dissolved, distance, distinction, distinctions, distribution, district,
districts, disturbance, disturbances, diverse, diversion, diversity, division, divisions, divorce,
doctor, doctors, doctrine, document, documentation, documents, dollars, domain, domains, domicile,
domination, dominion, donation, donations, doors, doubt, doubts, draft, drafting, drafts, draw,
drawing, drawn, drug, drugs, du, dues, duly, duration, duties, duty, dwelling, earlier, earnings,
earth, economic, economies, economy, ecosystems, edicts, editor, editorial, educate, education,
educational, effect, effective, effectiveness, effects, efficacy, efficiency, efficient, effort,
efforts, eighteen, elaboration, elderly, elect, elected, election, elections, elector, electorate,
electors, electricity, elects, element, elements, eligibility, eliminate, elimination, emanates,
embezzlement, emblem, emblems, emergence, emergencies, emergency, emigration, emir, emirates,
emission, emolument, emoluments, emphasis, employee, employees, employer, employers, employment,
employments, en, enabling, enact, enactment, enactments, enacts, encourage, encouragement,
encourages, encroachments, end, endeavors, endeavour, endorsement, ends, enemy, energy, enforce,
enforcement, engage, engagement, engagements, enhancement, enjoy, enjoyment, enquiry, enrichment,
enrolment, ensuing, ensures, enter, enterprise, enterprises, enters, entertainment, entirety,
entities, entitlement, entitlements, entity, entrance, entries, entry, enumeration, environment,
envoy, envoys, epidemic, epidemics, equal, equality, equalization, equals, equilibrium, equipment,
equity, equivalent, eradication, error, errors, escape, espionage, essence, establish, established,
establishes, establishing, establishment, establishments, estate, estates, estimate, estimates,
ethics, ethnic, ethnicity, evaluation, event, events, evidence, evolution, ex, examination,
examinations, examine, exceeds, exception, exceptions, excess, exchange, exchanges, excise,
exclusion, excuse, execute, execution, executive, executives, exemption, exemptions, exercise,
exercises, exercising, exhaustion, exhibition, exhibitions, exigencies, exist, existence, exists,
exit, expansion, expediency, expedient, expenditure, expenditures, expense, expenses, experience,
experimentation, experiments, expert, expertise, experts, expiration, expires, expiry, explanation,
explanations, exploitation, exploration, export, exportation, exports, express, expressed,
expression, expressions, expropriation, expropriations, expulsion, extend, extends, extension,
extensions, extent, extinction, extraction, extradition, face, facie, facilitation, facilities,
fact, faction, factions, facto, factor, factories, factors, facts, faculties, faculty, fail, fails,
failure, fair, fairness, faith, faithfully, faithfulness, faiths, fall, falls, families, family,
farm, farmer, farmers, farming, fashion, father, fatherhood, fatherland, fathers, fault, faults,
fauna, favor, favour, fear, features, federate, federation, fee, feelings, fees, felonies, felony,
female, feminine, fidelity, field, fields, fifth, fifths, fight, figure, figures, file, files,
filing, filling, finance, finances, financial, financing, finding, findings, fine, fines, firm,
firms, fisheries, fishing, fit, fix, fixing, flag, flagrante, flood, floor, flora, flow, fn,
followers, following, follows, food, foodstuffs, force, forces, foregoing, foreign, foreigner,
foreigners, forest, forestry, forests, forfeiture, form, formalities, formation, formations, forms,
formula, formulate, formulation, forth, forthwith, forum, foster, fostering, foundation,
foundations, fourth, fourths, fraction, frame, framework, franchise, fraternity, fraud, free,
freedom, freedoms, freely, frequencies, friend, friends, friendship, frontier, frontiers, fruits,
fuels, fulfillment, fulfilment, function, functionaries, functionary, functioning, functions, fund,
funding, funds, furtherance, future, gain, gains, games, gas, gathering, gazette, gender, general,
generality, generally, generation, generations, genocide, gift, gifts, given, glory, goal, goals,
gold, good, goods, governance, governing, government, governmental, governments, governor,
governorates, governors, grade, grades, grandparents, grant, granting, grants, grassroots,
gratuities, gratuity, grave, gravity, green, grievances, ground, grounds, group, groups, growth,
guarantee, guaranteed, guaranteeing, guarantees, guaranties, guarantor, guard, guardian, guardians,
guardianship, guidance, guidelines, guilt, guilty, habeas, habitat, half, hand, handicapped,
handling, hands, happiness, hardship, harm, harmonization, harmony, hatred, head, heading, headings,
headquarters, heads, health, healthcare, healthy, hear, hearing, hearings, heir, heirs, held, help,
hereinafter, hereof, heritage, heroes, heroic, hierarchy, highways, hindrance, historic, historical,
history, hoc, hold, holder, holders, holding, holdings, holiday, holidays, home, homeland, homes,
honest, honestly, honesty, honor, honors, honour, honours, hospital, hospitals, hostile,
hostilities, hostility, hour, hours, house, household, houses, housing, human, humane, humanity,
hunting, husband, husbandry, hydrocarbons, hygiene, ideal, ideals, ideas, identification,
identities, identity, ideology, ignorance, ii, iii, ill, illegality, illiteracy, illness, image,
images, imbalances, immediately, immigration, immunities, immunity, impact, impacts, impartial,
impartiality, impeachment, impediment, impediments, implement, implementation, implements,
implication, import, importance, importation, imports, imposes, imposing, imposition, impossibility,
imposts, imprisonment, improvement, improvements, inability, inauguration, incapable,
incapacitation, incapacity, incentives, incident, incidental, incitement, include, includes,
including, inclusion, inclusive, income, incomes, incompatibilities, incompatibility, incompetence,
inconsistency, inconsistent, incorporation, increase, increases, incumbent, indebtedness,
indefinite, indemnification, indemnities, indemnity, independence, independent, independently,
indication, indictment, individual, individuals, indivisibility, industrial, industrialization,
industries, industry, ineligibilities, ineligibility, inequalities, inequality, infirmity,
infliction, influence, influences, inform, information, infraction, infractions, infrastructure,
infringe, infringement, infringements, ingwenyama, inhabitant, inhabitants, inherent, inheritance,
inhuman, inhumane, initiate, initiation, initiative, initiatives, injunction, injuries, injury,
injustice, inland, innocence, innovation, inquire, inquiries, inquiry, insane, inscription,
insertion, insignia, insofar, insolvent, inspection, inspections, installation, installations,
installments, instance, instances, institute, institutes, institution, institutions, instruction,
instructions, instrument, instruments, insurance, insurrection, integration, integrity,
intellectual, intellectuals, intelligence, intent, intention, inter, interaction, interdependence,
interdiction, interests, interference, interim, interior, intermediary, interpellation,
interpellations, interpretation, interpreter, interrogation, interruption, interval, intervals,
intervene, intervenes, intervening, intervention, interventions, intimacy, intimidation,
intolerance, introduction, invalidity, invasion, invention, inventions, inventors, investigate,
investigating, investigation, investigations, investiture, investment, investments, investors,
inviolability, invitation, involvement, irregularities, irregularity, irrespective, irrigation,
island, islands, isolation, issuance, issue, issues, issuing, item, items, iv, jeopardy, job, jobs,
join, joint, jointly, journal, journalists, journey, judge, judgement, judgements, judges, judgment,
judgments, judicature, judicial, judiciary, jure, juridical, juries, jurisdiction, jurisdictions,
jurisprudence, jurist, jurists, jurors, jury, just, justice, justices, justification, kin, kind,
kinds, king, knowing, knowledge, labor, labour, lack, lakes, land, lands, language, languages,
lapse, lapses, later, latest, law, lawful, lawfulness, laws, lawsuit, lawsuits, lawyer, lawyers,
lay, leader, leaders, leadership, learning, lease, leases, leave, leaves, left, legality, legislate,
legislation, legislative, legislator, legislators, legislature, legislatures, legitimacy, leisure,

term_str,abandonment,abeyance,abide,abilities,ability,abolition,abroad,abrogation,absence,absences,absent,absolute,abuse,abuses,accept,acceptance,accepts,access,accessibility,accession,accident,accidents,accommodation,accomplices,accomplishment,accord,accordance,accordingly,accords,account,accountability,accounting,accounts,accredit,accreditation,accumulation,accusation,accusations,accused,achievement,achievements,acknowledgement,acknowledgment,acquisition,acquittal,act,acting,action,actions,activities,...,weeks,weight,weights,welfare,wellbeing,whatsoever,whereof,whichever,whilst,white,wider,widow,widows,width,wife,wireless,wisdom,wish,wishes,withdrawal,withdrawals,withdrawn,withheld,withhold,withholding,witness,witnesses,woman,women,word,wording,words,work,worker,workers,working,workplace,works,world,worship,worth,writ,writing,writs,year,years,yellow,youth,zone,zones
topic_id,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
T00,0.050000,0.05,0.050000,0.050000,0.050000,0.050000,0.050000,10.505440,0.050000,0.05,0.050000,10.971251,0.050000,0.050000,0.050000,0.050000,0.05,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.05,0.05,9.054885,309.643221,12.266023,0.050000,15.155393,0.050000,0.050000,0.050000,0.050000,0.05,0.050000,0.05,0.050000,0.05,0.05,0.05,1.281459,0.050000,0.050000,0.05,17.736116,0.050000,79.577504,0.050000,0.050000,...,106.727679,0.050000,0.050000,0.050000,0.050000,2.958228,7.949783,12.974700,0.050000,0.05,0.05000,0.050000,32.225263,0.050000,0.05,0.05,0.050000,4.412144,0.050000,0.050000,0.05,0.050000,17.05,11.05,2.269568,0.05000,0.050000,0.050000,0.050000,0.050000,13.835908,17.200677,0.050001,0.05,0.0500,0.050000,0.05,0.050000,4.158147,0.050000,0.050000,0.050000,30.086025,24.927260,401.591806,163.301817,0.05,0.050000,0.05,0.050000
T01,0.050000,0.05,0.050000,0.050000,0.050000,38.520938,0.050000,0.050000,3.663465,0.05,0.050000,0.050000,0.050000,0.050000,1.488825,0.275142,0.05,4.302121,0.050000,0.050000,0.050000,0.050000,0.050000,14.05,0.05,0.050000,238.038942,0.050000,1.805874,169.787925,0.050000,0.050011,334.473835,0.050000,0.05,0.050000,0.05,18.028042,0.05,0.05,0.05,0.050000,0.050000,0.050000,0.05,0.058109,0.050000,11.866961,0.050000,0.050000,...,0.115991,0.050000,0.050000,0.050000,2.260668,0.050000,0.050000,0.050000,0.050000,0.05,0.05000,25.762139,0.050000,0.050000,0.05,0.05,0.050000,0.050000,0.050000,141.713607,0.05,0.050000,0.05,1.05,13.909838,0.05000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.05,0.0500,0.050000,0.05,0.050000,0.050000,0.050000,3.175356,0.050000,10.910630,0.050000,1591.906510,4.314983,0.05,0.050000,0.05,0.050000
T02,0.050000,0.05,0.050000,0.050000,0.050000,27.202486,0.050000,0.050000,0.714187,0.05,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.05,0.050000,5.875918,0.050000,0.050000,1.732522,0.050000,0.05,0.05,86.605206,584.254725,3.021769,0.050106,5.057300,0.050000,6.606934,115.382191,0.050000,0.05,1.273555,0.05,0.050000,0.05,0.05,0.05,0.050000,0.050000,0.050000,0.05,67.342112,0.050000,63.691985,105.756718,71.465284,...,0.050000,0.050000,0.050000,0.050000,0.050000,6.472160,0.050000,0.050000,0.050000,0.05,0.05000,0.050000,0.050000,0.050000,0.05,0.05,0.050000,0.050000,0.050000,0.050000,0.05,0.050000,0.05,0.05,0.050000,0.05000,0.050000,0.050000,0.050000,0.050000,0.050000,0.303893,3.913876,0.05,0.0500,0.050000,0.05,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,25.709541,1.105993,3.374678,0.05,0.050000,0.05,4.718530
T03,0.050000,0.05,0.050000,0.050000,0.051118,0.050000,5.684324,0.050000,0.050000,0.05,0.050000,0.050000,11.345172,16.072002,0.050000,0.050000,0.05,321.030936,0.050000,0.050000,0.050000,0.050000,0.050000,0.05,0.05,0.050000,21.260599,0.050000,0.050000,59.381145,0.396668,4.476613,0.050000,0.050000,0.05,0.050000,0.05,0.050000,0.05,0.05,0.05,0.050000,0.050000,0.050000,0.05,9.221310,0.050000,82.596535,0.122263,27.552350,...,0.050000,0.050000,0.050026,0.050000,0.050000,12.877134,0.050000,0.050000,0.050000,0.05,0.05000,0.050000,0.050000,0.050000,0.05,34.05,0.050000,0.050000,2.650261,0.050000,0.05,0.050000,0.05,0.05,0.050000,0.05000,0.678969,0.050000,0.674969,12.387109,0.050000,8.755175,1.266149,0.05,0.0500,0.050000,0.05,0.050000,0.050000,4.855865,0.050000,0.050000,33.957537,0.050000,0.050000,0.050000,0.05,10.866591,0.05,0.050000
T04,0.050000,0.05,0.050000,0.050000,0.124774,9.973970,1.209495,0.050000,183.146028,0.05,12.281048,0.050000,0.050000,0.050000,0.050000,0.050000,0.05,11.901740,0.050000,0.050000,5.088035,0.050000,0.050000,0.05,0.05,0.050000,2109.281408,11.699468,0.050000,12.026507,0.050000,0.050000,91.267326,0.050000,0.05,0.050000,0.05,0.050000,0.05,0.05,0.05,18.789519,12.578815,0.050000,0.05,167.853456,967.550042,66.221703,0.050000,0.050000,...,0.050000,0.050000,0.050000,0.050000,0.050000,2.974520,0.050000,3.676324,0.050000,0.05,0.05000,0.050000,0.050000,0.050000,0.05,0.05,0.050000,0.050000,0.050000,14.108470,0.05,0.050000,0.05,0.05,0.050000,0.05000,0.050000,0.050000,0.050000,15.742584,0.050000,78.515746,1.124223,0.05,0.0500,0.050000,0.05,0.050000,0.050000,0.050000,0.050000,1.778110,81.609494,0.050000,16.344889,249.265913,0.05,0.050000,0.05,0.050000
T05,6.473088,0.05,0.050000,0.050000,0.050000,0.050000,9.577679,17.003268,3.646712,0.05,0.050000,0.050000,0.050000,0.050000,0.050000,22.649032,0.05,0.050000,0.050000,45.575978,0.050000,0.050000,0.050000,0.05,0.05,0.050000,190.453311,0.050000,9.263490,0.458009,0.050000,0.050000,1.194399,0.050000,0.05,0.050000,0.05,0.050000,0.05,0.05,0.05,0.050000,0.050000,0.050000,0.05,11.378082,0.050000,2.399679,0.265935,36.527452,...,0.050000,3.841216,12.736401,0.261152,0.050000,0.050000,0.050000,0.050000,0.050000,0.05,0.05000,0.050000,0.050000,2.568777,0.05,0.05,0.050000,0.050000,0.050000,1.934531,0.05,0.050000,0.05,0.05,0.050000,0.05000,0.050000,0.050000,0.050000,0.050000,0.050000,3.966296,0.317575,0.05,0.0500,4.781158,0.05,0.050000,0.051251,0.050000,0.050000,0.050000,0.050000,0.050000,0.144874,0.050000,0.05,0.050000,102.05,38.364715
T06,5.216702,0.05,1.325664,0.050000,89.240342,0.050000,5.741391,0.050000,0.650260,0.05,0.050000,0.050000,33.605947,0.050000,15.457677,0.050000,0.05,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.05,17.05,0.050000,596.290789,0.050000,0.050000,35.248109,35.831670,38.519986,44.460596,6.352955,0.05,0.050000,0.05,0.050000,0.05,0.05,0.05,0.050000,0.050000,0.050000,0.05,18.410586,0.050000,32.155157,181.220074,277.565420,...,0.050000,0.050000,0.050000,2.532529,0.050000,1.213802,0.050000,0.050000,5.116540,0.05,0.05000,0.050000,0.050000,0.050000,0.05,0.05,0.363557,0.050000,0.050000,0.050000,0.05,0.050000,0.05,0.05,2.382553,0.05000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,77.728008,0.05,0.0500,8.239914,0.05,10.352593,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,10.841462,44.272188,0.05,0.050000,0.05,0.050000
T07,0.050000,0.05,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,10.234646,0.05,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.05,0.054533,0.050000,0.050000,0.050000,0.050000,0.050000,0.05,0.05,0.530823,85.447855,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.05,0.050000,0.05,0.050000,0.05,0.05,34.05,0.050000,0.050000,0.050000,0.05,2.210488,0.050000,4.109380,0.050000,22.207906,...,1.780405,0.050000,0.050000,0.050000,0.050000,16.371013,0.050000,0.050000,0.050000,0.05,1.70228,0.050000,0.050000,0.050000,0.05,0.05,0.050000,0.050000,2.535139,0.050000,0.05,0.050000,0.05,0.05,0.050000,0.05000,0.050000,0.050061,0.050000,23.926530,24.617344,46.186386,78.844617,0.05,0.0716,0.313463,0.05,0.050000,0.050000,0.050000,1.215713,0.050000,0.050000,0.050000,23.103371,42.571982,0.05,0.861658,0.05,0.050000
T08,0.050000,0.05,0.050000,1.325071,0.050000,0.050000,0.050000,0.303336,0.050000,0.05,0.050000,0.050340,0.050000,0.050000,0.050000,1.994685,0.05,0.050000,0.050000,0.050000,6.355197,0.050000,0.050000,0.05,0.05,27.608256,133.780330,0.050000,0.050000,0.413497,0.050000,0.050000,0.050000,0.050000,0.05,0.050000,0.05,0.050000,0.05,0.05,0.05,0.050000,0.050000,0.342886,0.05,4.805312,0.050000,8.443612,26.525982,8.631150,...,0.050052,0.050000,0.050000,0.050000,0.050000,0.050000,0.050001,0.050000,0.050000,15.05,0.05000,0.050000,0.366286,26.531223,0.05,0.05,0.050000,0.050000,0.986598,0.050000,0.05,0.050000,0.05,0.05,0.050000,0.05000,0.050000,0.050000,0.050000,1.143762,11.185373,8.334915,0.050000,0.05,0.0500,0.050000,0.05,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,0.050000,1.199185,0.050000,18.05,0.050000,0.05,2.689894
T09,0.050000,0.05,0.050000,0.050000,0.050000,3.325386,0.050000,0.050000,112.488930,0.05,0.050063,0.050000,4.263025,0.050000,0.050000,0.050000,0.05,11.370640,0.050000,0.050000,0.050000,0.050000,6.654098,0.05,0.05,0.050000,92.863138,19.590185,0.050000,174.478699,0.050000,0.050000,0.050000,0.050000,0.05,0.050000,0.05,0.050000,0.05,0.05,0.05,0.050000,0.050000,0.050000,40.05,306.409251,0.050000,97.590188,0.050000,0.050000,...,0.050000,0.050000,0.050000,68.461342,0.050000,10.927389,3.150217,0.050000,5.973029,0.05,0.05000,0.050000,0.050000,0.050000,0.05,0.05,0.050000,0.050000,0.050000,14.121922,0.05,1.884266,0.05,0.05,0.050000,48.73223,245.421031,0.050000,0.050000,0.050000,0.050000,7.755251,0.050000,0.05,0.0500,0.050000,0.05,0.050000,0.050000,0.050000,0.050000,8.008697,7.285447,48.412616,0.050000,109.078078,0.05,0.050000,0.05,0.050000

## Sentiment VOCAB_SENT

This section inspects the sentiment-enriched vocabulary table produced by matching project vocabulary terms to the Loughran-McDonald lexicon.

In [13]:
VOCAB_SENT = inspect_table(
    section='Sentiment VOCAB_SENT',
    box_url='https://virginia.box.com/shared/static/9i317on9zav6qhx9o898dwxtwegjxqul',
    local_path='vocab_sent.parquet',
    file_format='parquet'
)

Section: Sentiment VOCAB_SENT
Box URL: https://virginia.box.com/shared/static/9i317on9zav6qhx9o898dwxtwegjxqul
Local file: vocab_sent.parquet
Loaded from: Box download
Format: parquet
Shape: 15,294 rows x 26 columns
Number of observations: 15,294
Column names:
term_str, n, p, i, df, idf, dfidf, n_chars, max_pos, max_pos_group, n_pos, cat_pos, n_pos_group,
cat_pos_group, stop, porter_stem, negative, positive, uncertainty, litigious, strong_modal,
weak_modal, constraining, complexity, sentiment, matched_lexicon

,term_str,n,p,i,df,idf,dfidf,n_chars,max_pos,max_pos_group,n_pos,cat_pos,n_pos_group,cat_pos_group,stop,porter_stem,negative,positive,uncertainty,litigious,strong_modal,weak_modal,constraining,complexity,sentiment,matched_lexicon
0,abandon,11,2.864780e-06,18.413144,11,5.007495,55.082440,7,VB,VB,2,"{JJ, VB}",2,"{JJ, VB}",0,abandon,1,0,0,0,0,0,0,0,-1,1
1,abandoned,35,9.115210e-06,16.743293,27,3.785102,102.197757,9,VBN,VB,8,"{IN, JJ, NN, NNP, NNPS, VB, VBD, VBN}",4,"{IN, JJ, NN, VB}",0,abandon,1,0,0,0,0,0,0,0,-1,1
2,abandoning,1,2.604346e-07,21.872576,1,7.592457,7.592457,10,VBG,VB,1,{VBG},1,{VB},0,abandon,1,0,0,0,0,0,0,0,-1,1
3,abandonment,40,1.041738e-05,16.550648,32,3.548063,113.538013,11,NN,NN,4,"{JJ, NN, NNP, VB}",3,"{JJ, NN, VB}",0,abandon,1,0,0,0,0,0,0,0,-1,1
4,abandons,4,1.041738e-06,19.872576,3,6.592457,19.777371,8,VBZ,VB,1,{VBZ},1,{VB},0,abandon,1,0,0,0,0,0,0,0,-1,1
5,abases,1,2.604346e-07,21.872576,1,7.592457,7.592457,6,VBZ,VB,1,{VBZ},1,{VB},0,abas,0,0,0,0,0,0,0,0,0,1
6,abate,4,1.041738e-06,19.872576,2,7.007495,14.014989,5,VB,VB,1,{VB},1,{VB},0,abat,0,0,0,0,0,0,0,0,0,1
7,abatement,2,5.208691e-07,20.872576,2,7.007495,14.014989,9,NN,NN,1,{NN},1,{NN},0,abat,0,0,0,0,0,0,0,0,0,1
8,abatements,2,5.208691e-07,20.872576,2,7.007495,14.014989,10,NNS,NN,1,{NNS},1,{NN},0,abat,0,0,0,0,0,0,0,0,0,1
9,abattoir,1,2.604346e-07,21.872576,1,7.592457,7.592457,8,NN,NN,1,{NN},1,{NN},0,abattoir,0,0,0,0,0,0,0,0,0,1

## Sentiment Source Lexicon

This section inspects the Loughran-McDonald source lexicon file that supports the sentiment notebook.

In [14]:
LM_LEXICON = inspect_table(
    section='Sentiment Source Lexicon',
    box_url='https://virginia.box.com/shared/static/obtdoavt4ue8cv0pi128b91gksayehnf',
    local_path='Loughran-McDonald_MasterDictionary_1993-2025.csv',
    file_format='csv'
)

Section: Sentiment Source Lexicon
Box URL: https://virginia.box.com/shared/static/obtdoavt4ue8cv0pi128b91gksayehnf
Local file: Loughran-McDonald_MasterDictionary_1993-2025.csv
Loaded from: Box download
Format: csv
Shape: 86,553 rows x 17 columns
Number of observations: 86,553
Column names:
Word, Seq_num, Word Count, Word Proportion, Average Proportion, Std Dev, Doc Count, Negative,
Positive, Uncertainty, Litigious, Strong_Modal, Weak_Modal, Constraining, Complexity, Syllables,
Source

,Word,Seq_num,Word Count,Word Proportion,Average Proportion,Std Dev,Doc Count,Negative,Positive,Uncertainty,Litigious,Strong_Modal,Weak_Modal,Constraining,Complexity,Syllables,Source
0,AARDVARK,1,814,3.085383e-08,2.022181e-08,4.059339e-06,158,0,0,0,0,0,0,0,0,2,12of12inf
1,AARDVARKS,2,3,1.137119e-10,7.898767e-12,8.829342e-09,1,0,0,0,0,0,0,0,0,2,12of12inf
2,ABACI,3,9,3.411357e-10,1.067549e-10,5.054031e-08,7,0,0,0,0,0,0,0,0,3,12of12inf
3,ABACK,4,29,1.099215e-09,6.073925e-10,1.523804e-07,28,0,0,0,0,0,0,0,0,2,12of12inf
4,ABACUS,5,9921,3.760453e-07,3.836730e-07,3.392121e-05,1355,0,0,0,0,0,0,0,0,3,12of12inf
5,ABACUSES,6,0,0.000000e+00,0.000000e+00,0.000000e+00,0,0,0,0,0,0,0,0,0,4,12of12inf
6,ABAFT,7,4,1.516159e-10,2.101878e-11,2.349506e-08,1,0,0,0,0,0,0,0,0,2,12of12inf
7,ABALONE,8,151,5.723499e-09,4.678978e-09,1.022283e-06,54,0,0,0,0,0,0,0,0,4,12of12inf
8,ABALONES,9,1,3.790397e-11,7.560853e-11,8.451617e-08,1,0,0,0,0,0,0,0,0,4,12of12inf
9,ABANDON,10,161792,6.132559e-06,4.843331e-06,3.244019e-05,79131,2009,0,0,0,0,0,0,0,3,12of12inf

## Sentiment BOW_SENT

This section inspects the bag-of-words table after sentiment dimensions from `VOCAB_SENT` have been mapped onto each bag-term row.

In [15]:
BOW_SENT = inspect_table(
    section='Sentiment BOW_SENT',
    box_url='https://virginia.box.com/shared/static/md0swqfp719tqns4f1m1015t3rqjcnk8',
    local_path='bow_sent.parquet',
    file_format='parquet'
)

Section: Sentiment BOW_SENT
Box URL: https://virginia.box.com/shared/static/md0swqfp719tqns4f1m1015t3rqjcnk8
Local file: bow_sent.parquet
Loaded from: Box download
Format: parquet
Shape: 1,307,209 rows x 23 columns
Number of observations: 1,307,209
Column names:
country_id, article_n, term_str, n, tfidf, negative, positive, uncertainty, litigious, strong_modal,
weak_modal, constraining, complexity, sentiment, negative_w, positive_w, uncertainty_w, litigious_w,
strong_modal_w, weak_modal_w, constraining_w, complexity_w, sentiment_w

,country_id,article_n,term_str,n,tfidf,negative,positive,uncertainty,litigious,strong_modal,weak_modal,constraining,complexity,sentiment,negative_w,positive_w,uncertainty_w,litigious_w,strong_modal_w,weak_modal_w,constraining_w,complexity_w,sentiment_w
0,Afghanistan,1,accordance,1,2.950516,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Afghanistan,1,adhering,1,9.123469,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Afghanistan,1,admiring,1,10.732907,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Afghanistan,1,all,3,8.100179,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,Afghanistan,1,almighty,1,6.597740,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,Afghanistan,1,appreciating,1,9.816616,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,Afghanistan,1,appropriate,1,4.486800,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,Afghanistan,1,approved,1,4.600594,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,Afghanistan,1,atrocity,1,10.732907,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,Afghanistan,1,attain,1,7.437070,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,1

## Sentiment DOC_SENT

This section inspects the article-level sentiment summary table aggregated from `BOW_SENT`.

In [16]:
DOC_SENT = inspect_table(
    section='Sentiment DOC_SENT',
    box_url='https://virginia.box.com/shared/static/jg5stv77zs6b7fjnl5xrf34q0m8q33h9',
    local_path='doc_sent.parquet',
    file_format='parquet'
)

Section: Sentiment DOC_SENT
Box URL: https://virginia.box.com/shared/static/jg5stv77zs6b7fjnl5xrf34q0m8q33h9
Local file: doc_sent.parquet
Loaded from: Box download
Format: parquet
Shape: 33,725 rows x 40 columns
Number of observations: 33,725
Column names:
country_id, article_n, matched_token_count, matched_term_count, negative_w, positive_w,
uncertainty_w, litigious_w, strong_modal_w, weak_modal_w, constraining_w, complexity_w, sentiment_w,
negative_mean, positive_mean, uncertainty_mean, litigious_mean, strong_modal_mean, weak_modal_mean,
constraining_mean, complexity_mean, sentiment_mean, doc_id, year_created, year_amended, region,
region_compressed, source_file, file_format, char_count, line_count, article_count, clause_count,
token_count, v2x_regime, v2x_freexp_altinf, v2x_rule, v2x_regime_cat, v2x_freexp_altinf_cat,
v2x_rule_cat

,country_id,article_n,matched_token_count,matched_term_count,negative_w,positive_w,uncertainty_w,litigious_w,strong_modal_w,weak_modal_w,constraining_w,complexity_w,sentiment_w,negative_mean,positive_mean,uncertainty_mean,litigious_mean,strong_modal_mean,weak_modal_mean,constraining_mean,complexity_mean,sentiment_mean,doc_id,year_created,year_amended,region,region_compressed,source_file,file_format,char_count,line_count,article_count,clause_count,token_count,v2x_regime,v2x_freexp_altinf,v2x_rule,v2x_regime_cat,v2x_freexp_altinf_cat,v2x_rule_cat
0,Afghanistan,1,143,119,3,8,1,4,0,0,1,1,5,0.020979,0.055944,0.006993,0.027972,0.0,0.0,0.006993,0.006993,0.034965,Afghanistan_2004,2004,2004,Southern Asia,Asia,Afghanistan_2004.txt,plaintext,66806,1482,163,277,9937,1.0,0.666,0.122,Electoral autocracy,High,Very low
1,Afghanistan,2,5,5,0,0,0,0,0,0,0,0,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,Afghanistan_2004,2004,2004,Southern Asia,Asia,Afghanistan_2004.txt,plaintext,66806,1482,163,277,9937,1.0,0.666,0.122,Electoral autocracy,High,Very low
2,Afghanistan,3,15,14,0,0,0,1,0,0,0,0,0,0.000000,0.000000,0.000000,0.066667,0.0,0.0,0.000000,0.000000,0.000000,Afghanistan_2004,2004,2004,Southern Asia,Asia,Afghanistan_2004.txt,plaintext,66806,1482,163,277,9937,1.0,0.666,0.122,Electoral autocracy,High,Very low
3,Afghanistan,4,6,6,0,0,0,2,0,0,0,0,0,0.000000,0.000000,0.000000,0.333333,0.0,0.0,0.000000,0.000000,0.000000,Afghanistan_2004,2004,2004,Southern Asia,Asia,Afghanistan_2004.txt,plaintext,66806,1482,163,277,9937,1.0,0.666,0.122,Electoral autocracy,High,Very low
4,Afghanistan,5,35,30,1,0,0,2,0,0,0,0,-1,0.028571,0.000000,0.000000,0.057143,0.0,0.0,0.000000,0.000000,-0.028571,Afghanistan_2004,2004,2004,Southern Asia,Asia,Afghanistan_2004.txt,plaintext,66806,1482,163,277,9937,1.0,0.666,0.122,Electoral autocracy,High,Very low
5,Afghanistan,6,18,18,1,2,0,2,0,0,0,0,1,0.055556,0.111111,0.000000,0.111111,0.0,0.0,0.000000,0.000000,0.055556,Afghanistan_2004,2004,2004,Southern Asia,Asia,Afghanistan_2004.txt,plaintext,66806,1482,163,277,9937,1.0,0.666,0.122,Electoral autocracy,High,Very low
6,Afghanistan,7,31,29,0,2,0,1,0,0,1,0,2,0.000000,0.064516,0.000000,0.032258,0.0,0.0,0.032258,0.000000,0.064516,Afghanistan_2004,2004,2004,Southern Asia,Asia,Afghanistan_2004.txt,plaintext,66806,1482,163,277,9937,1.0,0.666,0.122,Electoral autocracy,High,Very low
7,Afghanistan,8,27,26,0,0,0,0,0,0,1,1,0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.037037,0.037037,0.000000,Afghanistan_2004,2004,2004,Southern Asia,Asia,Afghanistan_2004.txt,plaintext,66806,1482,163,277,9937,1.0,0.666,0.122,Electoral autocracy,High,Very low
8,Afghanistan,9,19,19,0,2,0,1,0,0,0,0,2,0.000000,0.105263,0.000000,0.052632,0.0,0.0,0.000000,0.000000,0.105263,Afghanistan_2004,2004,2004,Southern Asia,Asia,Afghanistan_2004.txt,plaintext,66806,1482,163,277,9937,1.0,0.666,0.122,Electoral autocracy,High,Very low
9,Afghanistan,10,20,18,0,0,0,2,0,0,0,0,0,0.000000,0.000000,0.000000,0.100000,0.0,0.0,0.000000,0.000000,0.000000,Afghanistan_2004,2004,2004,Southern Asia,Asia,Afghanistan_2004.txt,plaintext,66806,1482,163,277,9937,1.0,0.666,0.122,Electoral autocracy,High,Very low

## VOCAB_W2V

This section inspects the Word2Vec vocabulary table that adds embedding features to the project `VOCAB` table.

In [17]:
VOCAB_W2V = inspect_table(
    section='VOCAB_W2V',
    box_url='https://virginia.box.com/shared/static/g397pdb178mn0efv68s8p4tlpgjsybc4',
    local_path='vocab_w2v.parquet',
    file_format='parquet'
)

Section: VOCAB_W2V
Box URL: https://virginia.box.com/shared/static/g397pdb178mn0efv68s8p4tlpgjsybc4
Local file: vocab_w2v.parquet
Loaded from: Box download
Format: parquet
Shape: 5,622 rows x 272 columns
Number of observations: 5,622
Column names:
term_str, n, p, i, df, idf, dfidf, n_chars, max_pos, max_pos_group, n_pos, cat_pos, n_pos_group,
cat_pos_group, stop, porter_stem, w2v_0, w2v_1, w2v_2, w2v_3, w2v_4, w2v_5, w2v_6, w2v_7, w2v_8,
w2v_9, w2v_10, w2v_11, w2v_12, w2v_13, w2v_14, w2v_15, w2v_16, w2v_17, w2v_18, w2v_19, w2v_20,
w2v_21, w2v_22, w2v_23, w2v_24, w2v_25, w2v_26, w2v_27, w2v_28, w2v_29, w2v_30, w2v_31, w2v_32,
w2v_33, w2v_34, w2v_35, w2v_36, w2v_37, w2v_38, w2v_39, w2v_40, w2v_41, w2v_42, w2v_43, w2v_44,
w2v_45, w2v_46, w2v_47, w2v_48, w2v_49, w2v_50, w2v_51, w2v_52, w2v_53, w2v_54, w2v_55, w2v_56,
w2v_57, w2v_58, w2v_59, w2v_60, w2v_61, w2v_62, w2v_63, w2v_64, w2v_65, w2v_66, w2v_67, w2v_68,
w2v_69, w2v_70, w2v_71, w2v_72, w2v_73, w2v_74, w2v_75, w2v_76, w2v_77, w2v_78, w2v_79, w2v_80,
w2v_81, w2v_82, w2v_83, w2v_84, w2v_85, w2v_86, w2v_87, w2v_88, w2v_89, w2v_90, w2v_91, w2v_92,
w2v_93, w2v_94, w2v_95, w2v_96, w2v_97, w2v_98, w2v_99, w2v_100, w2v_101, w2v_102, w2v_103, w2v_104,
w2v_105, w2v_106, w2v_107, w2v_108, w2v_109, w2v_110, w2v_111, w2v_112, w2v_113, w2v_114, w2v_115,
w2v_116, w2v_117, w2v_118, w2v_119, w2v_120, w2v_121, w2v_122, w2v_123, w2v_124, w2v_125, w2v_126,
w2v_127, w2v_128, w2v_129, w2v_130, w2v_131, w2v_132, w2v_133, w2v_134, w2v_135, w2v_136, w2v_137,
w2v_138, w2v_139, w2v_140, w2v_141, w2v_142, w2v_143, w2v_144, w2v_145, w2v_146, w2v_147, w2v_148,
w2v_149, w2v_150, w2v_151, w2v_152, w2v_153, w2v_154, w2v_155, w2v_156, w2v_157, w2v_158, w2v_159,
w2v_160, w2v_161, w2v_162, w2v_163, w2v_164, w2v_165, w2v_166, w2v_167, w2v_168, w2v_169, w2v_170,
w2v_171, w2v_172, w2v_173, w2v_174, w2v_175, w2v_176, w2v_177, w2v_178, w2v_179, w2v_180, w2v_181,
w2v_182, w2v_183, w2v_184, w2v_185, w2v_186, w2v_187, w2v_188, w2v_189, w2v_190, w2v_191, w2v_192,
w2v_193, w2v_194, w2v_195, w2v_196, w2v_197, w2v_198, w2v_199, w2v_200, w2v_201, w2v_202, w2v_203,
w2v_204, w2v_205, w2v_206, w2v_207, w2v_208, w2v_209, w2v_210, w2v_211, w2v_212, w2v_213, w2v_214,
w2v_215, w2v_216, w2v_217, w2v_218, w2v_219, w2v_220, w2v_221, w2v_222, w2v_223, w2v_224, w2v_225,
w2v_226, w2v_227, w2v_228, w2v_229, w2v_230, w2v_231, w2v_232, w2v_233, w2v_234, w2v_235, w2v_236,
w2v_237, w2v_238, w2v_239, w2v_240, w2v_241, w2v_242, w2v_243, w2v_244, w2v_245, w2v_246, w2v_247,
w2v_248, w2v_249, w2v_250, w2v_251, w2v_252, w2v_253, w2v_254, w2v_255

,term_str,n,p,i,df,idf,dfidf,n_chars,max_pos,max_pos_group,n_pos,cat_pos,n_pos_group,cat_pos_group,stop,porter_stem,w2v_0,w2v_1,w2v_2,w2v_3,w2v_4,w2v_5,w2v_6,w2v_7,w2v_8,w2v_9,w2v_10,w2v_11,w2v_12,w2v_13,w2v_14,w2v_15,w2v_16,w2v_17,w2v_18,w2v_19,w2v_20,w2v_21,w2v_22,w2v_23,w2v_24,w2v_25,w2v_26,w2v_27,w2v_28,w2v_29,w2v_30,w2v_31,w2v_32,w2v_33,...,w2v_206,w2v_207,w2v_208,w2v_209,w2v_210,w2v_211,w2v_212,w2v_213,w2v_214,w2v_215,w2v_216,w2v_217,w2v_218,w2v_219,w2v_220,w2v_221,w2v_222,w2v_223,w2v_224,w2v_225,w2v_226,w2v_227,w2v_228,w2v_229,w2v_230,w2v_231,w2v_232,w2v_233,w2v_234,w2v_235,w2v_236,w2v_237,w2v_238,w2v_239,w2v_240,w2v_241,w2v_242,w2v_243,w2v_244,w2v_245,w2v_246,w2v_247,w2v_248,w2v_249,w2v_250,w2v_251,w2v_252,w2v_253,w2v_254,w2v_255
0,abandoned,35,0.000009,16.743293,27,3.785102,102.197757,9,VBN,VB,8,"{IN, JJ, NN, NNP, NNPS, VB, VBD, VBN}",4,"{IN, JJ, NN, VB}",0,abandon,0.073700,-0.174708,0.093871,-0.000434,0.021934,0.122396,-0.112501,0.088526,-0.084787,0.155957,-0.043394,0.042839,-0.122988,-0.026982,-0.001589,-0.139062,-0.087802,0.163906,0.021254,-0.085140,0.122532,-0.217843,0.039072,-0.132595,0.063915,0.012649,-0.058430,0.069377,-0.011684,-0.056713,-0.066475,-0.031281,0.096206,0.141939,...,0.139267,0.012704,-0.154450,0.197402,-0.048538,-0.006751,-0.100635,-0.045073,-0.106387,-0.055860,0.072501,-0.093267,-0.043283,-0.061011,-0.074880,0.059546,0.117177,-0.064828,-0.087773,0.019939,0.012150,-0.089868,-0.043985,-0.025825,0.094725,0.031734,-0.072790,0.030077,-0.053025,-0.191701,0.089533,0.008379,-0.076043,-0.200846,-0.199409,0.005384,-0.078783,-0.018475,0.097394,-0.232650,-0.043581,0.120082,0.100029,-0.088394,-0.032106,-0.269811,-0.000878,-0.131548,-0.046129,-0.001895
1,abandonment,40,0.000010,16.550648,32,3.548063,113.538013,11,NN,NN,4,"{JJ, NN, NNP, VB}",3,"{JJ, NN, VB}",0,abandon,0.088658,-0.175913,0.147324,0.099200,0.015570,0.158780,-0.006007,-0.044386,-0.093620,0.065705,-0.055803,0.131556,0.101062,0.088443,-0.031846,-0.116678,-0.009710,0.145142,0.134152,-0.068435,0.068232,-0.133187,-0.021322,0.006533,0.057720,0.140106,-0.117492,0.079170,0.045317,-0.031481,0.027261,0.045549,0.004103,0.098799,...,-0.034857,-0.034180,-0.106529,0.013614,-0.002248,-0.043029,-0.177203,-0.038882,-0.128045,0.048825,0.010827,-0.101246,0.012953,-0.047898,-0.012416,-0.016143,0.096819,-0.030208,-0.092434,-0.019137,0.008156,0.013714,-0.023656,0.043786,0.124049,-0.056937,0.082849,0.008655,0.068120,0.031792,0.115240,0.074317,-0.036700,-0.138439,-0.032085,0.086659,-0.134960,0.042748,-0.023416,-0.126393,-0.048050,-0.057721,0.138578,-0.042252,0.034308,-0.145910,0.040471,-0.075106,-0.105863,-0.140268
2,abeyance,35,0.000009,16.743293,5,6.007495,30.037473,8,NN,NN,3,"{CC, JJ, NN}",3,"{CC, JJ, NN}",0,abey,0.281123,-0.275636,-0.104653,-0.091375,-0.083771,0.034206,-0.138228,-0.068119,0.046710,0.061548,0.055645,0.115365,0.073761,-0.329504,0.215103,-0.000641,-0.247402,-0.020216,-0.178775,0.143593,-0.142429,0.001881,-0.254678,-0.028050,0.121308,-0.390504,0.048189,0.251398,0.213564,0.105306,0.224514,-0.174981,0.149835,0.222569,...,0.217903,0.143233,0.101785,0.422052,0.217841,-0.172943,0.104746,0.137911,-0.167356,-0.116892,-0.007192,-0.086031,-0.036458,-0.119800,-0.077488,0.234456,0.039391,0.151356,-0.102520,0.037541,-0.155224,0.033608,-0.264599,-0.031395,0.101758,0.071054,-0.026766,0.016328,0.001893,-0.050023,-0.087428,0.159665,0.159006,-0.058171,-0.307542,-0.025018,0.119891,-0.128965,-0.076891,-0.366557,0.107452,0.071837,0.011519,-0.095819,-0.062295,-0.323261,-0.018861,0.007049,-0.196832,-0.059989
3,abide,104,0.000027,15.172136,51,2.892017,147.492883,5,VB,VB,4,"{NN, RB, VB, VBP}",3,"{NN, RB, VB}",0,abid,0.281837,-0.215503,0.067570,-0.199556,0.199987,0.154022,0.796452,-0.164625,-0.078652,0.224606,-0.258865,-0.105670,0.323694,-0.026433,-0.192868,-0.085982,0.084579,0.056524,0.332158,0.289530,0.022649,-0.284675,-0.111188,-0.103307,0.180317,-0.258130,-0.045990,-0.032062,-0.242827,-0.234238,-0.103869,0.037107,-0.150219,0.026284,...,-0.068272,-0.136070,0.153113,-0.416895,-0.325328,0.091150,-0.194366,0.271919,-0.036059,0.163504,0.471782,-0.022165,0.105701,-0.069878,-0.214171,0.466177,0.020430,-0.221446,0.026878,0.096617,-0.070467,-0.142519,0.259244,0.005026,0.311614,0.134012,-0.032285,0.438936,-0.320496,0.208710,0.027416,-0.249007,-0.234855,0.244458,0.262991,0.081080,-0.231061,0.153497,0.141053,-0.394979,-0.091540,-0.001636,0.174982,0.046464,0.059576,-0.281745,0.217085,-0.098526,0.146203,-0.193683
4,abilities,52,0.000014,16.172136,41,3.200140,131.205724,9,NNS,NN,4,"{JJ, NN, NNS, VB}",3,"{JJ, NN, VB}",0,abil,0.186644,-0.282482,0.068749,0.071084,0.126719,-0.013663,-0.043870,-0.006880,-0.125679,0.146638,0.014256,0.014327,0.142303,0.065827,-0.215124,-0.160649,-0.113400,0.148731,-0.040530,-0.104278,0.224125,-0.002260,0.318607,-0.060765,-0.173205,0.228168,-0.143238,-0.005909,-0.238135,0.059781,-0.292543,0.034477,0.077483,0.210570,...,0.070429,0.155890,0.053712,-0.162797,-0.201056,0.014155,-0.233580,-0.024798,-0.173749,0.188519,0.320606,-0.010641,0.019229,0.117449,0.083439,0.015313,0.238587,-0.158322,-0.004381,0.223742,-0.017075,-0.234570,-0.234631,-0.309367,0.069294,0.002154,0.036453,0.199421,-0.082475,-0.083592,0.174946,-0.040286,-0.169669,0.011341,-0.031096,-0.016848,-0.101683,0.053464,0.020794,-0.131648,0.050736,0.183318,-0.078571,-0.131802,-0.126832,-0.213738,0.208840,-0.163703,-0.083084,-0.062794
5,ability,183,0.000048,14.356876,72,2.402632,172.989538,7,NN,NN,5,"{IN, JJ, NN, NNP, VB}",4,"{IN, JJ, NN, VB}",0,abil,0.280273,-0.634262,0.082326,-0.038248,0.206475,0.342011,0.394721,-0.205207,-0.356822,0.547667,-0.101150,-0.167809,0.232119,0.012394,-0.271581,-0.475257,-0.166161,0.179520,0.051557,0.110431,0.181203,-0.104182,0.571533,-0.400611,-0.143906,0.262843,-0.370185,0.312001,-0.262561,-0.076070,-0.429380,-0.151090,0.346622,0.547441,...,0.011607,0.318721,0.085069,-0.072669,-0.292549,-0.031493,-0.626245,0.022393,-0.017425,0.133824,0.269246,-0.114458,-0.278463,0.144227,0.215204,0.043782,0.387335,-0.124135,-0.194682,0.419802,-0.152042,-0.265544,-0.510704,-0.134114,0.406410,-0.184190,0.253652,0.130813,-0.146651,-0.065169,0.126830,0.136681,-0.372119,-0.104794,-0.078420,0.175191,-0.275990,0.383000,-0.174290,-0.010054,0.027957,0.014638,-0.110223,-0.138287,-0.229885,-0.265432,0.392606,-0.268986,0.014189,-0.295286
6,able,320,0.000083,13.550648,97,1.977747,191.841478,4,JJ,JJ,5,"{JJ, NN, RB, VBN, VBP}",4,"{JJ, NN, RB, VB}",0,abl,-0.243594,0.000758,0.391418,-0.238888,-0.161739,0.081261,0.319770,-0.319149,-0.252433,0.266736,-0.160566,0.040336,-0.211683,-0.381376,-0.291230,-0.413447,0.343984,-0.367216,-0.349690,-0.147498,-0.348763,-0.172500,0.685050,-0.424180,0.301372,-0.123639,0.179986,0.030123,0.169220,-0.229416,-0.322528,0.117280,0.185825,-0.358402,...,-0.368907,0.731601,0.125198,0.252635,-0.102046,0.009393,0.055747,-0.288921,-0.083710,-0.156213,0.288128,-0.032510,-0.449884,0.443415,0.232244,0.130628,0.067390,0.083645,-0.495901,-0.234007,-0.014859,-0.150407,-0.161505,-0.131420,0.166029,-0.201906,-0.016753,0.020192,-0.040197,-0.570109,0.237679,0.020940,-0.172615,-0.267716,-0.123523,-0.070149,-0.066065,-0.037368,0.000534,-0.127627,-0.517186,-0.537465,-0.214139,0.054125,0.521900,-0.537991,0.395720,-0.082214,-0.142948,0.614511
7,aboard,35,0.000009,16.743293,19,4.270529,81.140050,6,IN,IN,2,"{IN, RP}",2,"{IN, RP}",0,aboard,0.183009,-0.305984,0.073363,-0.013043,0.005812,0.244486,-0.156676,0.194602,-0.311649,0.135114,-0.012522,0.007716,0.208108,-0.178637,-0.007561,-0.245625,-0.205599,0.069920,-0.116191,-0.034883,0.125489,-0.231211,0.097724,0.001921,0.209997,0.004504,-0.019005,0.101976,0.122845,-0.083300,0.082831,-0.025145,0.094842,0.095098,...,0.047689,0.043827,-0.341394,0.257838,-0.006420,-0.124274,-0.067042,-0.239633,-0.202831,-0.114037,0.145718,-0.172442,0.083971,0.064879,0.077025,0.040783,0.208527,-0.179229,-0.143323,-0.054094,0.035344,-0.064134,-0.275558,0.173550,0.198552,0.185151,-0.047574,0.006536,-0.094271,-0.251294,0.077407,0.133183,0.040681,-0.296508,-0.363652,-0.078688,0.010425,-0.086820,-0.062660,-0.321374,-0.120019,-0.040185,0.306200,-0.194338,0.016429,-0.349973,-0.067577,-0.353122,-0.227654,0.063122
8,abolish,72,0.000019,15.702651,57,2.734476,155.865134,7,VB,VB,5,"{CD, IN, JJ, NN, VB}",5,"{CD, IN, JJ, NN, VB}",0,abolish,0.190104,-0.115819,0.270387,-0.035566,0.111610,-0.012850,-0.158362,-0.120188,-0.002824,0.159612,-0.212079,0.465868,0.165137,-0.267521,-0.321152,0.024439,0.102036,0.231336,0.049979,0.175849,0.209499,-0.014279,-0.098538,0.084429,0.090008,0.147407,0.110348,-0.007369,-0.012325,-0.088249,-0.339995,0.064711,-0.175500,0.096438,...,0.009242,-0.039702,0.055158,-0.182282,-0.076894,0.107497,-0.169225,0.065492,-0.211515,0.062071,0.259667,0.085512,-0.223574,-0.076978,0.028878,-0.078690,0.103321,-0.003528,0.085151,0.169635,-0.207200,0.028349,0.036579,-0.123243,-0.058002,-0.219902,-0.149903,0.237143,0.228150,0.263546,0.250510,-0.069736,0.437845,-0.201621,0.093411,-0.016261,-0.064148,0.155588,0.086675,-0.251370,-0.058602,0.045551,-0.036455,0.236945,0.084479,-0.320522,0.174350,0.040641,0.207937,0.044234
9,abolished,104,0.000027,15.172136,68,2.483933,168.907415,9,VBN,VB,8,"{IN, JJ, NN, PDT, RB, VBD, VBN, VBZ}",6,"{DT, IN, JJ, NN, RB, VB}",0,abolish,0.200764,0.265510,0.007997,-0.092770,-0.129051,0.027872,-0.202203,-0.042334,-0.142991,0.126168,-0.068252,0.164254,-0.298917,0.019797,-0.036837,-0.063999,0.093589,0.294862,-0.107343,-0.025073,-0.324292,-0.324045,-0.022995,-0.382379,0.214477,-0.239850,0.052811,-0.010817,-0.015103,-0.096132,-0.175655,-0.310252,0.069984,0.049461,...,0.169879,-0.038638,0.044926,0.317776,-0.110653,0.050107,0.157479,-0.093149,-0.172993,-0.284227,-0.143798,-0.115752,-0.079065,-0.239419,-0.204017,0.295267,-0.225271,-0.017092,-0.240101,0.178285,-0.041540,0.034526,0.171497,0.277161,0.161045,0.125810,-0.112978,-0.045319,-0.092474,0.042608,0.246915,0.095397,-0.064424,0.011997,-0.025157,0.149691,-0.144089,0.076951,-0.041415,-0.147752,-0.213053,0.026796,0.201561,-0.028067,0.016319,-0.399046,0.234087,-0.036184,0.182109,-0.125289